.TH GM-ADJUST_DB_SETTINGS 8 "2010 April 23th" "GNUmed server adjust database"

.SH NAME
.B gm-adjust_db_settings
- GNUmed server adjust database settings

.SH SYNOPSIS
.B gm-adjust_db_settings
.I <target database>

.I <target database>:
a GNUmed database (such as "gnumed_VERSION")

.SH DESCRIPTION
The
.B gm-adjust_db_settings
script can be used to try to adjust database settings
if the GNUmed client complains about them at startup.

.SH AUTHOR
This manual page was written by Andreas Tille <tille@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
