.\" ========================================================
.\" license: GPL
.\" ========================================================

.TH GM-BOOTSTRAP_SERVER 8 "2009 January 4th" "Bootstrapping GNUmed Server"

.SH NAME
.B gm-bootstrap_server
- bootstrap the latest released version of the SQL database for GNUmed

.SH SYNOPSIS
.B gm-bootstrap_server

.SH DESCRIPTION
.B gm-bootstrap_server
is a simple helper script which is provided by the Debian
GNU/Linux distribution to simplify bootstrapping the GNUmed
database.

.SH WARNING
This script will
.B delete existing
GNUmed
.B databases
if necessary.

.SH AUTHOR
This manual page was written by Andreas Tille <tille@debian.org>
for the Debian GNU/Linux system (but may be used by others).

.SH REVISION

$Source: /home/ncq/Projekte/cvs2git/vcs-mirror/gnumed/gnumed/client/doc/man-pages/gm-bootstrap_server.8,v $

$Id: gm-bootstrap_server.8,v 1.2 2009-01-08 16:42:20 ncq Exp $

.\" ========================================================
.\" $Log: gm-bootstrap_server.8,v $
.\" Revision 1.2  2009-01-08 16:42:20  ncq
.\" - improved man page title
.\"
.\" Revision 1.1  2009/01/07 12:16:15  ncq
.\" - new
.\"
.\"