.\" ========================================================
.\" license: GPL v2 or later
.\" ========================================================

.TH gm-describe_file 1 "2016 January 1st" "Describe files from within GNUmed"


.SH NAME
.B gm-describe_file
- describes files from within GNUmed


.SH SYNOPSIS
.B gm-describe_file
.I <input file>
.I <metadata file>


.SH DESCRIPTION
.B gm-describe_file
is a helper script which GNUmed uses to extract metadata
from files for describing them to the user when needed.


.SH OPTIONS
.PP
.TP
.B input file
The file to describe.
.TP
.B metadata file
The file into which to store extracted metadata for description.

Defaults to (and overwrites) <input file>.txt if not given.


.SH SEE ALSO
.TP
.B exiftool(1)


.SH AUTHOR
This manual page was written by Karsten Hilbert <karsten.hilbert@gmx.net>
for the Debian GNU/Linux system (but may be used by others).
