.TH GM-FINGERPRINT_DB 8 "2011 Oct 22nd" "GNUmed server fingerprint database"

.SH NAME
.B gm-fingerprint_db
- GNUmed server fingerprint database

.SH SYNOPSIS
.B gm-fingerprint_db
.I <target database>
.I <gm-dbo password>
.I [--with-dump]

.I <target database>:
a GNUmed database (such as "gnumed_VERSION")

.I <gm-dbo password>
the password for the database owner <gm-dbo>

.I [--with-dump]
if this option is given a dump of the database schema structure
will be included created by:

	SELECT gm.concat_table_structure();

.SH DESCRIPTION
The
.B gm-fingerprint_db
script can be used to fingerprint a GNUmed database
in order to aid identifying particular databases
or verifying database transfers (not upgrades).

The fingerprint of the database is written to the file

.B 	gm_db-<target database>-fingerprint.log

in the current directory.

.SH EXAMPLES

Fingerprint the database gnumed_v20:

.B 	gm-fingerprint_db
gnumed_v20 secret-password

Include a database schema structure dump:

.B 	gm-fingerprint_db
gnumed_v20 secret-password --with-dump

.SH AUTHOR
This manual page was written by Karsten Hilbert <karsten.hilbert@gmx.net>.
