.\" ========================================================
.\" license: GPL v2 or later
.\" ========================================================

.TH GM-FIXUP_SERVER 8 "2009 January 4th" "Fixing the GNUmed Server"

.SH NAME
.B gm-fixup_server
- apply fixup scripts to an SQL database for GNUmed

.SH SYNOPSIS
.B gm-fixup_server
.I VERSION

.SH DESCRIPTION
.B gm-fixup_server
is a simple helper script which is provided by the Debian
GNU/Linux distribution to simplify applying fixups to the
GNUmed database
.I VERSION
.

.SH AUTHOR
This manual page was written by Karsten Hilbert <karsten.hilbert@gmx.net>
for the Debian GNU/Linux system (but may be used by others).

.SH REVISION

$Id: gm-fixup_server.8,v 1.1 2009-06-17 09:18:56 ncq Exp $
