.TH GM-REMOVE_PERSON 1 "2010 April 23th" "Remove person from GNUmed DB"

.SH NAME
.B gm-remove_person
- GNUmed server remove person from database 

.SH SYNOPSIS
.B gm-remove_person
.I <target database> <person PK> [END_TX]

.I <target database>:
a GNUmed database (such as "gnumed_v20")

.I <person PK>:
primary key of a person in that database

.I <END_TX>:
set this appropriately to commit the transaction removing
the person if you REALLY know what you are doing (read the
source of gm-remove_person if you don't)

.SH DESCRIPTION
The script
.B gm-remove_person
can be used to completely, irrevocably remove a person from
a GNUmed database.

.SH AUTHOR
This manual page was written by Andreas Tille <tille@debian.org>,
for the Debian GNU/Linux system (but may be used by others).

