.TH GM-RESTORE 8 "2016 March 13th" "GNUmed server database restore"

.SH NAME
.B gm-restore
- restoring a GNUmed database

.SH SYNOPSIS
.B gm-restore
.I <backup>

.I <backup>:
a database backup file ("backup-gnumed_vX-*.tar.bz2") created by gm-backup

.SH DESCRIPTION
The
.B gm-restore
script attempts to recreate from scratch the backed up GNUmed
database. It tries to be very conservative.

It is intended for interactive use by root and may have to be
adjusted to your needs.

.SH KNOWN PROBLEMS

Note that for some reason restoring does not work when
the backup file you intend to restore is a link to the
actual backup. Use the full path instead.

.SH SEE ALSO
gm-backup(8)

/etc/gnumed/gnumed-restore.conf

.SH AUTHOR
This manual page was written by Karsten Hilbert,
for the Debian GNU/Linux system (but may be used by others).
