.TH GM-SET_GM-DBO_PASSWORD 8 "2010 April 23th" "GNUmed: set gm-dbo password"

.SH NAME
.B gm-set_gm-dbo_password
- GNUmed server set gm-dbo password

.SH SYNOPSIS
.B gm-set_gm-dbo_password

.SH DESCRIPTION
The
.B gm-set_gm-dbo_password
script can be used to try to (re-)set the gm-dbo password.

.SH AUTHOR
This manual page was written by Karsten Hilbert.
