.\" ========================================================
.\" license: GPL v2 or later
.\" ========================================================

.TH GM-UPGRADE_SERVER 8 "2009 January 4th" "Upgrading GNUmed Server"

.SH NAME
.B gm-upgrade_server
- upgrade an existing SQL database for GNUmed to the next version

.SH SYNOPSIS
.B gm-upgrade_server
.I VERSION
.I VERSION+1
[
.I no-backup | no-check
]
[
.I quiet
]

.SH DESCRIPTION
.B gm-upgrade_server
is a simple helper script which is provided by the Debian
GNU/Linux distribution to simplify upgrading the GNUmed
database from version
.I VERSION
to the next version
.I VERSION+1.

.SH OPTIONS
.PP
.TP
.B no-backup
Do not create a database backup before upgrading (you got faith).
.TP
.B no-check
Do not check data checksum in the existing database before upgrading.
.TP
.B quiet
Display failures only, do not chatter about progress.

.SH WARNING
This script may result in
.B deletion of
existing GNUmed
.B databases
if so instructed.

.SH AUTHOR
This manual page was written by Karsten Hilbert <karsten.hilbert@gmx.net>.
