.TH GNUMED 1 "2007 September 5th" "Manual for GNUmed"

.SH NAME
.B GNUmed
- an electronic MEDICAL record software for GP offices

This is not fully featured yet. Use at your own risk.
You have been warned.

.SH SYNOPSIS
.B gnumed
.RB [--quiet|debug]
.RB [--slave]
.RB [--text-domain=TEXTDOMAIN]
.RB [--log-file=FILE]
.RB [--conf-file=FILE]
.RB [--lang-gettext=LANGUAGE]
.RB [--override-schema-check]
.RB [--local-import]
.RB [--help]
.RB [--version]
.RB [-V]
.RB [-h|?]

.SH DESCRIPTION
.B GNUmed
is a solution for keeping safe and medically sound electronic
records on a patient's health. It primarily focuses on GP
offices. It is released under the GPL.

GNUmed is written in Python with wxPython/wxWindows. Data is
stored in a PostgreSQL database. Multiple clients can work
with the same database at the same time.

.SH OPTIONS
.PP
.TP
.B \--quiet
Be extra quiet and show only _real_ errors in the log.
.TP
.B \--debug
Pre-set the [debug mode] checkbox in the login dialog
which controls increased verbosity in the log file.

Useful for, well, debugging :-)  Slower, too.
.TP
.B \--slave
Pre-set the [enable remote control] checkbox in the login
dialog to enable the XML-RPC remote control feature.
.TP
.B \--hipaa
Enable HIPAA features with user workflow impact.

Those features which do not affect the workflow of the user
are permanently enabled.
.TP
.B \--text-domain=TEXTDOMAIN
Set this to change the name of the language file to be loaded.
Note, this does not change the directory the file is searched in,
only the name of the file where messages are loaded from. The
standard textdomain is, of course, "gnumed.mo". You need only
specify the base name of the file without the .mo extension.
.TP
.B \--log-file=FILE
Use this to change the name of the log file. The default
log file would be <~/.gnumed/gnumed.log>.
.TP
.B \--conf-file=FILE
Use configuration file FILE instead of searching for it in
standard locations.
.TP
.B \--lang-gettext=LANGUAGE
Explicitely set the language to use in gettext translation. The very
same effect can be achieved by setting the environment variable $LANG
from a launcher script.
.TP
.B \--override-schema-check
Continue loading the client even if the database schema
version and the client software version cannot be verified
to be compatible.
.TP
.B \--local-import
At startup adjust the PYTHONPATH such that the GNUmed client is
run from a local copy of the source tree rather than from a
proper system-wide installation.
.TP
.B \--version, -V
Show version information about the GNUmed client and the
database it needs.
.TP
.B \--help, -h, or -?
Well, show this help.


.SH ENVIRONMENT
.TP
.B LANG, LC_MESSAGES, etc.
See gettext(1) for how the various locale related environment
variables work.


.SH FILES
.PP
.TP
.B ~/etc/gnumed/gnumed-client.conf
The system-wide configuration file.
.TP
.B ~/.gnumed/gnumed.conf
The user-specific configuration file.
.TP
.B ~/.gnumed/gnumed.log
The default log file.

.SH SEE ALSO
.PP
.TP
.B gettext(1)
.TP
.B http://wiki.gnumed.de
Detailed Wiki-style documentation
.TP
.B http://www.gnumed.org
Users' website
.TP
.B http://www.gnumed.de
German website
.TP
.B http://savannah.gnu.org/projects/gnumed
Source code repository (CVS)
.TP
.B /usr/share/doc/gnumed/
Local documentation

.SH BUGS

A lot of functionality is still missing. However, to make up for
that, we deliver a plethora of bugs for your amusement :-)

Use at your own risk. You have been warned. Take proper backups !

.SH REVISION

$Source: /home/ncq/Projekte/cvs2git/vcs-mirror/gnumed/gnumed/client/doc/man-pages/gnumed.1,v $

$Id: gnumed.1,v 1.21 2008-12-17 21:53:07 ncq Exp $
