#!/bin/sh

#------------------------------------------------------------------
# $Id: gm-mirror_vcs,v 1.1 2009-06-05 07:31:03 ncq Exp $
# $Source: /home/ncq/Projekte/cvs2git/vcs-mirror/gnumed/gm-mirror_vcs,v $
# $Revision: 1.1 $
#------------------------------------------------------------------

mkdir gm-vcs-mirror
rsync -avr rsync://cvs.sv.gnu.org/sources/gnumed/ gm-vcs-mirror/
tar -cvzf gm-vcs-mirror.tgz gm-vcs-mirror

#------------------------------------------------------------------
# $Log: gm-mirror_vcs,v $
# Revision 1.1  2009-06-05 07:31:03  ncq
# - first version
#
#