link:index.html[Home]

== GNUmed database upgrade

Use this procedure to _upgrade_ an _existing_ GNUmed
database. It is not intended for
link:GNUmedDatabaseInstallation.html[installing] a fresh
GNUmed database. It is also not intended for
https://www.postgresql.org/docs/devel/pgupgrade.html[upgrading
a PostgreSQL server].

'''''
CAUTION: GNUmed takes appropriate steps to protect
patient data but do make sure to have a known good
link:GNUmedDatabaseBackup.html[backup] before
applying upgrades or fixes.

'''''

Make sure you understand link:GNUmedDatabaseVersions.html[GNUmed database versions].

=== Applying a database fixup

This procedure applies when a minor-version database
revision has been released.

==== Debian based systems

	* check for the latest package which will typically have been upgraded to by the package management system
	* run the fixup script

As root (or with sudo):

-------------------------------------
	$> apt-cache policy gnumed-server
	$> gm-fixup_server
-------------------------------------

==== Other systems

	* https://www.gnumed.de/downloads/server/[download] the latest release https://www.gnumed.de/downloads/readme.txt[appropriate for your client]
	* unpack the tarball
	* run the fixup script

-------------------------------------
	$> mkdir gnumed
	$> cd gnumed
	$> wget -c https://www.gnumed.de/downloads/server/vXY/gnumed-server.XY.ZZ.tgz
	$> tar -xvzf gnumed-server.XY.ZZ.tgz
	$> cd gnumed-server.XY.ZZ/server/bootstrap/
	$> sudo ./fixup-db.sh XY
-------------------------------------

=== Applying a major-version upgrade

This procedure applies when a major-version database
revision has been released.

==== Debian based systems

	* check for the latest package which will typically have been upgraded to by the package management system
	* run the fixup script

As root (or with sudo):

-------------------------------------
	$> apt-cache policy gnumed-server
	$> gm-upgrade_server
-------------------------------------

==== Other systems

	* https://www.gnumed.de/downloads/server/[download] the latest release https://www.gnumed.de/downloads/readme.txt[appropriate for your client]
	* unpack the tarball
	* run the upgrade script

-------------------------------------
	$> mkdir gnumed
	$> cd gnumed
	$> wget -c https://www.gnumed.de/downloads/server/vXY/gnumed-server.XY.ZZ.tgz
	$> tar -xvzf gnumed-server.XY.ZZ.tgz
	$> cd gnumed-server.XY.ZZ/server/bootstrap/
	$> sudo ./upgrade-db.sh XY XY+1
-------------------------------------

'''''
link:index.html[Home]
