#!/bin/sh

BAK_BASE=~/".gnumed/backup"
#------------------------------------------------------------------

mkdir -p ${BAK_BASE}/vcs-mirror
cd ${BAK_BASE}/vcs-mirror


# Git
git clone git://gitorious.org/gnumed/gnumed.git
if test "$?" != "0" ; then
	cd gnumed
	git pull -v
	cd ..
fi


# CVS
#rsync -qar --delete rsync://cvs.sv.gnu.org/sources/gnumed/ .
#if test "$?" != "0" ; then
#	echo "Rsyncing VCS tree failed. Aborting."
#	exit 1
#fi


date > timestamp.txt

cd ..
tar -czf gm-vcs-mirror-day_`date +%u`.tgz vcs-mirror
