// File:  CosEventChannelAdmin.idl
// This file contains an abbreviated set of definitions, only those
// which are required by DsObservationAccess. 
// Use this file only when the standard CosEvent module
// is not available nor desired for compilation and runtime.

#ifndef _COS_EVENT_CHANNEL_ADMIN_IDL_
#define _COS_EVENT_CHANNEL_ADMIN_IDL_

#pragma prefix "omg.org"

module CosEventChannelAdmin {
 	exception AlreadyConnected {};
};
#endif /* ifndef _COS_EVENT_CHANNEL_ADMIN_IDL_ */
