
// Page 210 of CORBASec doc. describes AttributeList
#pragma prefix "omg.org"

module Security {

	typedef sequence<octet> Opaque;
	
	struct ExtensibleFamily {
		unsigned short family_definer;
		unsigned short family;
	};

	typedef unsigned long SecurityAttributeType;

	const SecurityAttributeType AuditId = 1;
	const SecurityAttributeType AccountingId = 2;
	const SecurityAttributeType NonRepudiationId = 3;


	//privilege attributes; family = 1;

	const SecurityAttributeType Public_ = 1;
	const SecurityAttributeType AccessId = 2;
	const SecurityAttributeType PrimaryGroupId = 3;
	const SecurityAttributeType GroupId = 4;
	const SecurityAttributeType Role = 5;
	const SecurityAttributeType AttributeSet = 6;
	const SecurityAttributeType Clearance = 7;
	const SecurityAttributeType Capability = 8;

	struct AttributeType {
		ExtensibleFamily	attribute_family;
		SecurityAttributeType   attribute_type;
	};

	typedef sequence<AttributeType> AttributeTypeList;

	struct SecAttribute {
		AttributeType 	attribute_type;
		Opaque		defining_authority;
		Opaque		value;
	};
	
	typedef sequence<SecAttribute> AttributeList;

};











	
