#!/bin/bash

WORKDIR="pdoc3"

rm -vf ${WORKDIR}/Gnumed/__pycache__/*
rm -vf ${WORKDIR}/Gnumed/*
rmdir -v ${WORKDIR}/Gnumed/__pycache__
rmdir -v ${WORKDIR}/Gnumed
rm -vfR ${WORKDIR}/api/*
rmdir -v ${WORKDIR}/api

mkdir -p ${WORKDIR}/Gnumed
cd ${WORKDIR}/Gnumed/
ln -s ../../../client/gnumed.py
ln -s ../../../client/pycommon
ln -s ../../../client/business
ln -s ../../../client/wxpython
ln -s ../../../client/wxg
ln -s ../../../client/connectors
ln -s ../../../client/exporters
#ln -s ../../../client/importers
cd -

cd ${WORKDIR}
export PYTHONPATH="${PYTHONPATH:+$PYTHONPATH:}./Gnumed/"
pdoc3 --force --html --skip-errors --output-dir api/ Gnumed
#pdoc3 --force --html --output-dir api/ Gnumed
date > api/Gnumed/generated.txt
cd -

rm -vf ${WORKDIR}/Gnumed/__pycache__/*
rm -vf ${WORKDIR}/Gnumed/*
rmdir -v ${WORKDIR}/Gnumed/__pycache__
rmdir -v ${WORKDIR}/Gnumed

exit 0


#---------------------------------------------
# old
#cd ~/gm-git/gnumed/gnumed/
#ln -sT client Gnumed
#cd -
#BASE=~/gm-git/gnumed/gnumed/Gnumed
##MODULES=" $BASE/pycommon/ $BASE/business/ $BASE/connectors/ $BASE/exporters/ $BASE/importers/ $BASE/wxpython/"
#LOG=~/gm-apidocs/epydoc-errors.txt
#
#export DISPLAY=":0.0"
#export PYTHONPATH="${PYTHONPATH}:~/gm-git/gnumed/gnumed/"
#mkdir ~/gm-apidocs
#nice -n 19 epydoc -v --debug --show-imports -n "GNUmed Never Sleeps" -u https://www.gnumed.org --no-private -o ~/gm-apidocs $BASE/ &> $LOG
#cat $LOG
