#!/bin/bash


DIRS="../client/pycommon ../client/business ../client/wxpython"
echo "=== $(date): pyflakes3 '${DIRS}' ==========" > source-coding_errors.log
pyflakes3 ${DIRS} &>> tmp-pyflakes3.log
grep --invert-match "undefined name '_'" tmp-pyflakes3.log &>> source-coding_errors.log
rm tmp-pyflakes3.log


echo "=== maintainability -- $(date): radon mi (lower = better, A/B not shown) ==========" > source-maintainability.log
radon mi ${DIRS} | egrep '\-\s[^AB]$' &>> source-maintainability.log


echo "=== cyclic complexity -- $(date) - radon cc (lower = better, A/B/C/D/E not shown) ==========" > source-cyclic_complexity.log
radon cc ${DIRS} | egrep '(\-\s[^ABCDE])|(.py)$' &>> source-cyclic_complexity.log


DIRS="../client/pycommon ../client/business"
for DIR in ${DIRS} ; do
	LOG=$(basename ${DIR})
	echo "=== $(date): pylint ${DIR} ==========" > source-coding_errors-pylint_${LOG}.log
	pylint --errors-only ${DIR}/*.py &>> source-coding_errors-pylint_${LOG}.log
done


MYPY_CMD="mypy --pretty --allow-redefinition --no-strict-optional --ignore-missing-imports --follow-imports silent"
echo "=== $(date): mypy ==========" > source-type_checking.log
echo "${MYPY_CMD}" &>> source-type_checking.log
for DIR in ${DIRS} ; do
	echo "=== ${DIR} ==========" &>> source-type_checking.log
	for PYFILE in ${DIR}/*.py ; do
		echo "----- ${PYFILE} --------------------------------------" &>> source-type_checking.log
		${MYPY_CMD} ${PYFILE} &>> source-type_checking.log
	done
done
##--warn-unreachable
##--check-untyped-defs
##--warn-return-any
##--html-report ./
## --allow-untyped-globals


exit 0
