#!/bin/bash


DIRS="../client/pycommon ../client/business ../client/wxpython"
echo "=== $(date): pyflakes3 '${DIRS}' ==========" > source-coding_errors.log
pyflakes3 ${DIRS} &>> tmp-pyflakes3.log
#grep --invert-match "'Gnumed.pycommon.gmLog2' imported but unused" tmp-pyflakes3.log &>> tmp-grep_gmlog2.log
#grep --invert-match "undefined name '_'" tmp-grep_gmlog2.log &>> source-coding_errors.log
grep --invert-match "undefined name '_'" tmp-pyflakes3.log &>> source-coding_errors.log


echo "=== maintainability -- $(date): radon mi (lower = better, A/B not shown) ==========" > source-maintainability.log
radon mi ${DIRS} | egrep '\-\s[^AB]$' &>> source-maintainability.log


echo "=== cyclic complexity -- $(date) - radon cc (lower = better, A/B/C/D not shown) ==========" > source-cyclic_complexity.log
radon cc ${DIRS} | egrep '(\-\s[^ABCD])|(.py)$' &>> source-cyclic_complexity.log


DIRS="../client/pycommon ../client/business"
for DIR in ${DIRS} ; do
	LOG=$(basename ${DIR})
	echo "=== $(date): pylint ${DIR} ==========" > source-coding_errors-pylint_${LOG}.log
	pylint --errors-only ${DIR}/*.py &>> source-coding_errors-pylint_${LOG}.log
done


echo "=== $(date): mypy ==========" > source-type_checking.log
for DIR in ${DIRS} ; do
	echo "=== ${DIR} ==========" &>> source-type_checking.log
	for PYFILE in ${DIR}/*.py ; do
		echo "----- ${PYFILE} --------------------------------------" &>> source-type_checking.log
		mypy --pretty --no-strict-optional --ignore-missing-imports --follow-imports silent ${PYFILE} &>> source-type_checking.log
	done
done
##mypy --allow-redefinition --ignore-missing-imports --check-untyped-defs --warn-return-any --warn-unreachable --pretty ${DIRS} &>> source-type_checking.log
##mypy --html-report ./ --allow-redefinition --ignore-missing-imports --check-untyped-defs --warn-return-any --warn-unreachable ${DIRS}
## --allow-untyped-globals


exit 0
