#!/bin/bash

DIRS="../client/pycommon ../client/business ../client/wxpython"

echo "=== Code - problems ($(date) - pyflakes3) ==========" > source-coding_errors.log
pyflakes3 ${DIRS} &>> source-coding_errors.log

echo "=== Code - maintainability ($(date) - radon mi, lower = better) ==========" > source-maintainability.log
radon mi ${DIRS} | egrep '\-\s[^AB]$' &>> source-maintainability.log

echo "=== Code - cyclic complexity ($(date) - radon cc, lower = better) ==========" > source-cyclic_complexity.log
radon cc ${DIRS} | egrep '(\-\s[^AB])|(.py)$' &>> source-cyclic_complexity.log

#echo "=== Code - type checking ($(date) - mypy) ==========" > source-type_checking.log
#DIRS="../client/pycommon/"
#mypy --allow-redefinition --ignore-missing-imports --check-untyped-defs --warn-return-any --warn-unreachable --pretty ${DIRS} &>> source-type_checking.log
##mypy --html-report ./ --allow-redefinition --ignore-missing-imports --check-untyped-defs --warn-return-any --warn-unreachable ${DIRS}
## --allow-untyped-globals
