#!/bin/bash

rm --verbose --force html/*.html

for ADOC in website/*.adoc ; do
	./convert_adoc2html ${ADOC}
	RESULT="$?"
	if test "${RESULT}" != "0" ; then
		echo "Cannot convert asciidoc (${ADOC}) to html5 (${RESULT}). Aborting."
		exit ${RESULT}
	fi
done;

read -p "Hit [ENTER] for uploading website updates "
rsync --verbose --progress --checksum --human-readable html/*.html gm-vm:gm-website/
RESULT="$?"
if test "${RESULT}" != "0" ; then
	echo "Cannot upload html files (${RESULT}). Aborting."
	exit ${RESULT}
fi

rm --verbose --force html/*.html
