#!/bin/sh

rm --verbose --force html/*.html

for ADOC in website/*.adoc ; do
	./convert_adoc2html ${ADOC}
#	asciidoc --backend=html5 --verbose ${ADOC}
#	#--section-numbers
#	#--safe
	RESULT="$?"
	if test "${RESULT}" != "0" ; then
		echo "Cannot convert asciidoc (${ADOC}) to html5 (${RESULT}). Aborting."
		exit ${RESULT}
	fi
done;

rsync --verbose --progress --checksum --human-readable html/*.html www.gnumed.de:gm-website/
RESULT="$?"
if test "${RESULT}" != "0" ; then
	echo "Cannot upload html files (${RESULT}). Aborting."
	exit ${RESULT}
fi

rm --verbose --force html/*.html
