/*
 * ContactsInnerFrame1.java
 *
 * Created on 22 August 2003, 10:32
 */

package quickmed.usecases.test;

/**
 *
 * @author  sjtan
 */
public class ContactsInnerFrame1 extends javax.swing.JInternalFrame {
     private ContactsPanel contactPanel;
    /** Creates new form ContactsInnerFrame1 */
    public ContactsInnerFrame1() {
        initComponents();
        initContactsPanel();
    }
    void   initContactsPanel() {
        contactPanel = new ContactsPanel();
        jPanel1.add(contactPanel, java.awt.BorderLayout.CENTER);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        generateLetterButton = new javax.swing.JButton();

        setTitle(java.util.ResourceBundle.getBundle("SummaryTerms").getString("contacts"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        generateLetterButton.setText(java.util.ResourceBundle.getBundle("SummaryTerms").getString("referral_letter"));
        generateLetterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateLetterButtonActionPerformed(evt);
            }
        });

        jPanel1.add(generateLetterButton, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void generateLetterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateLetterButtonActionPerformed
        // Add your handling code here:
        if ( contactPanel.getSelectedProvider() != null) {
            
            
        }
    }//GEN-LAST:event_generateLetterButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateLetterButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
