/*
 * ProblemDialog.java
 *
 * Created on 11 August 2003, 10:02
 */

package quickmed.usecases.test;
import javax.swing.event.*;
import java.awt.event.KeyEvent;
import java.awt.KeyboardFocusManager;
import javax.swing.*;

import java.util.*;
import org.drugref.*;
/**
 *
 * @author  sjtan
 */
public class ProblemDialog extends javax.swing.JDialog implements SearchSelectable  {
    
    /** Creates new form ProblemDialog */
    public ProblemDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("condition");
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        jTextField1.setColumns(20);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel2.add(jTextField1, new java.awt.GridBagConstraints());

        jButton1.setText("clear");
        jPanel2.add(jButton1, new java.awt.GridBagConstraints());

        jLabel2.setText("prefix filter");
        jPanel2.add(jLabel2, new java.awt.GridBagConstraints());

        jTextField2.setColumns(4);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jPanel2.add(jTextField2, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
        // Add your handling code here:
         if ( evt.getKeyCode() == evt.VK_UP && jList1.getSelectedIndex() == 0) {
            jList1.transferFocus();
            jTextField1.requestFocusInWindow();
        }
        if (evt.getKeyCode() == evt.VK_ENTER)
            setVisible(false);
    }//GEN-LAST:event_jList1KeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // Add your handling code here:
        try {
        List l = TestProblemManager.instance().findDiseaseCodeByDescription(jTextField1.getText());
        jList1.setListData(l.toArray());
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        new ProblemDialog(new javax.swing.JFrame(), true).show();
    }
    
    public Object getSelectedItem() {
        return jList1.getSelectedValue();
    }    
    
    public void setSearchText(String text) {
        jTextField1.setText(text);
        jTextField1ActionPerformed(new java.awt.event.ActionEvent(jTextField1, 1, "search"));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    
}
