/*
 * TestScriptPreviewPanel.java
 *
 * Created on 1 September 2003, 23:57
 */

package quickmed.usecases.test;
import java.awt.print.*;
import java.awt.Point;
import java.awt.Component;
import javax.swing.*;
import java.util.logging.*;
import java.util.*;
import javax.print.*;
import javax.print.attribute.*;
import javax.print.attribute.standard.*;


/**
 *
 * @author  syan
 */
public class TestScriptPreviewPanel extends javax.swing.JPanel {
    private   TestBasicScriptPrintable test = new TestBasicScriptPrintable();
    //    private   MedicareBasicScriptPrintable printable = (MedicareBasicScriptPrintable)test.getBasicScriptPrintable();
    private JPanel[] previews;
    /** Creates new form TestScriptPreviewForm */
    public TestScriptPreviewPanel() {
        initComponents();
        setBasicScriptPrintable(test.getBasicScriptPrintable());
        initOriginFields();
    }
    
    void initOriginFields() {
        if (getBasicScriptPrintable() instanceof BasicScriptFormLayoutAdjustable) {
            BasicScriptFormLayoutAdjustable p = (BasicScriptFormLayoutAdjustable) getBasicScriptPrintable();
            ProviderOriginTextField1.setText( getTextFromPoint(p.getOriginProviderDetails() ) );
            PatientOriginTextField3.setText( getTextFromPoint(p.getOriginPatientDetail() ));
            PrescriptionOriginTextField5.setText( getTextFromPoint(p.getOriginDrugDetails() ));
            DateOriginTextField4.setText( getTextFromPoint(p.getOriginDate()) );
            subsidizedOriginTextField.setText( getTextFromPoint(p.getOriginSubsidized() ));
            MedicareOriginTextField.setText(  getTextFromPoint(p.getOriginHealthNumber() ));
            fontSizeTextField1.setText( Integer.toString( p.getFontSize()) );
            splitWidthTextField1.setText( Integer.toString(p.getSplitWidth()) );
            jSpinner1.getModel().setValue(new Integer( p.getLeftMargin() ) );
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ProviderOriginTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        MedicareOriginTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PatientOriginTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DateOriginTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PrescriptionOriginTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        subsidizedOriginTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        splitWidthTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fontSizeTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        jButton1.setText("test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.add(jButton1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("provider origin");
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        ProviderOriginTextField1.setText("providerOriginTextField");
        jPanel2.add(ProviderOriginTextField1, new java.awt.GridBagConstraints());

        jLabel2.setText("health no. origin");
        jPanel2.add(jLabel2, new java.awt.GridBagConstraints());

        MedicareOriginTextField.setText("jTextField2");
        jPanel2.add(MedicareOriginTextField, new java.awt.GridBagConstraints());

        jLabel3.setText("patient detail origin");
        jPanel2.add(jLabel3, new java.awt.GridBagConstraints());

        PatientOriginTextField3.setText("jTextField3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel2.add(PatientOriginTextField3, gridBagConstraints);

        jLabel4.setText("date origin");
        jPanel2.add(jLabel4, new java.awt.GridBagConstraints());

        DateOriginTextField4.setText("jTextField4");
        jPanel2.add(DateOriginTextField4, new java.awt.GridBagConstraints());

        jLabel5.setText("prescription origin");
        jPanel2.add(jLabel5, new java.awt.GridBagConstraints());

        PrescriptionOriginTextField5.setText("jTextField5");
        jPanel2.add(PrescriptionOriginTextField5, new java.awt.GridBagConstraints());

        jLabel6.setText("subsidized Origin");
        jPanel2.add(jLabel6, new java.awt.GridBagConstraints());

        subsidizedOriginTextField.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel2.add(subsidizedOriginTextField, gridBagConstraints);

        jLabel7.setText("split width");
        jPanel2.add(jLabel7, new java.awt.GridBagConstraints());

        splitWidthTextField1.setText("jTextField1");
        jPanel2.add(splitWidthTextField1, new java.awt.GridBagConstraints());

        jLabel8.setText("fontSize");
        jPanel2.add(jLabel8, new java.awt.GridBagConstraints());

        fontSizeTextField1.setText("jTextField1");
        jPanel2.add(fontSizeTextField1, new java.awt.GridBagConstraints());

        jLabel9.setText(java.util.ResourceBundle.getBundle("SummaryTerms").getString("leftMargin"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel2.add(jLabel9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        jPanel2.add(jSpinner1, gridBagConstraints);

        jButton2.setText(java.util.ResourceBundle.getBundle("SummaryTerms").getString("print"));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton2, new java.awt.GridBagConstraints());

        jPanel3.add(jPanel2, java.awt.BorderLayout.SOUTH);

        add(jPanel3, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Add your handling code here:
        printAction(evt);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
        testAction();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DateOriginTextField4;
    private javax.swing.JTextField MedicareOriginTextField;
    private javax.swing.JTextField PatientOriginTextField3;
    private javax.swing.JTextField PrescriptionOriginTextField5;
    private javax.swing.JTextField ProviderOriginTextField1;
    private javax.swing.JTextField fontSizeTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField splitWidthTextField1;
    private javax.swing.JTextField subsidizedOriginTextField;
    // End of variables declaration//GEN-END:variables
    
    /** Holds value of property basicScriptPrintable. */
    private BasicScriptPrintable basicScriptPrintable;
    
    
    static class PreviewPainter implements Runnable {
        private Printable printable;
        private Component component;
        private int index;
        public PreviewPainter( Component comp, Printable printable, int index) {
            this.printable = printable;
            this.component = comp;
            this.index = index;
        }
        
        public void run() {
            try {
                printable.print(component.getGraphics(), new PageFormat(), index);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
    }
    
    static class RunnableFocusListener extends  java.awt.event.FocusAdapter {
        Runnable runnable;
        public RunnableFocusListener(Runnable r) {
            this.runnable = r;
        }
        public void focusGained(java.awt.event.FocusEvent ev) {
            Logger.global.info("PAINTING USING " + runnable);
            SwingUtilities.invokeLater(runnable);
        }
    }
    
    static class RunnableComponentListener implements java.awt.event.ComponentListener {
        Runnable runnable;
        public RunnableComponentListener(Runnable r) {
            this.runnable = r;
        }
        public void componentHidden(java.awt.event.ComponentEvent e) {
        }
        
        public void componentMoved(java.awt.event.ComponentEvent e) {
        }
        
        public void componentResized(java.awt.event.ComponentEvent e) {
        }
        
        public void componentShown(java.awt.event.ComponentEvent e) {
            Logger.global.info("PAINTING USING " + runnable);
            
            SwingUtilities.invokeLater(runnable);
        }
        
    }
    
    void printAction(java.awt.event.ActionEvent evt) {
        configurePrintLocations();
        DocFlavor flavor = DocFlavor.SERVICE_FORMATTED.PAGEABLE;
        
        
        HashPrintRequestAttributeSet attributes = new HashPrintRequestAttributeSet();
        //        attributes.add( MediaSizeName.ISO_A4);
        //        attributes.add( MediaSizeName.FOLIO);
        //
        
        
        PrintService[] services = PrintServiceLookup.lookupPrintServices(flavor, attributes);
        List list = new ArrayList();
        list.addAll(Arrays.asList(services));
        
        services = new PrintService[] { PrintServiceLookup.lookupDefaultPrintService() };
        list.addAll(Arrays.asList(services));
        services = (PrintService[]) list.toArray( new PrintService[0]);
        
        PrintService service = ServiceUI.printDialog(null,
        ((java.awt.Component)evt.getSource()).getX(),
        ((java.awt.Component)evt.getSource()).getY() ,
        services, null,  flavor,   attributes) ;
        SimpleDoc doc = new SimpleDoc( getBasicScriptPrintable().getPageable() , flavor, null);
        try {
            service.createPrintJob().print(doc, attributes);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    void testAction() {
        // Add your handling code here:
        configurePrintLocations();
        try {
            //            test.test();
            BasicScriptPrintable bp = getBasicScriptPrintable();
            int pages = bp.getPageable().getNumberOfPages();
            setPages(pages);
            //            for (int i = 0; i < pages; ++i) {
            //                TestScriptPreviewPanel.PreviewPainter painter =
            //                new TestScriptPreviewPanel.PreviewPainter(previews[i], bp.getPageable().getPrintable(i), i ) ;
            //                previews[i].setRunnable(painter);
            //
            ////                TestScriptPreviewPanel.RunnableComponentListener listener = new TestScriptPreviewPanel.RunnableComponentListener(
            //                painter
            //                ) ;
            //                System.out.println("MADE  FOR " + previews[i] + listener);
            //                previews[i].addComponentListener( listener);
            //                previews[i].addFocusListener(new RunnableFocusListener(painter) );
            //            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    void configurePrintLocations() {
        setPointsFromFields();
        setSplitWidth();
        setFontSize();
        setLeftMargin();
    }
    
    void setPages(int pages) {
        jTabbedPane1.removeAll();
        previews = new JPanel[pages];
        for (int i = 0; i < pages; ++i) {
            previews[i] =createPreviewPanel(i);
            jTabbedPane1.addTab("Page " + Integer.toString(i) , previews[i]);
        }
        
    }
    
    static class PreviewPanel extends JPanel {
        Printable printable; PageFormat format ; int index;
        public PreviewPanel( Printable p, PageFormat format, int index) {
            this.printable = p;
            this.format = format;
            this.index = index;
        }
        public void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);
            try {
                printable.print(g, format, index);
            } catch (Exception e) {
                e.printStackTrace();
            }
            
        }
    }
    
    public JPanel createPreviewPanel(int i ) {
        return new PreviewPanel( getBasicScriptPrintable().getPageable().getPrintable(i),
        getBasicScriptPrintable().getPageable().getPageFormat(i), i);
    }
    
    
    void setPointsFromFields() {
        if ( getBasicScriptPrintable() instanceof BasicScriptFormLayoutAdjustable) {
            BasicScriptFormLayoutAdjustable  q = (BasicScriptFormLayoutAdjustable) getBasicScriptPrintable();
            Point p = getPointFromText(ProviderOriginTextField1.getText());
            if (p != null)
                q. setOriginProviderDetails( p  );
            Point p2 = getPointFromText(MedicareOriginTextField.getText());
            if (p2 != null)
                q.setOriginHealthNumber(p2);
            Point p3 = getPointFromText(DateOriginTextField4.getText());
            if (p3 != null)
                q.setOriginDate(p3);
            Point p4 = getPointFromText(PatientOriginTextField3.getText());
            if ( p4 != null)
                q.setOriginPatientDetail(p4);
            Point p5 = getPointFromText(PrescriptionOriginTextField5.getText());
            if (p5 != null)
                q.setOriginDrugDetails(p5);
            Point p6 = getPointFromText(subsidizedOriginTextField.getText());
            if (p6 != null)
                q.setOriginSubsidized(p6);
        }
    }
    
    void  setSplitWidth() {
        try {
            BasicScriptFormLayoutAdjustable f = (BasicScriptFormLayoutAdjustable) getBasicScriptPrintable();
            f.setSplitWidth(Integer.parseInt(splitWidthTextField1.getText().trim()));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    void setLeftMargin() {
        try {
            BasicScriptFormLayoutAdjustable f = (BasicScriptFormLayoutAdjustable) getBasicScriptPrintable();
            f.setLeftMargin( ((Integer)jSpinner1.getModel().getValue() ).intValue() );
        }catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    void   setFontSize() {
        try {
            BasicScriptFormLayoutAdjustable f = (BasicScriptFormLayoutAdjustable) getBasicScriptPrintable();
            f.setFontSize(Integer.parseInt(fontSizeTextField1.getText().trim()));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    
    public static java.awt.Point getPointFromText( String text) {
        text = text.trim();
        String[] parts = text.split(",");
        if (parts.length != 2)
            return null;
        try {
            int x = Integer.parseInt(parts[0].trim());
            int y = Integer.parseInt(parts[1].trim());
            java.awt.Point p = new java.awt.Point(x,y);
            return p;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }
    
    public static String getTextFromPoint(Point p) {
        return Integer.toString(p.x) +  ", " + Integer.toString(p.y);
        
    }
    
    
    /** Getter for property basicScriptPrintable.
     * @return Value of property basicScriptPrintable.
     *
     */
    public BasicScriptPrintable getBasicScriptPrintable() {
        return this.basicScriptPrintable;
    }
    
    /** Setter for property basicScriptPrintable.
     * @param basicScriptPrintable New value of property basicScriptPrintable.
     *
     */
    public void setBasicScriptPrintable(BasicScriptPrintable basicScriptPrintable) {
        this.basicScriptPrintable = basicScriptPrintable;
        if (basicScriptPrintable instanceof BasicScriptFormLayoutAdjustable)
            initOriginFields();
    }
    
}
