/*
 * TestScriptPreviewForm.java
 *
 * Created on 31 August 2003, 21:53
 */

package quickmed.usecases.test;
import java.awt.print.*;
import java.awt.Point;
/**
 *
 * @author  syan
 * Preliminary test gui for script preview and printing.
 *
 */
public class TestScriptPreviewForm extends javax.swing.JFrame {
    private   TestBasicScriptPrintable test = new TestBasicScriptPrintable();
    private   MedicareBasicScriptPrintable printable = (MedicareBasicScriptPrintable)test.getBasicScriptPrintable();
    /** Creates new form TestScriptPreviewForm */
    public TestScriptPreviewForm() {
        initComponents();
        initOriginFields();
    }
    
    void initOriginFields() {
        MedicareBasicScriptPrintable.MedicarePrintable p =  printable.getMedicarePrintable();
        ProviderOriginTextField1.setText( getTextFromPoint(p.getOriginProviderDetail() ) );
        PatientOriginTextField3.setText( getTextFromPoint(p.getOriginPatientDetail() ));
        PrescriptionOriginTextField5.setText( getTextFromPoint(p.getOriginScriptDetail() ));
        DateOriginTextField4.setText( getTextFromPoint(p.getOriginDate()) );
        subsidizedOriginTextField.setText( getTextFromPoint(p.getOriginSubsidized() ));
        MedicareOriginTextField.setText(  getTextFromPoint(p.getOriginMedicareNumber() ));
        fontSizeTextField1.setText( Integer.toString( p.getFontSize()) );
        splitWidthTextField1.setText( Integer.toString(p.getSplitWidth()) );
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ProviderOriginTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        MedicareOriginTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PatientOriginTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DateOriginTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PrescriptionOriginTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        subsidizedOriginTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        splitWidthTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fontSizeTextField1 = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        jButton1.setText("test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.add(jButton1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("provider origin");
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        ProviderOriginTextField1.setText("providerOriginTextField");
        jPanel2.add(ProviderOriginTextField1, new java.awt.GridBagConstraints());

        jLabel2.setText("health no. origin");
        jPanel2.add(jLabel2, new java.awt.GridBagConstraints());

        MedicareOriginTextField.setText("jTextField2");
        jPanel2.add(MedicareOriginTextField, new java.awt.GridBagConstraints());

        jLabel3.setText("patient detail origin");
        jPanel2.add(jLabel3, new java.awt.GridBagConstraints());

        PatientOriginTextField3.setText("jTextField3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel2.add(PatientOriginTextField3, gridBagConstraints);

        jLabel4.setText("date origin");
        jPanel2.add(jLabel4, new java.awt.GridBagConstraints());

        DateOriginTextField4.setText("jTextField4");
        jPanel2.add(DateOriginTextField4, new java.awt.GridBagConstraints());

        jLabel5.setText("prescription origin");
        jPanel2.add(jLabel5, new java.awt.GridBagConstraints());

        PrescriptionOriginTextField5.setText("jTextField5");
        jPanel2.add(PrescriptionOriginTextField5, new java.awt.GridBagConstraints());

        jLabel6.setText("subsidized Origin");
        jPanel2.add(jLabel6, new java.awt.GridBagConstraints());

        subsidizedOriginTextField.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel2.add(subsidizedOriginTextField, gridBagConstraints);

        jLabel7.setText("split width");
        jPanel2.add(jLabel7, new java.awt.GridBagConstraints());

        splitWidthTextField1.setText("jTextField1");
        jPanel2.add(splitWidthTextField1, new java.awt.GridBagConstraints());

        jLabel8.setText("fontSize");
        jPanel2.add(jLabel8, new java.awt.GridBagConstraints());

        fontSizeTextField1.setText("jTextField1");
        jPanel2.add(fontSizeTextField1, new java.awt.GridBagConstraints());

        jPanel3.add(jPanel2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
        setPointsFromFields();
        setSplitWidth();
        setFontSize();
        
        try {
            //            test.test();
            BasicScriptPrintable bp = test.getBasicScriptPrintable();
            bp.getPageable().getPrintable(0).print(jPanel1.getGraphics(), new PageFormat(), 0);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    void setPointsFromFields() {
        
        Point p = getPointFromText(ProviderOriginTextField1.getText());
        if (p != null)
            printable.getMedicarePrintable().setOriginProviderDetail( p  );
        Point p2 = getPointFromText(MedicareOriginTextField.getText());
        if (p2 != null)
            printable.getMedicarePrintable().setOriginMedicareNumber(p2);
        Point p3 = getPointFromText(DateOriginTextField4.getText());
        if (p3 != null)
            printable.getMedicarePrintable().setOriginDate(p3);
        Point p4 = getPointFromText(PatientOriginTextField3.getText());
        if ( p4 != null)
            printable.getMedicarePrintable().setOriginPatientDetail(p4);
        Point p5 = getPointFromText(PrescriptionOriginTextField5.getText());
        if (p5 != null)
            printable.getMedicarePrintable().setOriginScriptDetail(p5);
        Point p6 = getPointFromText(subsidizedOriginTextField.getText());
        if (p6 != null)
            printable.getMedicarePrintable().setOriginSubsidized(p6);
    }
    
    void  setSplitWidth() {
        try {
            printable.setSplitWidth(Integer.parseInt(splitWidthTextField1.getText().trim()));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    void   setFontSize() {
         try {
            printable.setFontSize(Integer.parseInt(fontSizeTextField1.getText().trim()));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new TestScriptPreviewForm().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DateOriginTextField4;
    private javax.swing.JTextField MedicareOriginTextField;
    private javax.swing.JTextField PatientOriginTextField3;
    private javax.swing.JTextField PrescriptionOriginTextField5;
    private javax.swing.JTextField ProviderOriginTextField1;
    private javax.swing.JTextField fontSizeTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField splitWidthTextField1;
    private javax.swing.JTextField subsidizedOriginTextField;
    // End of variables declaration//GEN-END:variables
    
    public static java.awt.Point getPointFromText( String text) {
        text = text.trim();
        String[] parts = text.split(",");
        if (parts.length != 2)
            return null;
        try {
            int x = Integer.parseInt(parts[0].trim());
            int y = Integer.parseInt(parts[1].trim());
            java.awt.Point p = new java.awt.Point(x,y);
            return p;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }
    
    public static String getTextFromPoint(Point p) {
        return Integer.toString(p.x) +  ", " + Integer.toString(p.y);
        
    }
}
