/*
 * TestReferralInternalFrame.java
 *
 * Created on 22 August 2003, 22:23
 */

package quickmed.usecases.test;

/**
 *
 * @author  sjtan
 */
public class TestReferralInternalFrame extends javax.swing.JInternalFrame implements ClientProviderRelatable {
    private TestReferralPanel referral;
    /** Creates new form TestReferralInternalFrame */
    public TestReferralInternalFrame() {
        initComponents();
        referral = new TestReferralPanel();
        setContentPane(referral);
        pack();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle(java.util.ResourceBundle.getBundle("SummaryTerms").getString("referral_helper"));
        pack();
    }//GEN-END:initComponents

    public org.gnumed.gmIdentity.identity getClient() {
        return referral.getClient();
    }    
    
    public org.gnumed.gmIdentity.identity getProvider() {
        return referral.getProvider();
        
    }    
    
    public void setClient(org.gnumed.gmIdentity.identity client) {
         referral.setClient(  client) ;
         org.gnumed.gmIdentity.Names n = client.findNames(0);
         setTitle( new StringBuffer().append(Globals.bundle.getString("referral_helper")).
         append(" for ").append(n.getLastnames()).append(", ").append(n.getFirstnames()).toString());
    }
    
    public void setProvider(org.gnumed.gmIdentity.identity provider) {
         referral.setProvider(  provider);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
