/*
 * TestScriptPreviewPanelTestFrame.java
 *
 * Created on 2 September 2003, 00:18
 */

package quickmed.usecases.test;

/**
 *
 * @author  syan
 */
public class TestScriptPreviewPanelTestFrame extends javax.swing.JFrame {
    
    /** Creates new form TestScriptPreviewPanelTestFrame */
    public TestScriptPreviewPanelTestFrame() {
        initComponents();
        getContentPane().add( new TestScriptPreviewPanel() );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new TestScriptPreviewPanelTestFrame().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
