# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4cvs on Sun Jan 15 22:20:11 2006

import wx

# begin wxGlade: dependencies
import wx.grid
# end wxGlade

from  Gnumed.wxpython.gmAU_DBUserSetup import cAU_DBUserSetup
from Gnumed.pycommon import gmDispatcher, gmSignals, gmPG

from Gnumed.wxpython.gmDemographicsWidgets import cNewPatientWizard

from Gnumed.wxpython.gmAU_ProviderFind import cAU_ProviderFind

class cAU_AppointV01(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: cAU_AppointV01.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_3 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, -1)
        self.window_1 = wx.SplitterWindow(self.notebook_1_pane_2, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.window_1_pane_2 = wx.Panel(self.window_1, -1)
        self.window_2 = wx.SplitterWindow(self.window_1_pane_2, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.window_2_pane_2 = wx.Panel(self.window_2, -1)
        self.window_2_pane_1 = wx.Panel(self.window_2, -1)
        self.window_1_pane_1 = wx.Panel(self.window_1, -1)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        self.notebook_2 = wx.Notebook(self.notebook_1_pane_1, -1, style=0)
        self.sizer_20_staticbox = wx.StaticBox(self.notebook_1_pane_1, -1, "Appointment Views")
        self.sizer_13_staticbox = wx.StaticBox(self.window_2_pane_1, -1, "Session Manager")
        self.sizer_9_staticbox = wx.StaticBox(self.window_2_pane_2, -1, "holidays")
        self.sizer_1_staticbox = wx.StaticBox(self, -1, "Provider Management")
        self.notebook_2_pane_1 = wx.Panel(self.notebook_2, -1)
        self.button_13 = wx.Button(self.notebook_2_pane_1, -1, "button_13")
        self.combo_box_9 = wx.ComboBox(self.notebook_2_pane_1, -1, choices=[], style=wx.CB_DROPDOWN)
        self.button_14 = wx.Button(self.notebook_2_pane_1, -1, "button_14")
        self.grid_2 = wx.grid.Grid(self.notebook_2_pane_1, -1, size=(1, 1))
        self.button_11 = wx.Button(self.window_1_pane_1, -1, "use selected")
        self.button_12 = wx.Button(self.window_1_pane_1, -1, "new provider")
        self.list_box_1 = wx.ListBox(self.window_1_pane_1, -1, choices=[])
        self.label_12 = wx.StaticText(self.window_2_pane_1, -1, "start time")
        self.text_ctrl_7 = wx.TextCtrl(self.window_2_pane_1, -1, "")
        self.label_13 = wx.StaticText(self.window_2_pane_1, -1, "end time")
        self.text_ctrl_8 = wx.TextCtrl(self.window_2_pane_1, -1, "")
        self.checkbox_1 = wx.CheckBox(self.window_2_pane_1, -1, "mon")
        self.checkbox_2 = wx.CheckBox(self.window_2_pane_1, -1, "tue")
        self.checkbox_3 = wx.CheckBox(self.window_2_pane_1, -1, "wed")
        self.checkbox_4 = wx.CheckBox(self.window_2_pane_1, -1, "thur")
        self.checkbox_5 = wx.CheckBox(self.window_2_pane_1, -1, "fri")
        self.checkbox_6 = wx.CheckBox(self.window_2_pane_1, -1, "sat")
        self.checkbox_7 = wx.CheckBox(self.window_2_pane_1, -1, "sun")
        self.label_14 = wx.StaticText(self.window_2_pane_1, -1, "starting on")
        self.combo_box_6 = wx.ComboBox(self.window_2_pane_1, -1, choices=[], style=wx.CB_DROPDOWN)
        self.label_15 = wx.StaticText(self.window_2_pane_1, -1, "ending on")
        self.combo_box_5 = wx.ComboBox(self.window_2_pane_1, -1, choices=[], style=wx.CB_DROPDOWN)
        self.checkbox_8 = wx.CheckBox(self.window_2_pane_1, -1, "indefinite")
        self.button_6 = wx.Button(self.window_2_pane_1, -1, "add sessions")
        self.button_9 = wx.Button(self.window_2_pane_1, -1, "cancel sessions")
        self.label_5 = wx.StaticText(self.window_2_pane_1, -1, "script id")
        self.text_ctrl_1 = wx.TextCtrl(self.window_2_pane_1, -1, "")
        self.label_6 = wx.StaticText(self.window_2_pane_1, -1, "referral id")
        self.text_ctrl_2 = wx.TextCtrl(self.window_2_pane_1, -1, "")
        self.label_7 = wx.StaticText(self.window_2_pane_1, -1, "request id")
        self.text_ctrl_3 = wx.TextCtrl(self.window_2_pane_1, -1, "")
        self.label_8 = wx.StaticText(self.window_2_pane_1, -1, "registration id")
        self.text_ctrl_4 = wx.TextCtrl(self.window_2_pane_1, -1, "")
        self.label_9 = wx.StaticText(self.window_2_pane_1, -1, "insurance")
        self.combo_box_4 = wx.ComboBox(self.window_2_pane_1, -1, choices=[], style=wx.CB_DROPDOWN)
        self.label_10 = wx.StaticText(self.window_2_pane_1, -1, "insurance no")
        self.text_ctrl_5 = wx.TextCtrl(self.window_2_pane_1, -1, "")
        self.button_10 = wx.Button(self.window_2_pane_1, -1, "identity details")
        self.button_15 = wx.Button(self.window_2_pane_1, -1, "db user detail")
        self.button_2 = wx.Button(self.window_2_pane_1, -1, "update")
        self.button_5 = wx.Button(self.window_2_pane_1, -1, "cancel changes")
        self.button_3 = wx.Button(self.window_2_pane_2, -1, "<<")
        self.combo_box_1 = wx.ComboBox(self.window_2_pane_2, -1, choices=[], style=wx.CB_DROPDOWN)
        self.label_2 = wx.StaticText(self.window_2_pane_2, -1, "week n")
        self.button_4 = wx.Button(self.window_2_pane_2, -1, ">>")
        self.grid_1 = wx.grid.Grid(self.window_2_pane_2, -1, size=(1, 1))
        self.label_1 = wx.StaticText(self.window_2_pane_2, -1, "Sessions")
        self.radio_box_1 = wx.RadioBox(self.window_2_pane_2, -1, "radio_box_1", choices=["view regular sessions", "view sessions for week"], majorDimension=0, style=wx.RA_SPECIFY_ROWS)
        self.list_box_2 = wx.ListBox(self.window_2_pane_2, -1, choices=[])
        self.label_3 = wx.StaticText(self.window_2_pane_2, -1, "from")
        self.combo_box_3 = wx.ComboBox(self.window_2_pane_2, -1, choices=[], style=wx.CB_DROPDOWN)
        self.label_4 = wx.StaticText(self.window_2_pane_2, -1, "to")
        self.combo_box_2 = wx.ComboBox(self.window_2_pane_2, -1, choices=[], style=wx.CB_DROPDOWN)
        self.button_1 = wx.Button(self.window_2_pane_2, -1, "add holiday")
        self.list_ctrl_1 = wx.ListCtrl(self.notebook_1_pane_3, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.button_7 = wx.Button(self.notebook_1_pane_3, -1, "add")
        self.button_8 = wx.Button(self.notebook_1_pane_3, -1, "properties")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.use_selected_provider, self.button_11)
        self.Bind(wx.EVT_BUTTON, self.new_provider, self.button_12)
        self.Bind(wx.EVT_LISTBOX_DCLICK, self.use_selected_provider, self.list_box_1)
        self.Bind(wx.EVT_BUTTON, self.add_session, self.button_6)
        self.Bind(wx.EVT_BUTTON, self.cancel_sessions, self.button_9)
        self.Bind(wx.EVT_BUTTON, self.edit_details, self.button_10)
        self.Bind(wx.EVT_BUTTON, self.update_provider, self.button_2)
        self.Bind(wx.EVT_BUTTON, self.cancel_provider_detail_change, self.button_5)
        self.Bind(wx.EVT_BUTTON, self.prev_week, self.button_3)
        self.Bind(wx.EVT_COMBOBOX, self.combo_week, self.combo_box_1)
        self.Bind(wx.EVT_BUTTON, self.next_week, self.button_4)
        self.Bind(wx.grid.EVT_GRID_CMD_CELL_CHANGE, self.session_cell_changed, self.grid_1)
        self.Bind(wx.grid.EVT_GRID_CMD_SELECT_CELL, self.session_cell_selected, self.grid_1)
        self.Bind(wx.EVT_RADIOBOX, self.radio_sessions, self.radio_box_1)
        self.Bind(wx.EVT_BUTTON, self.add_holiday, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.add_user, self.button_7)
        self.Bind(wx.EVT_BUTTON, self.user_properties, self.button_8)
        self.Bind(wx.EVT_NOTEBOOK_PAGE_CHANGED, self.appt_notebook_changed, self.notebook_1)
        # end wxGlade
	
	gmDispatcher.connect(signal= gmSignals.pg_users_changed(), receiver = self.populate_list )
	

    def __set_properties(self):
        # begin wxGlade: cAU_AppointV01.__set_properties
        self.combo_box_9.SetSelection(-1)
        self.grid_2.CreateGrid(10, 3)
        self.button_11.SetDefault()
        self.combo_box_6.SetSelection(-1)
        self.combo_box_5.SetSelection(-1)
        self.combo_box_4.SetSelection(-1)
        self.combo_box_1.SetFocus()
        self.combo_box_1.SetSelection(-1)
        self.grid_1.CreateGrid(10, 7)
        self.grid_1.SetColLabelValue(0, "Mon")
        self.grid_1.SetColLabelValue(1, "Tue")
        self.grid_1.SetColLabelValue(2, "Wed")
        self.grid_1.SetColLabelValue(3, "Thur")
        self.grid_1.SetColLabelValue(4, "Fri")
        self.grid_1.SetColLabelValue(5, "Sat")
        self.grid_1.SetColLabelValue(6, "Sun")
        self.radio_box_1.SetSelection(0)
        self.combo_box_3.SetSelection(-1)
        self.combo_box_2.SetSelection(-1)
        self.notebook_1.SetFocus()
        # end wxGlade

	self.populate_list()

    def __do_layout(self):
        # begin wxGlade: cAU_AppointV01.__do_layout
        sizer_1 = wx.StaticBoxSizer(self.sizer_1_staticbox, wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.FlexGridSizer(3, 2, 0, 0)
        sizer_9 = wx.StaticBoxSizer(self.sizer_9_staticbox, wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_2 = wx.FlexGridSizer(4, 4, 0, 0)
        sizer_13 = wx.StaticBoxSizer(self.sizer_13_staticbox, wx.HORIZONTAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_15 = wx.BoxSizer(wx.VERTICAL)
        sizer_19 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_17 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18 = wx.BoxSizer(wx.VERTICAL)
        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_3 = wx.GridSizer(2, 2, 0, 0)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_21 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_20 = wx.StaticBoxSizer(self.sizer_20_staticbox, wx.HORIZONTAL)
        sizer_27 = wx.BoxSizer(wx.VERTICAL)
        sizer_28 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_28.Add(self.button_13, 0, wx.ADJUST_MINSIZE, 0)
        sizer_28.Add(self.combo_box_9, 0, wx.ADJUST_MINSIZE, 0)
        sizer_28.Add(self.button_14, 0, wx.ADJUST_MINSIZE, 0)
        sizer_27.Add(sizer_28, 1, wx.EXPAND, 0)
        sizer_27.Add(self.grid_2, 10, wx.EXPAND, 0)
        sizer_27.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        self.notebook_2_pane_1.SetAutoLayout(True)
        self.notebook_2_pane_1.SetSizer(sizer_27)
        sizer_27.Fit(self.notebook_2_pane_1)
        sizer_27.SetSizeHints(self.notebook_2_pane_1)
        self.notebook_2.AddPage(self.notebook_2_pane_1, "tab1")
        sizer_20.Add(self.notebook_2, 1, wx.EXPAND, 0)
        self.notebook_1_pane_1.SetAutoLayout(True)
        self.notebook_1_pane_1.SetSizer(sizer_20)
        sizer_20.Fit(self.notebook_1_pane_1)
        sizer_20.SetSizeHints(self.notebook_1_pane_1)
        sizer_21.Add(self.button_11, 0, wx.ADJUST_MINSIZE, 0)
        sizer_21.Add(self.button_12, 0, wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(sizer_21, 0, wx.EXPAND, 0)
        sizer_3.Add(self.list_box_1, 1, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        self.window_1_pane_1.SetAutoLayout(True)
        self.window_1_pane_1.SetSizer(sizer_3)
        sizer_3.Fit(self.window_1_pane_1)
        sizer_3.SetSizeHints(self.window_1_pane_1)
        grid_sizer_3.Add(self.label_12, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_3.Add(self.text_ctrl_7, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_3.Add(self.label_13, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_3.Add(self.text_ctrl_8, 0, wx.ADJUST_MINSIZE, 0)
        sizer_15.Add(grid_sizer_3, 1, wx.EXPAND, 0)
        sizer_16.Add(self.checkbox_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_16.Add(self.checkbox_2, 0, wx.ADJUST_MINSIZE, 0)
        sizer_16.Add(self.checkbox_3, 0, wx.ADJUST_MINSIZE, 0)
        sizer_16.Add(self.checkbox_4, 0, wx.ADJUST_MINSIZE, 0)
        sizer_16.Add(self.checkbox_5, 0, wx.ADJUST_MINSIZE, 0)
        sizer_16.Add(self.checkbox_6, 0, wx.ADJUST_MINSIZE, 0)
        sizer_16.Add(self.checkbox_7, 0, wx.ADJUST_MINSIZE, 0)
        sizer_15.Add(sizer_16, 1, wx.EXPAND, 0)
        sizer_17.Add(self.label_14, 0, wx.ADJUST_MINSIZE, 0)
        sizer_17.Add(self.combo_box_6, 0, wx.ADJUST_MINSIZE, 0)
        sizer_17.Add(self.label_15, 0, wx.ADJUST_MINSIZE, 0)
        sizer_18.Add(self.combo_box_5, 0, wx.ADJUST_MINSIZE, 0)
        sizer_18.Add(self.checkbox_8, 0, wx.ADJUST_MINSIZE, 0)
        sizer_17.Add(sizer_18, 1, wx.EXPAND, 0)
        sizer_15.Add(sizer_17, 1, wx.EXPAND, 0)
        sizer_19.Add(self.button_6, 0, wx.ADJUST_MINSIZE, 0)
        sizer_19.Add(self.button_9, 0, wx.ADJUST_MINSIZE, 0)
        sizer_15.Add(sizer_19, 1, wx.EXPAND, 0)
        sizer_14.Add(sizer_15, 1, wx.EXPAND, 0)
        sizer_13.Add(sizer_14, 1, wx.EXPAND, 0)
        sizer_10.Add(sizer_13, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_5, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_2.Add(self.text_ctrl_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_2.Add(self.label_6, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_2.Add(self.text_ctrl_2, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_2.Add(self.label_7, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_2.Add(self.text_ctrl_3, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_2.Add(self.label_8, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_2.Add(self.text_ctrl_4, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_2.Add(self.label_9, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_2.Add(self.combo_box_4, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_2.Add(self.label_10, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_2.Add(self.text_ctrl_5, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_2.Add(self.button_10, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_2.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_2.Add(self.button_15, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_2.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_2.Add(self.button_2, 0, wx.ALL|wx.ADJUST_MINSIZE, 3)
        grid_sizer_2.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_2.Add(self.button_5, 0, wx.ALL|wx.ADJUST_MINSIZE, 5)
        grid_sizer_2.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        sizer_10.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        self.window_2_pane_1.SetAutoLayout(True)
        self.window_2_pane_1.SetSizer(sizer_10)
        sizer_10.Fit(self.window_2_pane_1)
        sizer_10.SetSizeHints(self.window_2_pane_1)
        sizer_7.Add(self.button_3, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7.Add(self.combo_box_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7.Add(self.label_2, 0, wx.ADJUST_MINSIZE, 0)
        sizer_7.Add(self.button_4, 0, wx.ADJUST_MINSIZE, 0)
        sizer_5.Add(sizer_7, 0, wx.EXPAND, 0)
        sizer_5.Add(self.grid_1, 2, wx.EXPAND, 0)
        sizer_6.Add(self.label_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_6.Add(self.radio_box_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_9.Add(self.list_box_2, 0, wx.ADJUST_MINSIZE, 0)
        sizer_8.Add(sizer_9, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_3, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.combo_box_3, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_4, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.combo_box_2, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add((20, 20), 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.button_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_8.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_6.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_5.Add(sizer_6, 0, wx.EXPAND, 0)
        self.window_2_pane_2.SetAutoLayout(True)
        self.window_2_pane_2.SetSizer(sizer_5)
        sizer_5.Fit(self.window_2_pane_2)
        sizer_5.SetSizeHints(self.window_2_pane_2)
        self.window_2.SplitHorizontally(self.window_2_pane_1, self.window_2_pane_2)
        sizer_4.Add(self.window_2, 2, wx.EXPAND, 0)
        self.window_1_pane_2.SetAutoLayout(True)
        self.window_1_pane_2.SetSizer(sizer_4)
        sizer_4.Fit(self.window_1_pane_2)
        sizer_4.SetSizeHints(self.window_1_pane_2)
        self.window_1.SplitVertically(self.window_1_pane_1, self.window_1_pane_2)
        sizer_2.Add(self.window_1, 1, wx.EXPAND, 0)
        self.notebook_1_pane_2.SetAutoLayout(True)
        self.notebook_1_pane_2.SetSizer(sizer_2)
        sizer_2.Fit(self.notebook_1_pane_2)
        sizer_2.SetSizeHints(self.notebook_1_pane_2)
        sizer_11.Add(self.list_ctrl_1, 1, wx.EXPAND, 0)
        sizer_12.Add(self.button_7, 0, wx.ADJUST_MINSIZE, 0)
        sizer_12.Add(self.button_8, 0, wx.ADJUST_MINSIZE, 0)
        sizer_11.Add(sizer_12, 1, wx.EXPAND, 0)
        self.notebook_1_pane_3.SetAutoLayout(True)
        self.notebook_1_pane_3.SetSizer(sizer_11)
        sizer_11.Fit(self.notebook_1_pane_3)
        sizer_11.SetSizeHints(self.notebook_1_pane_3)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Appointments")
        self.notebook_1.AddPage(self.notebook_1_pane_2, "Providers")
        self.notebook_1.AddPage(self.notebook_1_pane_3, "users")
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        # end wxGlade



    def add_session(self, event): # wxGlade: cAU_AppointV01Panel.<event_handler>
        print "Event handler `add_session' not implemented!"
        event.Skip()

    def cancel_sessions(self, event): # wxGlade: cAU_AppointV01Panel.<event_handler>
        print "Event handler `cancel_sessions' not implemented!"
        event.Skip()

    def edit_details(self, event): # wxGlade: cAU_AppointV01Panel.<event_handler>
        print "Event handler `edit_details' not implemented!"
        event.Skip()

    def update_provider(self, event): # wxGlade: cAU_AppointV01Panel.<event_handler>
        print "Event handler `update_provider' not implemented!"
        event.Skip()

    def cancel_provider_detail_change(self, event): # wxGlade: cAU_AppointV01Panel.<event_handler>
        print "Event handler `cancel_provider_detail_change' not implemented!"
        event.Skip()

    def prev_week(self, event): # wxGlade: cAU_AppointV01Panel.<event_handler>
        print "Event handler `prev_week' not implemented!"
        event.Skip()

    def combo_week(self, event): # wxGlade: cAU_AppointV01Panel.<event_handler>
        print "Event handler `combo_week' not implemented!"
        event.Skip()

    def next_week(self, event): # wxGlade: cAU_AppointV01Panel.<event_handler>
        print "Event handler `next_week' not implemented!"
        event.Skip()

    def session_cell_changed(self, event): # wxGlade: cAU_AppointV01Panel.<event_handler>
        print "Event handler `session_cell_changed' not implemented!"
        event.Skip()

    def session_cell_selected(self, event): # wxGlade: cAU_AppointV01Panel.<event_handler>
        print "Event handler `session_cell_selected' not implemented!"
        event.Skip()

    def radio_sessions(self, event): # wxGlade: cAU_AppointV01Panel.<event_handler>
        print "Event handler `radio_sessions' not implemented!"
        event.Skip()

    def add_holiday(self, event): # wxGlade: cAU_AppointV01Panel.<event_handler>
        print "Event handler `add_holiday' not implemented!"
        event.Skip()

    def add_user(self, event): # wxGlade: cAU_AppointV01Panel.<event_handler>
        print "Event handler `add_user' not implemented!"
        event.Skip()
	dlg =  wx.Dialog(self, -1, _("Add DB User") )
	panel = cAU_DBUserSetup(dlg)

	if ( dlg.ShowModal() == wx.ID_OK ) :
		dlg.Destroy()

    def user_properties(self, event): # wxGlade: cAU_AppointV01Panel.<event_handler>
        print "Event handler `user_properties' not implemented!"
        event.Skip()
        
    def appt_notebook_changed(self, event): # wxGlade: cAU_AppointV01.<event_handler>
        print "Event handler `appt_notebook_changed' not implemented!"
        event.Skip()

    def use_selected_provider(self, event): # wxGlade: cAU_AppointV01.<event_handler>
        print "Event handler `use_selected_provider' not implemented"
        event.Skip()

    def new_provider(self, event): # wxGlade: cAU_AppointV01.<event_handler>
        #print "Event handler `new_provider' not implemented"
        event.Skip()

	#c = cNewPatientWizard( self, title = _('Register new provider'), subtitle = _('New Provider details') )
	#ident = c.RunWizard(activate = False)
	#print ident
	#import pdb
	#pdb.set_trace()
	
	dlg = wx.Dialog( self, -1, "Create Provider")
	
	c = cAU_ProviderFind(dlg )
	dlg.ShowModal()
	



    def use_selected_provider(self, event): # wxGlade: cAU_AppointV01.<event_handler>
        print "Event handler `use_selected_provider' not implemented"
        event.Skip()

    def add_session(self, event): # wxGlade: cAU_AppointV01.<event_handler>
        print "Event handler `add_session' not implemented"
        event.Skip()

    def cancel_sessions(self, event): # wxGlade: cAU_AppointV01.<event_handler>
        print "Event handler `cancel_sessions' not implemented"
        event.Skip()

    def edit_details(self, event): # wxGlade: cAU_AppointV01.<event_handler>
        print "Event handler `edit_details' not implemented"
        event.Skip()

    def update_provider(self, event): # wxGlade: cAU_AppointV01.<event_handler>
        print "Event handler `update_provider' not implemented"
        event.Skip()

    def cancel_provider_detail_change(self, event): # wxGlade: cAU_AppointV01.<event_handler>
        print "Event handler `cancel_provider_detail_change' not implemented"
        event.Skip()

    def prev_week(self, event): # wxGlade: cAU_AppointV01.<event_handler>
        print "Event handler `prev_week' not implemented"
        event.Skip()

    def combo_week(self, event): # wxGlade: cAU_AppointV01.<event_handler>
        print "Event handler `combo_week' not implemented"
        event.Skip()

    def next_week(self, event): # wxGlade: cAU_AppointV01.<event_handler>
        print "Event handler `next_week' not implemented"
        event.Skip()

    def session_cell_changed(self, event): # wxGlade: cAU_AppointV01.<event_handler>
        print "Event handler `session_cell_changed' not implemented"
        event.Skip()

    def session_cell_selected(self, event): # wxGlade: cAU_AppointV01.<event_handler>
        print "Event handler `session_cell_selected' not implemented"
        event.Skip()

    def radio_sessions(self, event): # wxGlade: cAU_AppointV01.<event_handler>
        print "Event handler `radio_sessions' not implemented"
        event.Skip()

    def add_holiday(self, event): # wxGlade: cAU_AppointV01.<event_handler>
        print "Event handler `add_holiday' not implemented"
        event.Skip()

    def add_user(self, event): # wxGlade: cAU_AppointV01.<event_handler>
        print "Event handler `add_user' not implemented"
        event.Skip()

    def user_properties(self, event): # wxGlade: cAU_AppointV01.<event_handler>
        print "Event handler `user_properties' not implemented"
        event.Skip()

# end of class cAU_AppointV01


    def populate_list(self):
    	populate_pg_user_list(self.list_ctrl_1)
	
def populate_pg_user_list( c, filter = "True"):
    	
	stmt = "select usename,groname from pg_user p , pg_group g where p.usesysid = any ( grolist) and "+filter+" order by usename"
	
	result= gmPG.run_ro_query('historica', stmt)
	#import pdb 
	#pdb.set_trace()
	user_grps = {}
	for x,y in result:
		if not user_grps.has_key(x):
			user_grps[x] = []

		user_grps[x].append(y)


	c.InsertColumn(0, _("pg user"))
	c.InsertColumn(1, _("group memberships"))


	c.DeleteAllItems()
	for (k,v), i  in zip( user_grps.items(), range(len(user_grps)) ):
		
		c.InsertStringItem(i, k) 
		c.SetStringItem(i, 1, ", ".join(v) )	

	for i in range(2):
		c.SetColumnWidth(i, wx.LIST_AUTOSIZE)
		
		
if __name__=="__main__":
	a = wx.App()
	f = wx.Frame(None, -1, "Test Appoint Frame")
	a.SetTopWindow(f)
	p = cAU_AppointV01(f, -1)
	f.Fit()
	f.Show(1)
	a.MainLoop()




