# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4cvs on Sun Dec 25 22:47:25 2005

import wx
from Gnumed.pycommon import gmDispatcher, gmSignals
from Gnumed.business import gmPerson
# begin wxGlade: dependencies
# end wxGlade

class cAU_DrugV01Panel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: cAU_DrugV01Panel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.window_1 = wx.SplitterWindow(self, -1, style=wx.SP_3DSASH|wx.SP_LIVE_UPDATE|wx.CLIP_CHILDREN)
        self.window_1_pane_2 = wx.Panel(self.window_1, -1)
        self.window_2 = wx.SplitterWindow(self.window_1_pane_2, -1, style=wx.SP_3DSASH|wx.SP_LIVE_UPDATE|wx.CLIP_CHILDREN)
        self.window_2_pane_2 = wx.Panel(self.window_2, -1)
        self.window_2_pane_1 = wx.Panel(self.window_2, -1)
        self.sizer_17_staticbox = wx.StaticBox(self.window_2_pane_2, -1, "protocol")
        self.window_1_pane_1 = wx.Panel(self.window_1, -1)
        self.text_ctrl_8_summ_med = wx.TextCtrl(self.window_1_pane_1, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.TE_RICH)
        self.list_ctrl_7_allergy = wx.ListCtrl(self.window_2_pane_1, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.list_ctrl_8_meds = wx.ListCtrl(self.window_2_pane_1, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.label_14 = wx.StaticText(self.window_2_pane_2, -1, "drug")
        self.combo_box_8_drug = wx.ComboBox(self.window_2_pane_2, -1, choices=[], style=wx.CB_DROPDOWN)
        self.label_15 = wx.StaticText(self.window_2_pane_2, -1, "narrative")
        self.text_ctrl_4_narrative = wx.TextCtrl(self.window_2_pane_2, -1, "")
        self.label_16 = wx.StaticText(self.window_2_pane_2, -1, "date")
        self.text_ctrl_5_date = wx.TextCtrl(self.window_2_pane_2, -1, "")
        self.checkbox_1_is_reaction = wx.CheckBox(self.window_2_pane_2, -1, "is reaction")
        self.checkbox_2_is_sensitivity = wx.CheckBox(self.window_2_pane_2, -1, "is sensitivity")
        self.checkbox_3_is_definite = wx.CheckBox(self.window_2_pane_2, -1, "definite")
        self.checkbox_4_is_severe = wx.CheckBox(self.window_2_pane_2, -1, "severe")
        self.button_3_save_allergy = wx.Button(self.window_2_pane_2, -1, "save as allergy")
        self.checkbox_8_free_text = wx.CheckBox(self.window_2_pane_2, -1, "free text prescribe")
        self.text_ctrl_6_free = wx.TextCtrl(self.window_2_pane_2, -1, "")
        self.label_18 = wx.StaticText(self.window_2_pane_2, -1, "strength")
        self.combo_box_9_strength = wx.ComboBox(self.window_2_pane_2, -1, choices=[], style=wx.CB_DROPDOWN)
        self.label_19 = wx.StaticText(self.window_2_pane_2, -1, "dose")
        self.combo_box_10_dose = wx.ComboBox(self.window_2_pane_2, -1, choices=[], style=wx.CB_DROPDOWN)
        self.label_20 = wx.StaticText(self.window_2_pane_2, -1, "route")
        self.combo_box_11_route = wx.ComboBox(self.window_2_pane_2, -1, choices=[], style=wx.CB_DROPDOWN)
        self.label_21 = wx.StaticText(self.window_2_pane_2, -1, "freq")
        self.combo_box_12_freq = wx.ComboBox(self.window_2_pane_2, -1, choices=[], style=wx.CB_DROPDOWN)
        self.label_22 = wx.StaticText(self.window_2_pane_2, -1, "duration")
        self.combo_box_13_duration = wx.ComboBox(self.window_2_pane_2, -1, choices=[], style=wx.CB_DROPDOWN)
        self.label_29 = wx.StaticText(self.window_2_pane_2, -1, "max duration")
        self.combo_box_19_max_duration = wx.ComboBox(self.window_2_pane_2, -1, choices=[], style=wx.CB_DROPDOWN)
        self.label_23 = wx.StaticText(self.window_2_pane_2, -1, "condition")
        self.combo_box_14_main_condition = wx.ComboBox(self.window_2_pane_2, -1, choices=[], style=wx.CB_DROPDOWN)
        self.button_4_prescribe = wx.Button(self.window_2_pane_2, -1, "prescribe")
        self.checkbox_7_use_paed = wx.CheckBox(self.window_2_pane_2, -1, "use paed calc  ")
        self.label_30 = wx.StaticText(self.window_2_pane_2, -1, "weight")
        self.text_ctrl_7_weight = wx.TextCtrl(self.window_2_pane_2, -1, "")
        self.label_27 = wx.StaticText(self.window_2_pane_2, -1, "dose/wt")
        self.combo_box_17_dosebyweight = wx.ComboBox(self.window_2_pane_2, -1, choices=[], style=wx.CB_DROPDOWN)
        self.label_5 = wx.StaticText(self.window_2_pane_2, -1, "  std freq")
        self.combo_box_18_std_freq = wx.ComboBox(self.window_2_pane_2, -1, choices=[], style=wx.CB_DROPDOWN)
        self.button_6_add_to_protocol = wx.Button(self.window_2_pane_2, -1, "add to protocol")
        self.button_7_add_protocol = wx.Button(self.window_2_pane_2, -1, "add protocol")
        self.button_8_prescribe_protocol = wx.Button(self.window_2_pane_2, -1, "prescribe protocol")
        self.list_ctrl_5 = wx.ListCtrl(self.window_2_pane_2, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.list_box_1 = wx.ListBox(self.window_2_pane_2, -1, choices=[])

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LIST_DELETE_ITEM, self.delete_allergy, self.list_ctrl_7_allergy)
        self.Bind(wx.EVT_LIST_ITEM_ACTIVATED, self.edit_allergy, self.list_ctrl_7_allergy)
        self.Bind(wx.EVT_LIST_DELETE_ITEM, self.delete_med, self.list_ctrl_8_meds)
        self.Bind(wx.EVT_LIST_ITEM_ACTIVATED, self.edit_med, self.list_ctrl_8_meds)
        self.Bind(wx.EVT_LIST_ITEM_RIGHT_CLICK, self.menu_med, self.list_ctrl_8_meds)
        self.Bind(wx.EVT_COMBOBOX, self.find_drug_evt, self.combo_box_8_drug)
        self.Bind(wx.EVT_TEXT_ENTER, self.find_date_evt, self.text_ctrl_5_date)
        self.Bind(wx.EVT_CHECKBOX, self.is_reaction, self.checkbox_1_is_reaction)
        self.Bind(wx.EVT_BUTTON, self.save_allergy, self.button_3_save_allergy)
        self.Bind(wx.EVT_CHECKBOX, self.is_free_text, self.checkbox_8_free_text)
        self.Bind(wx.EVT_COMBOBOX, self.load_strength, self.combo_box_9_strength)
        self.Bind(wx.EVT_COMBOBOX, self.load_route, self.combo_box_11_route)
        self.Bind(wx.EVT_COMBOBOX, self.load_freq, self.combo_box_12_freq)
        self.Bind(wx.EVT_COMBOBOX, self.load_conditions, self.combo_box_14_main_condition)
        self.Bind(wx.EVT_BUTTON, self.prescribe, self.button_4_prescribe)
        self.Bind(wx.EVT_CHECKBOX, self.use_paed, self.checkbox_7_use_paed)
        self.Bind(wx.EVT_COMBOBOX, self.load_standard_freq, self.combo_box_18_std_freq)
        self.Bind(wx.EVT_BUTTON, self.add_to_protocol, self.button_6_add_to_protocol)
        self.Bind(wx.EVT_BUTTON, self.add_protocol, self.button_7_add_protocol)
        self.Bind(wx.EVT_BUTTON, self.prescribe_protocol, self.button_8_prescribe_protocol)
        self.Bind(wx.EVT_LIST_DELETE_ITEM, self.delete_protocol_item, self.list_ctrl_5)
        self.Bind(wx.EVT_LIST_ITEM_ACTIVATED, self.load_protocol_item, self.list_ctrl_5)
        self.Bind(wx.EVT_LIST_ITEM_RIGHT_CLICK, self.menu_protocol_items, self.list_ctrl_5)
        self.Bind(wx.EVT_LISTBOX, self.select_protocol, self.list_box_1)
        self.Bind(wx.EVT_SPLITTER_SASH_POS_CHANGING, self.window_2_changing, self.window_2)
        self.Bind(wx.EVT_SPLITTER_SASH_POS_CHANGING, self.window_1_changing, self.window_1)
        # end wxGlade

	# gnumed events
	gmDispatcher.connect(signal=gmSignals.post_patient_selection(), receiver=self._on_post_patient_selection)


    def __set_properties(self):
        # begin wxGlade: cAU_DrugV01Panel.__set_properties
        self.SetFocus()
        self.combo_box_8_drug.SetSelection(-1)
        self.checkbox_2_is_sensitivity.Enable(False)
        self.checkbox_3_is_definite.Enable(False)
        self.checkbox_4_is_severe.Enable(False)
        self.button_3_save_allergy.Enable(False)
        self.text_ctrl_6_free.Enable(False)
        self.combo_box_9_strength.Enable(False)
        self.combo_box_9_strength.SetSelection(-1)
        self.combo_box_10_dose.Enable(False)
        self.combo_box_10_dose.SetSelection(-1)
        self.combo_box_11_route.Enable(False)
        self.combo_box_11_route.SetSelection(-1)
        self.combo_box_12_freq.Enable(False)
        self.combo_box_12_freq.SetSelection(-1)
        self.combo_box_13_duration.SetSelection(-1)
        self.combo_box_19_max_duration.SetSelection(-1)
        self.combo_box_14_main_condition.SetSelection(-1)
        self.text_ctrl_7_weight.Enable(False)
        self.combo_box_17_dosebyweight.Enable(False)
        self.combo_box_17_dosebyweight.SetSelection(-1)
        self.combo_box_18_std_freq.Enable(False)
        self.combo_box_18_std_freq.SetSelection(-1)
        self.button_6_add_to_protocol.Enable(False)
        self.button_7_add_protocol.Enable(False)
        self.button_8_prescribe_protocol.Enable(False)
        # end wxGlade
    
    def set_input_enable( self, is_allergy = False, is_free = False, is_paed = False):
	self.label_18.Enable( not is_allergy)
	self.label_19.Enable( not is_allergy and not is_free and not is_paed)
	self.label_20.Enable( not is_allergy and not is_free and not is_paed)
	self.label_21.Enable( not is_allergy and not is_free and not is_paed)
	self.label_22.Enable( not is_allergy and not is_free)
	self.label_29.Enable( not is_allergy and not is_free)
	self.label_23.Enable( not is_allergy )
	self.label_30.Enable( not is_allergy )
	self.label_27.Enable( not is_allergy and not is_free and is_paed)
	self.label_28.Enable( not is_allergy and not is_free and is_paed)
	self.label_5.Enable( not is_allergy  and not is_free and is_paed)
	self.checkbox_1_is_reaction.Enable(not is_free and not is_paed)
	self.checkbox_2_is_sensitivity.Enable(is_allergy) 
        self.checkbox_3_is_definite.Enable(is_allergy)
        self.checkbox_4_is_severe.Enable(is_allergy)
        self.button_3_save_allergy.Enable(is_allergy)
	self.checkbox_8_free_text.Enable( not is_allergy and not is_paed)
	
        self.text_ctrl_6_free.Enable(not is_allergy and is_free and not is_paed)
        self.combo_box_9_strength.Enable(not is_allergy  )
        self.combo_box_10_dose.Enable(not is_allergy and not is_free and not is_paed)
        
        self.combo_box_11_route.Enable(not is_allergy and not is_free)
        
        self.combo_box_12_freq.Enable(not is_allergy and not is_free and not is_paed)
        self.combo_box_13_duration.Enable(not is_allergy and not is_free )
        self.combo_box_19_max_duration.Enable(not is_allergy and not is_free) 
        self.combo_box_14_main_condition.Enable(not is_allergy)
	self.checkbox_7_use_paed.Enable(not is_allergy)
        self.text_ctrl_7_weight.Enable(not is_allergy and not is_free)
        self.combo_box_17_dosebyweight.Enable(not is_allergy and is_paed)
        self.button_4_prescribe.Enable( not is_allergy)
        self.combo_box_18_std_freq.Enable(not is_allergy and is_paed)
        
        self.button_6_add_to_protocol.Enable(not is_allergy)
        self.button_7_add_protocol.Enable(not is_allergy)
        self.button_8_prescribe_protocol.Enable(not is_allergy)


    def __do_layout(self):
        # begin wxGlade: cAU_DrugV01Panel.__do_layout
        sizer_24 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_26 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_17 = wx.StaticBoxSizer(self.sizer_17_staticbox, wx.HORIZONTAL)
        sizer_21 = wx.BoxSizer(wx.VERTICAL)
        sizer_22 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_20 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_27 = wx.BoxSizer(wx.VERTICAL)
        sizer_25 = wx.BoxSizer(wx.VERTICAL)
        sizer_25.Add(self.text_ctrl_8_summ_med, 1, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        self.window_1_pane_1.SetAutoLayout(True)
        self.window_1_pane_1.SetSizer(sizer_25)
        sizer_25.Fit(self.window_1_pane_1)
        sizer_25.SetSizeHints(self.window_1_pane_1)
        sizer_27.Add(self.list_ctrl_7_allergy, 2, wx.EXPAND, 0)
        sizer_27.Add(self.list_ctrl_8_meds, 3, wx.EXPAND, 0)
        self.window_2_pane_1.SetAutoLayout(True)
        self.window_2_pane_1.SetSizer(sizer_27)
        sizer_27.Fit(self.window_2_pane_1)
        sizer_27.SetSizeHints(self.window_2_pane_1)
        sizer_11.Add(self.label_14, 0, wx.ADJUST_MINSIZE, 0)
        sizer_11.Add(self.combo_box_8_drug, 3, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        sizer_8.Add(sizer_11, 0, wx.EXPAND, 0)
        sizer_9.Add(self.label_15, 0, wx.ADJUST_MINSIZE, 0)
        sizer_9.Add(self.text_ctrl_4_narrative, 2, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        sizer_9.Add(self.label_16, 0, wx.ADJUST_MINSIZE, 0)
        sizer_9.Add(self.text_ctrl_5_date, 0, wx.ADJUST_MINSIZE, 0)
        sizer_8.Add(sizer_9, 0, wx.EXPAND, 0)
        sizer_10.Add(self.checkbox_1_is_reaction, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10.Add(self.checkbox_2_is_sensitivity, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10.Add(self.checkbox_3_is_definite, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10.Add(self.checkbox_4_is_severe, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10.Add(self.button_3_save_allergy, 0, wx.ADJUST_MINSIZE, 0)
        sizer_10.Add((70, 20), 1, wx.ADJUST_MINSIZE, 0)
        sizer_8.Add(sizer_10, 0, wx.EXPAND, 0)
        sizer_12.Add(self.checkbox_8_free_text, 0, wx.ADJUST_MINSIZE, 0)
        sizer_12.Add(self.text_ctrl_6_free, 3, wx.ADJUST_MINSIZE, 0)
        sizer_8.Add(sizer_12, 0, wx.EXPAND, 0)
        sizer_13.Add(self.label_18, 0, wx.ADJUST_MINSIZE, 0)
        sizer_13.Add(self.combo_box_9_strength, 0, wx.ADJUST_MINSIZE, 0)
        sizer_13.Add(self.label_19, 0, wx.ADJUST_MINSIZE, 0)
        sizer_13.Add(self.combo_box_10_dose, 0, wx.ADJUST_MINSIZE, 0)
        sizer_13.Add(self.label_20, 0, wx.ADJUST_MINSIZE, 0)
        sizer_13.Add(self.combo_box_11_route, 0, wx.ADJUST_MINSIZE, 0)
        sizer_13.Add(self.label_21, 0, wx.ADJUST_MINSIZE, 0)
        sizer_13.Add(self.combo_box_12_freq, 0, wx.ADJUST_MINSIZE, 0)
        sizer_8.Add(sizer_13, 0, wx.EXPAND, 0)
        sizer_14.Add(self.label_22, 0, wx.ADJUST_MINSIZE, 0)
        sizer_14.Add(self.combo_box_13_duration, 0, wx.ADJUST_MINSIZE, 0)
        sizer_14.Add(self.label_29, 0, wx.ADJUST_MINSIZE, 0)
        sizer_14.Add(self.combo_box_19_max_duration, 0, wx.ADJUST_MINSIZE, 0)
        sizer_14.Add(self.label_23, 0, wx.ADJUST_MINSIZE, 0)
        sizer_14.Add(self.combo_box_14_main_condition, 1, wx.ADJUST_MINSIZE, 0)
        sizer_14.Add(self.button_4_prescribe, 0, wx.ADJUST_MINSIZE, 0)
        sizer_15.Add(sizer_14, 1, wx.EXPAND, 0)
        sizer_8.Add(sizer_15, 1, wx.EXPAND, 0)
        sizer_20.Add(self.checkbox_7_use_paed, 0, wx.ALL|wx.ADJUST_MINSIZE, 0)
        sizer_20.Add(self.label_30, 0, wx.ADJUST_MINSIZE, 0)
        sizer_20.Add(self.text_ctrl_7_weight, 0, wx.ADJUST_MINSIZE, 0)
        sizer_20.Add(self.label_27, 0, wx.ADJUST_MINSIZE, 0)
        sizer_20.Add(self.combo_box_17_dosebyweight, 0, wx.ADJUST_MINSIZE, 0)
        self.label_28 = wx.StaticText(self.window_2_pane_2, -1, "mg/kg")
        sizer_20.Add(self.label_28, 0, wx.ADJUST_MINSIZE, 0)
        sizer_20.Add(self.label_5, 0, wx.ADJUST_MINSIZE, 0)
        sizer_20.Add(self.combo_box_18_std_freq, 0, wx.ADJUST_MINSIZE, 0)
        sizer_8.Add(sizer_20, 1, wx.EXPAND, 0)
        sizer_7.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_21.Add(self.button_6_add_to_protocol, 0, wx.ADJUST_MINSIZE, 0)
        sizer_22.Add(self.button_7_add_protocol, 0, wx.ADJUST_MINSIZE, 0)
        sizer_22.Add(self.button_8_prescribe_protocol, 0, wx.ADJUST_MINSIZE, 0)
        sizer_21.Add(sizer_22, 0, wx.EXPAND, 0)
        sizer_21.Add(self.list_ctrl_5, 1, wx.EXPAND, 0)
        sizer_16.Add(sizer_21, 1, wx.EXPAND, 0)
        sizer_17.Add(self.list_box_1, 1, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        sizer_16.Add(sizer_17, 1, wx.EXPAND, 0)
        sizer_7.Add(sizer_16, 1, wx.EXPAND, 0)
        self.window_2_pane_2.SetAutoLayout(True)
        self.window_2_pane_2.SetSizer(sizer_7)
        sizer_7.Fit(self.window_2_pane_2)
        sizer_7.SetSizeHints(self.window_2_pane_2)
        self.window_2.SplitHorizontally(self.window_2_pane_1, self.window_2_pane_2)
        sizer_26.Add(self.window_2, 1, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        self.window_1_pane_2.SetAutoLayout(True)
        self.window_1_pane_2.SetSizer(sizer_26)
        sizer_26.Fit(self.window_1_pane_2)
        sizer_26.SetSizeHints(self.window_1_pane_2)
        self.window_1.SplitVertically(self.window_1_pane_1, self.window_1_pane_2)
        sizer_24.Add(self.window_1, 1, wx.EXPAND, 1)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_24)
        sizer_24.Fit(self)
        sizer_24.SetSizeHints(self)
        # end wxGlade

    def delete_allergy(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `delete_allergy' not implemented!"
        event.Skip()

    def edit_allergy(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `edit_allergy' not implemented!"
        event.Skip()

    def delete_med(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `delete_med' not implemented!"
        event.Skip()

    def edit_med(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `edit_med' not implemented!"
        event.Skip()

    def menu_med(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `menu_med' not implemented!"
        event.Skip()

    def find_drug_evt(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `find_drug_evt' not implemented!"
        event.Skip()

    def find_date_evt(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `find_date_evt' not implemented!"
        event.Skip()

    def is_reaction(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        #print "Event handler `is_reaction' not implemented!"
        self.set_input_enable( is_allergy = event.IsChecked() )
	event.Skip()

    def save_allergy(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `save_allergy' not implemented!"
        event.Skip()

    def is_free_text(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `is_free_text' not implemented!"
	self.set_input_enable( is_free = event.IsChecked() )
        event.Skip()

    def load_strength(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `load_strength' not implemented!"
        event.Skip()

    def load_route(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `load_route' not implemented!"
        event.Skip()

    def load_freq(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `load_freq' not implemented!"
        event.Skip()

    def load_conditions(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `load_conditions' not implemented!"
        event.Skip()

    def prescribe(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `prescribe' not implemented!"
        event.Skip()

    def use_paed(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        #print "Event handler `use_paed' not implemented!"
	self.set_input_enable( is_paed = event.IsChecked() )
        event.Skip()

    def load_standard_freq(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `load_standard_freq' not implemented!"
        event.Skip()

    def add_to_protocol(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `add_to_protocol' not implemented!"
	
        event.Skip()

    def add_protocol(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `add_protocol' not implemented!"
        event.Skip()

    def prescribe_protocol(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `prescribe_protocol' not implemented!"
        event.Skip()

    def delete_protocol_item(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `delete_protocol_item' not implemented!"
        event.Skip()

    def load_protocol_item(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `load_protocol_item' not implemented!"
        event.Skip()

    def menu_protocol_items(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `menu_protocol_items' not implemented!"
        event.Skip()

    def select_protocol(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `select_protocol' not implemented!"
        event.Skip()

    def window_2_changing(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `window_2_changing' not implemented!"
        event.Skip()

    def window_1_changing(self, event): # wxGlade: cAU_DrugV01Panel.<event_handler>
        print "Event handler `window_1_changing' not implemented!"
        event.Skip()


    def _on_post_patient_selection(self):
    	print self, "got on patient selected"
	p = gmPerson.gmCurrentPatient()	
	emr = p.get_emr()
	vv = emr.get_vaccinations()
    	print vv


# end of class cAU_DrugV01Panel


