#!/bin/bash

# .wxg contains:
#WXGs=$(grep -L 'generated by wxGlade 0\.8' *.wxg)
#WXGs=$(grep -L 'indent_symbol="tab"' *.wxg)
#WXGs=$(grep -L 'indent_amount="1"' *.wxg)
#WXGs=$(grep -L 'overwrite="1"' *.wxg)
#WXGs=$(grep -L -i 'encoding="UTF-8"' *.wxg)
#WXGs=$(grep -L -i 'path="\.\./wxGladeWidgets/.*\.py"' *.wxg)
#WXGs=$(grep -L -i 'path="\.\./wxGladeWidgets/wxg.*\.py"' *.wxg)
#WXGs=$(grep -L 'use_gettext="1"' *.wxg)
#WXGs=$(grep -L 'use_new_namespace="1"' *.wxg)
# for wxp4-only:
#WXGs=$(grep -L 'for_version="3\.0"' *.wxg)
WXGs=$(grep 'wxSYS' *.wxg)

echo $WXGs
exit 0

echo "#!/bin/bash"
echo ""
echo "export PYTHONPATH="/usr/lib/python2.7/dist-packages/wxp4/:${PYTHONPATH:+$PYTHONPATH}""
echo ""

for WXG in ${WXGs} ; do

	echo ""
	echo "read -p 'Convert ${WXG}'"
	echo "wxglade ${WXG}"

done;
