# GNUmed client config file
# $Source: /home/ncq/Projekte/cvs2git/vcs-mirror/gnumed/gnumed/client/gm-from-cvs.conf,v $
# $Revision: 1.6.2.2 $

[preferences]
profile = GNUmed - v5 database at salaam.homeunix.com
login = any-doc


[XDT profile generic XDT connector]
source = xDT allgemein
filename = patient.xdt


[XDT profile APW (fake)]
source = APW (fake)
encoding = cp850
DOB format = %d%m%Y
filename = /home/ncq/gnumed/xDT/APW2GNUmed-cp850.gdt


[profile GNUmed - v5 database on this machine (Linux)]
host = 
port = 5432
database = gnumed_v5


# resource directory =
[XDT profile NFZ SP2]
source = Medistar SP2
DOB format = %Y%m%d
filename = /media/nfz/behandlung2/c/BDT/PAT.BDT


[profile GNUmed - v5 database on this machine (Windows)]
host = 127.0.0.1
encoding = cp1252
port = 5432
database = gnumed_v5


[*remove*AU PracSoft PATIENTS.IN]
*remove*source = PracSoft (fake)
*remove*filename = ~/gnumed/xDT/PATIENTS.IN


[client]


[workplace]
XDT profiles = $XDT profiles$
$XDT profiles$
help desk = GNUmed Development List <Gnumed-devel@gnu.org>
name = Release 0.2.5


[XDT profile test source 2]
source = source 2 (xdt)
filename = patient-2.xdt


[profile GNUmed - v5 database at salaam.homeunix.com]
host = salaam.homeunix.com
port = 5432
database = gnumed_v5


[backend]
logins = $logins$
any-doc
$logins$
profiles = $profiles$
GNUmed - v5 database on this machine (Linux)
GNUmed - v5 database on this machine (Windows)
GNUmed - v5 database at salaam.homeunix.com
$profiles$


