// file DsObservationPolicies.idl
#ifndef _DS_OBSERVATION_POLICIES_IDL_
#define _DS_OBSERVATION_POLICIES_IDL_

#pragma prefix "omg.org"

#include "DsObservationTimeSeries.idl"

module DsObservationPolicies 
{
	typedef DsObservationAccess::QualifiedCodeStr QualifiedCodeStr;
	typedef DsObservationAccess::TimeStamp TimeStamp;

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr SEARCH_DEPTH_POLICY	= "DNS:omg.org/DsObservationAccess/policy/SEARCH_DEPTH_POLICY";
    typedef short SearchDepthPolicyType;
	    const SearchDepthPolicyType SEARCH_DEPTH_ONLY_ROOT			= 0x0;
	    const SearchDepthPolicyType SEARCH_DEPTH_DEEPEST_POSSIBLE	= 0x7FFF; // default

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr RETURN_DEPTH_POLICY	= "DNS:omg.org/DsObservationAccess/policy/RETURN_DEPTH_POLICY";
	typedef QualifiedCodeStr ReturnDepthPolicyType;
	    const ReturnDepthPolicyType RETURN_DEPTH_ROOT_ONLY			= "DNS:omg.org/DsObservationAccess/policy/RETURN_DEPTH_ROOT_ONLY";
	    const ReturnDepthPolicyType RETURN_DEPTH_ALL				= "DNS:omg.org/DsObservationAccess/policy/RETURN_DEPTH_ALL";
	    const ReturnDepthPolicyType RETURN_DEPTH_ALL_LEAVES			= "DNS:omg.org/DsObservationAccess/policy/RETURN_DEPTH_ALL_LEAVES";
	    const ReturnDepthPolicyType RETURN_DEPTH_LEAVES_OF_MATCHED	= "DNS:omg.org/DsObservationAccess/policy/RETURN_DEPTH_LEAVES_OF_MATCHED";
	    const ReturnDepthPolicyType RETURN_DEPTH_MATCHED_ONLY		= "DNS:omg.org/DsObservationAccess/policy/RETURN_DEPTH_MATCHED_ONLY";
	    const ReturnDepthPolicyType RETURN_DEPTH_MATCHED_AND_DOWN	= "DNS:omg.org/DsObservationAccess/policy/RETURN_DEPTH_MATCHED_AND_DOWN"; // default

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// RETURN_OBSERVATION_VALUES_POLICY is useful when metadata (qualifiers) only are desired
	// no real values desired
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr RETURN_OBSERVATION_VALUES_POLICY	= "DNS:omg.org/DsObservationAccess/policy/RETURN_OBSERVATION_VALUES_POLICY";
	typedef QualifiedCodeStr ReturnObservationValuesPolicyType;
	    const ReturnObservationValuesPolicyType RETURN_NO_OBSERVATION_VALUES	= "DNS:omg.org/DsObservationAccess/policy/RETURN_NO_OBSERVATION_VALUES";
	    const ReturnObservationValuesPolicyType RETURN_OBSERVATION_VALUES		= "DNS:omg.org/DsObservationAccess/policy/RETURN_OBSERVATION_VALUES";  // default

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr SEARCH_SYNONYMOUS_CODES_POLICY	= "DNS:omg.org/DsObservationAccess/policy/SEARCH_SYNONYMOUS_CODES_POLICY";
	typedef QualifiedCodeStr SearchSynonymousCodesPolicyType;
	    const SearchSynonymousCodesPolicyType SEARCH_SYNONYMOUS_CODES_FALSE	= "DNS:omg.org/DsObservationAccess/policy/SEARCH_SYNONYMOUS_CODES_FALSE";
	    const SearchSynonymousCodesPolicyType SEARCH_SYNONYMOUS_CODES_TRUE	= "DNS:omg.org/DsObservationAccess/policy/SEARCH_SYNONYMOUS_CODES_TRUE"; // default

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr SHORTCIRCUIT_SEARCH_CODES_ON_SUCCESS_POLICY	= "DNS:omg.org/DsObservationAccess/policy/SHORTCIRCUIT_SEARCH_CODES_ON_SUCCESS_POLICY";
	typedef boolean ShortcircuitSearchCodesOnSuccessPolicyType;
	    const ShortcircuitSearchCodesOnSuccessPolicyType SHORTCIRCUIT_SEARCH_CODES_ON_SUCCESS_FALSE	= FALSE;  // default
	    const ShortcircuitSearchCodesOnSuccessPolicyType SHORTCIRCUIT_SEARCH_CODES_ON_SUCCESS_TRUE	= TRUE; 

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr SEARCH_SYNONYMOUS_IDS_POLICY	= "DNS:omg.org/DsObservationAccess/policy/SEARCH_SYNONYMOUS_IDS_POLICY";
	typedef boolean SearchSynonymousIDsPolicyType;
	    const SearchSynonymousIDsPolicyType SEARCH_SYNONYMOUS_IDS_FALSE	= FALSE;
	    const SearchSynonymousIDsPolicyType SEARCH_SYNONYMOUS_IDS_TRUE 	= TRUE; // default

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr SHORTCIRCUIT_SEARCH_IDS_ON_SUCCESS_POLICY	= "DNS:omg.org/DsObservationAccess/policy/SHORTCIRCUIT_SEARCH_IDS_ON_SUCCESS_POLICY";
	typedef boolean ShortcircuitSearchIdsOnSuccessPolicyType;
	    const ShortcircuitSearchIdsOnSuccessPolicyType SHORTCIRCUIT_SEARCH_IDS_ON_SUCCESS_FALSE	= FALSE; // default
	    const ShortcircuitSearchIdsOnSuccessPolicyType SHORTCIRCUIT_SEARCH_IDS_ON_SUCCESS_TRUE 	= TRUE;

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr RETURN_ITEMS_IN_TIME_SPAN_POLICY	= "DNS:omg.org/DsObservationAccess/policy/RETURN_ITEMS_IN_TIME_SPAN_POLICY";
	typedef QualifiedCodeStr ReturnTimesInTimeSpanPolicyType;
	    const ReturnTimesInTimeSpanPolicyType RETURN_ITEMS_IN_TIME_SPAN_FIRST_ITEM_ONLY	= "DNS:omg.org/DsObservationAccess/policy/RETURN_ITEMS_IN_TIME_SPAN_FIRST_ITEM_ONLY";
	    const ReturnTimesInTimeSpanPolicyType RETURN_ITEMS_IN_TIME_SPAN_LAST_ITEM_ONLY	= "DNS:omg.org/DsObservationAccess/policy/RETURN_ITEMS_IN_TIME_SPAN_LAST_ITEM_ONLY";
	    const ReturnTimesInTimeSpanPolicyType RETURN_ITEMS_IN_TIME_SPAN_ALL_ITEMS		= "DNS:omg.org/DsObservationAccess/policy/RETURN_ITEMS_IN_TIME_SPAN_ALL_ITEMS"; // default

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr MATCHING_STRENGTH_POLICY	= "DNS:omg.org/DsObservationAccess/policy/MATCHING_STRENGTH_POLICY";
	typedef float MatchingStrengthPolicyType;
	    const MatchingStrengthPolicyType MATCHING_STRENGTH_WEAKEST		= 0.0;//0.0F;//1.0;
	    const MatchingStrengthPolicyType MATCHING_STRENGTH_STRONGEST	= 1.0;//1.0F;//00.0; // default

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr PARAM_CHECKING_POLICY	= "DNS:omg.org/DsObservationAccess/policy/PARAM_CHECKING_POLICY";
	typedef boolean ParamCheckingPolicyType;
	    const ParamCheckingPolicyType PARAM_CHECKING_FALSE	= FALSE;
	    const ParamCheckingPolicyType PARAM_CHECKING_TRUE	= TRUE; // default

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// QUALIFIER_RETURN_POLICY: see DsObservationQualifiers.idl for list of qualifiers 
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr QUALIFIER_RETURN_POLICY	= "DNS:omg.org/DsObservationAccess/policy/QUALIFIER_RETURN_POLICY";
	typedef sequence<QualifiedCodeStr> QualifierReturnPolicyType;
		// two special codes for this policy; 
		const QualifiedCodeStr QUALIFIER_RETURN_ALL		= "DNS:omg.org/DsObservationAccess/policy/QUALIFIER_RETURN_ALL";
		const QualifiedCodeStr QUALIFIER_RETURN_NONE	= "DNS:omg.org/DsObservationAccess/policy/QUALIFIER_RETURN_NONE"; // default

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// RELATIONS_RETURN_POLICY: see DsObservationRelations.idl for list of relations
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr RELATIONS_RETURN_POLICY	= "DNS:omg.org/DsObservationAccess/policy/RELATIONS_RETURN_POLICY";
	typedef sequence<QualifiedCodeStr> RelationsReturnPolicyType;
		// two special codes for this policy; 
		const QualifiedCodeStr RELATIONS_RETURN_ALL		= "DNS:omg.org/DsObservationAccess/policy/RELATIONS_RETURN_ALL";
		const QualifiedCodeStr RELATIONS_RETURN_NONE	= "DNS:omg.org/DsObservationAccess/policy/RELATIONS_RETURN_NONE"; // default: RELATIONS_RETURN_NONE

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr TIME_SERIES_REMOTE_RESAMPLE_ALGORITHM_POLICY	= "DNS:omg.org/DsObservationAccess/policy/TIME_SERIES_REMOTE_RESAMPLE_ALGORITHM_POLICY";
	typedef sequence<QualifiedCodeStr> TimeSeriesRemoteResampleAlgorithmPolicyType;

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr TIME_SERIES_REMOTE_RETURN_TYPE_PREFERENCE_POLICY	= "DNS:omg.org/DsObservationAccess/policy/TIME_SERIES_REMOTE_RETURN_TYPE_PREFERENCE_POLICY";
	typedef DsObservationTimeSeries::ValueSeqType TimeSeriesRemoteReturnTypePreferencePolicyType;
	
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr RETURN_MOST_RECENT_N_OBSERVATIONS_POLICY	= "DNS:omg.org/DsObservationAccess/policy/RETURN_MOST_RECENT_N_OBSERVATIONS_POLICY";
	typedef unsigned long ReturnMostRecent_N_ObservationsPolicyType;
		const unsigned long RETURN_MOST_RECENT_N_OBSERVATIONS_ALL	= 0xFFFFFF; // default

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// RETURN_MAX_SEQUENCE_FOR_VALUE_POLICY for ObservationValues which can return iterators, 
	// like DsObservationValues::Multimedia. this policy value is analogous to the max_sequence parameter
	// (that parameter applies only to the number of ObservationData items returned)
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	typedef unsigned long ReturnMaxSequenceForValueIteratorsPolicyType;
		const ReturnMaxSequenceForValueIteratorsPolicyType RETURN_MAX_SEQUENCE_FOR_VALUE_ALL	= 0xFFFFFF; // default

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr IGNORE_UNMATCHABLE_QUALIFIERS_POLICY	= "DNS:omg.org/DsObservationAccess/policy/IGNORE_UNMATCHABLE_QUALIFIERS_POLICY";
	typedef boolean IgnoreUnmatchableQualifiersPolicyType;
		const IgnoreUnmatchableQualifiersPolicyType IGNORE_UNMATCHABLE_QUALIFIERS_TRUE	= TRUE; 
		const IgnoreUnmatchableQualifiersPolicyType IGNORE_UNMATCHABLE_QUALIFIERS_FALSE	= FALSE; // default
};

#endif // _DS_OBSERVATION_POLICIES_IDL_
