// File DsObservationRelations.idl
#ifndef _DS_OBSERVATION_RELATIONS_IDL_
#define _DS_OBSERVATION_RELATIONS_IDL_

#pragma prefix "omg.org"

#include "DsObservationAccess.idl"

module DsObservationRelations 
{

	typedef DsObservationAccess::QualifiedCodeStr QualifiedCodeStr;
	
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// all relations are collections of observations (composite observations)
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    typedef DsObservationAccess::ObservationData RELATION_type;

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// From CEN/TC 251/N98-116, table A.5
	// CEN description names translated according to the following rules:
	//		replace "/" with "_"
	//		replace space with nothing, Capitalizing next word 
	//		replace apostrophe, periods, etc. with nothing
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Produces /is produced by healthcare activity produces result, report, study product
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr Produces		= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/Produces";
	const QualifiedCodeStr IsProducedBy	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsProducedBy";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Is documented by /documents healthcare activity is documented by note (3.15)
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr Documents		= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/Documents";
	const QualifiedCodeStr IsDocumentedBy	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsDocumentedBy";
		
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Is reported within /reports about property is reported within report (3.17)
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr Reports		= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/Reports";
	const QualifiedCodeStr IsReportedBy	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsReportedBy";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Describes /is described by graphic property (3.22) describes graphic object (3.21)
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr Describes		= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/Describes";
	const QualifiedCodeStr IsDescribedBy	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsDescribedBy";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Is identified within /incorporates graphic object is identified within study product (3.20)
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr IsIdentifiedWithin	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsIdentifiedWithin";
	const QualifiedCodeStr IsIncorporatedBy		= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsIncorporatedBy";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Is derived from /is source for graphic property is derived from study product
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr IsSourceFor		= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsSourceFor";
	const QualifiedCodeStr IsDerivedFrom	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsDerivedFrom";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Is compared to /is reference for situation, document is compared to situation, document
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr IsComparedTo		= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsComparedTo";
	const QualifiedCodeStr IsReferenceFor	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsReferenceFor";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Is recorded against /is recorded against family history of x is recorded against no evidence of x (note 3)
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr IsRecordedAgainst	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsRecordedAgainst";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Superseds /is superseded by clinical state superseds clinical state (note 4)
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr Supercedes		= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/Supercedes";
	const QualifiedCodeStr IsSupercededBy	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsSupercededBy";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Organizational links
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Is framework for /is framed in contact is framework for situation, document
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr IsFrameworkFor	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsFrameworkFor";
	const QualifiedCodeStr IsFramedBy		= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsFramedBy";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Has phase /is phase of healthcare activity has phase healthcare (sub)activity
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr HasPhase		= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/HasPhase";
	const QualifiedCodeStr IsPhaseOf	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsPhaseOf";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Is next phase wrt /has next phase healthcare activity is next phase wrt healthcare (sibling) activity
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr HasNextPhase		= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/HasNextPhase";
	const QualifiedCodeStr IsNextPhaseWRT	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsNextPhaseWRT";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Is associate to /is associate to condition is associate to condition
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr IsAssociateTo	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsAssociateTo";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Is assigned to /is setting for situation is assigned to problem
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr IsAssignedTo	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsAssignedTo";
	const QualifiedCodeStr IsSettingFor	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsSettingFor";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Is interpretation of/ is interpreted as condition is interpretation of findings, report
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr IsInterpretationOf	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsInterpretationOf";
	const QualifiedCodeStr IsInterpretedAs		= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsInterpretedAs";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Has progress /is progress of condition has progress condition (e.g. convalescence)
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr HasProgress	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/HasProgress";
	const QualifiedCodeStr IsProgressOf	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsProgressOf";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Has cause /is cause of condition has cause condition
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr HasCause		= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/HasCause";
	const QualifiedCodeStr IsCauseOf	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsCauseOf";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Co-exists with /co-exists with condition co-exist with condition
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr CoExistsWith	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/CoExistsWith";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Is evidence for /has evidence finding is evidence for diagnosis
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr HasEvidence		= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/HasEvidence";
	const QualifiedCodeStr IsEvidenceFor	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsEvidenceFor";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Triggers /is triggered by presence of prosthesis triggers risk state
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr Triggers			= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/Triggers";
	const QualifiedCodeStr IsTriggeredBy	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsTriggeredBy";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Has goal /is goal of healthcare activity has goal achievable situation
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr HasGoal	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/HasGoal";
	const QualifiedCodeStr IsGoalOf	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsGoalOf";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Has motivation /is motivation for healthcare activity has motivation current situation
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr HasMotivation	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/HasMotivation";
	const QualifiedCodeStr IsMotivationFor	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsMotivationFor";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Has consequence /is consequence of healthcare activity, event has consequence situation (e.g. outcome)
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr HasConsequence	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/HasConsequence";
	const QualifiedCodeStr IsConsequenceOf	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsConsequenceOf";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Circumstantial links
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Has topic /is topic for informing has topic record component
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr HasTopic		= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/HasTopic";
	const QualifiedCodeStr IsTopicFor	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsTopicFor";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Has target /is target of informing has target person
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr HasTarget	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/HasTarget";
	const QualifiedCodeStr IsTargetOf	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsTargetOf";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Provides information about /is reported by person provides information about record component
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr ProvidesInformationAbout	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/ProvidesInformationAbout";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Has circumstances /is circumstance for support activity has circumstance home circumstances
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr HasCircumstances	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/HasCircumstances";
	const QualifiedCodeStr IsCircumstanceOf	= "DNS:omg.org/DsObservationAccess/relation/CENTC251N98116/IsCircumstanceOf";
};

#endif // _DS_OBSERVATION_RELATIONS_IDL_
