// File DsObservationQualifiers.idl
#ifndef _DS_OBSERVATION_QUALIFIERS_IDL_
#define _DS_OBSERVATION_QUALIFIERS_IDL_

#pragma prefix "omg.org"

#include "DsObservationAccess.idl"

module DsObservationQualifiers
{
	typedef DsObservationAccess::QualifiedCodeStr	QualifiedCodeStr;
	typedef DsObservationAccess::TimeStamp			TimeStamp;

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// All the qualifiers listed here from HL7 are defined with subcomponents in HL7 2.3, so they all have type ObservationData (composite observations)
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    typedef DsObservationAccess::ObservationData COMPOSITE_OBSERVATION_type;

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// naming convention: 
	//		start with "DNS:omg.org/DsObservationAccess/HL72.3/"
	//		add the HL7 segment name, like OBX or PID, plus a slash
	//		take HL7 data element names from HL7 v3.2 standard distribution, 
	//		appendix A, (APPA.doc), table A.6 DATA ELEMENT NAMES, 
	//		translated according to the following rules:
	//		replace "/" with "_"
	//		replace space with nothing, capitalizing next word 
	//		omit apostrophe, periods, parentheses, and other punctuation
	//		to name subcomponents, additional slashes can follow the component names
	//			see SpecimenSourceBodySite at bottom for example
	// see HL7 descriptions for composite returned by each of these data elements.
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Clinical times; 
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr Date_TimeOfTheObservation	= "DNS:omg.org/DsObservationAccess/HL72.3/OBX/Date_TimeOfTheObservation";
	const QualifiedCodeStr EventOnsetDate_Time			= "DNS:omg.org/DsObservationAccess/HL72.3/PEO/EventOnsetDate_Time";
	const QualifiedCodeStr OrderEffectiveDate_Time		= "DNS:omg.org/DsObservationAccess/HL72.3/ORC/OrderEffectiveDate_Time";
	const QualifiedCodeStr ProcedureDate_Time			= "DNS:omg.org/DsObservationAccess/HL72.3/PR1/ProcedureDate_Time";
	const QualifiedCodeStr RequestedDate_Time			= "DNS:omg.org/DsObservationAccess/HL72.3/OBR/RequestedDate_Time";
	const QualifiedCodeStr VerificationDate_Time		= "DNS:omg.org/DsObservationAccess/HL72.3/IN1/VerificationDate_Time";
	const QualifiedCodeStr ActionDate_Time				= "DNS:omg.org/DsObservationAccess/HL72.3/GOL/ActionDate_Time";
	const QualifiedCodeStr AttestationDate_Time			= "DNS:omg.org/DsObservationAccess/HL72.3/DG1/AttestationDate_Time";
	const QualifiedCodeStr TranscriptionDate_Time		= "DNS:omg.org/DsObservationAccess/HL72.3/TXA/TranscriptionDate_Time";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Roles
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr PatientIDExternalID			= "DNS:omg.org/DsObservationAccess/HL72.3/PID/PatientIDExternalID";
	const QualifiedCodeStr PatientIDInternalID			= "DNS:omg.org/DsObservationAccess/HL72.3/PID/PatientIDInternalID";
	const QualifiedCodeStr OrderingProvider				= "DNS:omg.org/DsObservationAccess/HL72.3/OBR/OrderingProvider";
	const QualifiedCodeStr ProducerID	    			= "DNS:omg.org/DsObservationAccess/HL72.3/OBX/ProducerID";
	const QualifiedCodeStr CollectorIndentifier			= "DNS:omg.org/DsObservationAccess/HL72.3/OBR/CollectorIndentifier";
	const QualifiedCodeStr ResponsibleObserver			= "DNS:omg.org/DsObservationAccess/HL72.3/OBX/ResponsibleObserver";
	const QualifiedCodeStr Technician					= "DNS:omg.org/DsObservationAccess/HL72.3/OBR/Technician";
	const QualifiedCodeStr PrincipalResultInterpreter   = "DNS:omg.org/DsObservationAccess/HL72.3/OBR/PrincipalResultInterpreter";
	
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// From OBR (orders)
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr SpecimenSource				= "DNS:omg.org/DsObservationAccess/HL72.3/OBR/SpecimenSource";
	const QualifiedCodeStr ReasonForStudy				= "DNS:omg.org/DsObservationAccess/HL72.3/OBR/ReasonForStudy";
	const QualifiedCodeStr DiagnosticServiceSectionID	= "DNS:omg.org/DsObservationAccess/HL72.3/OBR/DiagnosticServiceSectionID";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// From OBX (results)
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr AbnormalFlags			= "DNS:omg.org/DsObservationAccess/HL72.3/OBX/AbnormalFlags";
	const QualifiedCodeStr ObservationMethod		= "DNS:omg.org/DsObservationAccess/HL72.3/OBX/ObservationMethod";
    const QualifiedCodeStr Units					= "DNS:omg.org/DsObservationAccess/HL72.3/OBX/Units";
	const QualifiedCodeStr ReferencesRange			= "DNS:omg.org/DsObservationAccess/HL72.3/OBX/ReferencesRange";
	const QualifiedCodeStr ObservationIdentifier	= "DNS:omg.org/DsObservationAccess/HL72.3/OBX/ObservationIdentifier";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// From PV1
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr PatientLocation	= "DNS:omg.org/DsObservationAccess/HL72.3/PV1/PatientLocation";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// Note that elements of HL7 composites can be individually identified with this COAS naming standard. 
	// e.g.  SpecimenSource is listed in the OBR definitions above, and one segment
	// of SpecimenSource, like Body Site, can have its own name.  
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	const QualifiedCodeStr SpecimenSourceBodySite	= "DNS:omg.org/DsObservationAccess/HL72.3/OBR/SpecimenSource/BodySite";
	typedef QualifiedCodeStr SpecimenSourceBodySite_type;
};

#endif // _DS_OBSERVATION_QUALIFIERS_IDL_
