#!/usr/bin/env python
# generated by wxGlade 0.2 on Fri Feb 14 23:43:37 2003

from wxPython.wx import *

class HandlerWarnDialog(wxDialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog3.__init__
        kwds["style"] = wxDEFAULT_DIALOG_STYLE | wxSTAY_ON_TOP
        wxDialog.__init__(self, *args, **kwds)
        self.label_2 = wxStaticText(self, -1, "label_2")
        self.button_3 = wxButton(self, -1, "OK")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog3.__set_properties
        self.SetTitle("ADVISORY")
        # end wxGlade
	id = wxNewId()
	self.button_3.SetId(id)
	EVT_BUTTON( self.button_3, id, self.endModal)
	
    def setMessage(self, message):
	self.label_2.SetLabel( message)
	self.GetBestSize()	
    def endModal(self, event):
	self.EndModal(wxID_OK)
	
    def __do_layout(self):
        # begin wxGlade: MyDialog3.__do_layout
        sizer_2 = wxBoxSizer(wxVERTICAL)
        sizer_2.Add(38, 20, 0, 0, 0)
        sizer_2.Add(self.label_2, 4, wxEXPAND, 0)
        sizer_2.Add(self.button_3, 0, 0, 0)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        sizer_2.SetSizeHints(self)
        self.Layout()
        # end wxGlade
   
# end of class MyDialog3


