#reads the filelist generated by bootstrap-parse and approximates a 
#gnumed schema install as per redo-max.sh , which is broken currently in cygwin.

python bootstrap-parse.py ../bootstrap/bootstrap-monolithic_core.conf filelist;

dropdb gnumed
createdb gnumed
createlang -d gnumed plpgsql
for  x in `cat filelist`;do
	echo psql -f $x gnumed
	psql -f $x gnumed 2>> err
done

#some of the country specific data is needed, such as enum_ext_id_types
sh install_local_schema.sh

