--
-- Name: entity Type: TABLE DATA Owner: ian
--


COPY "entity"  FROM stdin;
1	ABACAVIR SULFATE	f	f
2	ABCIXIMAB	f	f
3	ACAMPROSATE CALCIUM	f	f
4	ACARBOSE	f	f
5	ACETAZOLAMIDE	f	f
6	ACETYLCYSTEINE	f	f
7	ACICLOVIR	f	f
8	ACITRETIN	f	f
9	ADRENALINE	f	f
10	ALBENDAZOLE	f	f
11	ALENDRONATE SODIUM	f	f
14	ALLOPURINOL	f	f
15	ALPRAZOLAM	f	f
16	ALPROSTADIL	f	f
22	AMANTADINE HYDROCHLORIDE	f	f
23	AMILORIDE HYDROCHLORIDE	f	f
34	AMINOGLUTETHIMIDE	f	f
35	AMIODARONE HYDROCHLORIDE	f	f
36	AMITRIPTYLINE HYDROCHLORIDE	f	f
37	AMLODIPINE BESYLATE	f	f
38	AMMONIUM CHLORIDE	f	f
39	AMOROLFINE HYDROCHLORIDE	f	f
40	AMOXYCILLIN	f	f
42	AMPHOTERICIN	f	f
43	AMPICILLIN	f	f
44	ANASTROZOLE	f	f
46	APOMORPHINE HYDROCHLORIDE	f	f
47	APRACLONIDINE HYDROCHLORIDE	f	f
48	ASCORBIC ACID	f	f
49	ASPIRIN	f	f
50	ATENOLOL	f	f
51	ATORVASTATIN CALCIUM	f	f
52	ATOVAQUONE	f	f
53	ATROPINE SULFATE	f	f
54	AURANOFIN	f	f
55	AUROTHIOGLUCOSE	f	f
56	AZATHIOPRINE	f	f
57	AZITHROMYCIN	f	f
58	BACLOFEN	f	f
59	BANDAGE-ABSORBENT WOOL	f	f
60	BANDAGE-CALICO	f	f
61	BANDAGE-COMPRESSION	f	f
62	BANDAGE-RETENTION-COHESIVE-HEAVY	f	f
63	BANDAGE-RETENTION-COHESIVE-LIGHT	f	f
64	BANDAGE-RETENTION-COTTON CREPE	f	f
65	BANDAGE-TUBULAR	f	f
66	BANDAGE-TUBULAR (FINGER)	f	f
67	BANDAGE-TUBULAR (LIGHTWEIGHT)	f	f
68	BANDAGE-TUBULAR (LONG STOCKING)	f	f
69	BANDAGE-TUBULAR (SHORT STOCKING)	f	f
70	BANDAGE-ZINC PASTE	f	f
71	BATH EMOLLIENT	f	f
72	BCG IMMUNOTHERAPEUTIC (Bacillus Calmette-Gue rin/ Connaught 	f	f
73	BCG-TICE (Bacillus Calmette-Gue rin/ Tice strain)	f	f
74	BECLOMETHASONE DIPROPIONATE	f	f
75	BENDROFLUAZIDE	f	f
76	BENZATHINE PENICILLIN	f	f
77	BENZHEXOL HYDROCHLORIDE	f	f
78	BENZTROPINE MESYLATE	f	f
79	BENZYDAMINE HYDROCHLORIDE	f	f
80	BENZYL BENZOATE	f	f
81	BENZYLPENICILLIN	f	f
83	BETAMETHASONE DIPROPIONATE	f	f
84	BETAMETHASONE VALERATE	f	f
85	BETAXOLOL HYDROCHLORIDE	f	f
86	BETHANECHOL CHLORIDE	f	f
87	BICALUTAMIDE	f	f
88	BIFONAZOLE	f	f
89	BIPERIDEN HYDROCHLORIDE	f	f
90	BISACODYL	f	f
91	BISMUTH SUBCITRATE	f	f
93	BLEOMYCIN	f	f
94	BOTULINUM TOXIN TYPE A PURIFIED NEUROTOXIN COMPLEX	f	f
95	BRIMONIDINE TARTRATE	f	f
96	BRINZOLAMIDE	f	f
97	BROMAZEPAM	f	f
98	BROMOCRIPTINE MESYLATE	f	f
99	BUDESONIDE	f	f
100	BUMETANIDE	f	f
101	BUPROPION HYDROCHLORIDE	f	f
102	BUSPIRONE HYDROCHLORIDE	f	f
103	BUSULFAN	f	f
104	CABERGOLINE	f	f
105	CALCIPOTRIOL	f	f
106	CALCITONIN	f	f
107	CALCITRIOL	f	f
108	CALCIUM	f	f
110	CALCIUM FOLINATE	f	f
111	CANDESARTAN CILEXETIL	f	f
112	CAPECITABINE	f	f
113	CAPTOPRIL	f	f
114	CARBACHOL	f	f
115	CARBAMAZEPINE	f	f
116	CARBAMIDE PEROXIDE	f	f
117	CARBIMAZOLE	f	f
119	CARBOMER 940	f	f
120	CARBOMER 980	f	f
121	CARBOPLATIN	f	f
122	CARMELLOSE SODIUM	f	f
124	CARVEDILOL	f	f
126	CEFACLOR	f	f
127	CEFEPIME	f	f
128	CEFOTAXIME	f	f
129	CEFOTETAN	f	f
130	CEFTRIAXONE	f	f
131	CEFUROXIME AXETIL	f	f
132	CELECOXIB	f	f
133	CEPHALEXIN	f	f
134	CEPHALOTHIN	f	f
135	CEPHAZOLIN	f	f
136	CERIVASTATIN SODIUM	f	f
137	CETIRIZINE HYDROCHLORIDE	f	f
138	CHARCOAL, ACTIVATED	f	f
139	CHLORAMBUCIL	f	f
140	CHLORAMPHENICOL	f	f
141	CHLORHEXIDINE GLUCONATE	f	f
142	CHLORPROMAZINE HYDROCHLORIDE	f	f
143	CHLORTHALIDONE	f	f
144	CHOLESTYRAMINE	f	f
145	CIDOFOVIR	f	f
146	CIMETIDINE	f	f
147	CIPROFLOXACIN	f	f
148	CISAPRIDE	f	f
149	CISPLATIN	f	f
150	CITALOPRAM HYDROBROMIDE	f	f
151	CLADRIBINE	f	f
152	CLARITHROMYCIN	f	f
153	CLINDAMYCIN	f	f
154	CLOMIPHENE CITRATE	f	f
155	CLOMIPRAMINE HYDROCHLORIDE	f	f
156	CLONAZEPAM	f	f
157	CLONIDINE	f	f
158	CLOPIDOGREL HYDROGEN SULFATE	f	f
159	CLOTRIMAZOLE	f	f
160	CLOZAPINE	f	f
161	CODEINE PHOSPHATE	f	f
164	COLCHICINE	f	f
165	COLESTIPOL HYDROCHLORIDE	f	f
166	COPPER SULFATE	f	f
167	CORTISONE ACETATE	f	f
168	COTTON WOOL ROLL	f	f
169	CYCLOPHOSPHAMIDE	f	f
170	CYCLOSPORIN	f	f
171	CYPROHEPTADINE HYDROCHLORIDE	f	f
172	CYPROTERONE ACETATE	f	f
173	CYTARABINE	f	f
175	DANAZOL	f	f
176	DANTROLENE SODIUM	f	f
177	DELAVIRDINE MESYLATE	f	f
178	DEMECLOCYCLINE HYDROCHLORIDE	f	f
179	DESFERRIOXAMINE MESYLATE	f	f
180	DESMOPRESSIN ACETATE	f	f
181	DEXAMETHASONE	f	f
182	DEXAMETHASONE SODIUM PHOSPHATE	f	f
184	DEXAMPHETAMINE SULFATE	f	f
188	DEXTROPROPOXYPHENE NAPSYLATE	f	f
189	DIAZEPAM	f	f
191	DICLOFENAC POTASSIUM	f	f
192	DICLOFENAC SODIUM	f	f
194	DICLOXACILLIN	f	f
195	DICYCLOMINE HYDROCHLORIDE	f	f
196	DIDANOSINE	f	f
197	DIFLUNISAL	f	f
198	DIGOXIN	f	f
199	DIHYDROERGOTAMINE MESYLATE	f	f
200	DILTIAZEM HYDROCHLORIDE	f	f
202	DIPHEMANIL METHYLSULFATE	f	f
206	DIPHTHERIA ANTITOXIN	f	f
207	DIPIVEFRINE HYDROCHLORIDE	f	f
208	DIPYRIDAMOLE	f	f
210	DISODIUM ETIDRONATE	f	f
212	DISODIUM PAMIDRONATE	f	f
213	DISOPYRAMIDE	f	f
214	DOCETAXEL	f	f
215	DOCUSATE SODIUM	f	f
218	DOLASETRON MESYLATE	f	f
219	DOMPERIDONE	f	f
220	DONEPEZIL HYDROCHLORIDE	f	f
221	DORNASE ALFA	f	f
222	DORZOLAMIDE HYDROCHLORIDE	f	f
223	DOTHIEPIN HYDROCHLORIDE	f	f
224	DOXEPIN HYDROCHLORIDE	f	f
225	DOXORUBICIN HYDROCHLORIDE	f	f
226	DOXORUBICIN HYDROCHLORIDE, PEGYLATED LIPOSOMAL	f	f
227	DOXYCYCLINE	f	f
253	DYDROGESTERONE	f	f
254	ECONAZOLE NITRATE	f	f
255	ECOTHIOPATE IODIDE	f	f
256	EFAVIRENZ	f	f
257	EFORMOTEROL FUMARATE DIHYDRATE	f	f
258	ELECTROLYTE REPLACEMENT (ORAL)	f	f
259	ELECTROLYTE REPLACEMENT SOLUTION	f	f
260	ENALAPRIL MALEATE	f	f
262	ENOXACIN	f	f
263	ENOXAPARIN SODIUM	f	f
264	ENTACAPONE	f	f
265	EPIRUBICIN HYDROCHLORIDE	f	f
266	EPOETIN ALFA	f	f
267	EPROSARTAN MESYLATE	f	f
268	ERGOTAMINE TARTRATE	f	f
270	ERYTHROMYCIN	f	f
271	ERYTHROMYCIN ETHYL SUCCINATE	f	f
272	ERYTHROMYCIN LACTOBIONATE	f	f
273	ERYTHROMYCIN STEARATE	f	f
275	ETHACRYNIC ACID	f	f
276	ETHOSUXIMIDE	f	f
277	ETONOGESTREL	f	f
278	ETOPOSIDE	f	f
279	ETOPOSIDE PHOSPHATE	f	f
280	FAMCICLOVIR	f	f
281	FAMOTIDINE	f	f
282	FELODIPINE	f	f
283	FENTANYL	f	f
284	FERROUS GLUCONATE	f	f
286	FEXOFENADINE HYDROCHLORIDE	f	f
287	FILGRASTIM	f	f
288	FINASTERIDE	f	f
289	FLECAINIDE ACETATE	f	f
290	FLUCLOXACILLIN	f	f
291	FLUCONAZOLE	f	f
292	FLUDROCORTISONE ACETATE	f	f
293	FLUNITRAZEPAM	f	f
294	FLUOROMETHOLONE	f	f
295	FLUOROMETHOLONE ACETATE	f	f
296	FLUOROURACIL	f	f
297	FLUOXETINE HYDROCHLORIDE	f	f
300	FLURBIPROFEN SODIUM	f	f
301	FLUTAMIDE	f	f
302	FLUTICASONE PROPIONATE	f	f
303	FLUVASTATIN SODIUM	f	f
304	FLUVOXAMINE MALEATE	f	f
305	FOLIC ACID	f	f
306	FOLLITROPIN ALFA	f	f
307	FOLLITROPIN BETA	f	f
308	FOSCARNET SODIUM	f	f
309	FOSFESTROL SODIUM	f	f
310	FOSINOPRIL SODIUM	f	f
312	FRAMYCETIN SULFATE	f	f
313	FRUSEMIDE	f	f
314	FUSIDIC ACID	f	f
315	GABAPENTIN	f	f
316	GANCICLOVIR	f	f
317	GANCICLOVIR SODIUM	f	f
319	GELATIN - SUCCINYLATED	f	f
320	GEMCITABINE HYDROCHLORIDE	f	f
321	GEMFIBROZIL	f	f
322	GENTAMICIN SULFATE	f	f
323	GESTRINONE	f	f
324	GLATIRAMER ACETATE	f	f
325	GLIBENCLAMIDE	f	f
326	GLICLAZIDE	f	f
327	GLIMEPIRIDE	f	f
328	GLIPIZIDE	f	f
329	GLOVES PLASTIC (DISPOSABLE)	f	f
330	GLUCAGON HYDROCHLORIDE	f	f
331	GLUCOSE	f	f
333	GLUCOSE INDICATOR-BLOOD	f	f
334	GLUCOSE INDICATOR-URINE	f	f
335	GLYCEROL	f	f
336	GLYCERYL TRINITRATE	f	f
337	GOSERELIN ACETATE	f	f
338	GRISEOFULVIN	f	f
339	GROUP 102-ONE-PIECE COLOSTOMY BAGS, CLOSED	f	f
340	GROUP 103-ONE-PIECE ILEOSTOMY BAGS, DRAINABLE	f	f
341	GROUP 104-ONE-PIECE UROSTOMY BAGS, DRAINABLE	f	f
342	GROUP 105-SYSTEMS-WAFERS, FLANGES AND PLUGS	f	f
343	GROUP 106-SYSTEMS-COLOSTOMY BAGS, CLOSED	f	f
344	GROUP 107-SYSTEMS-ILEOSTOMY BAGS, DRAINABLE	f	f
345	GROUP 108-SYSTEMS-UROSTOMY BAGS, DRAINABLE	f	f
346	GROUP 109-BAGS, RUBBER	f	f
347	GROUP 111-IRRIGATION SETS (COMPLETE)	f	f
348	GROUP 112-IRRIGATION SET SPARE PARTS	f	f
349	GROUP 113-BELTS	f	f
350	GROUP 117-FLANGES WITH DIAPHRAGM	f	f
351	GROUP 118-FLANGES WITHOUT DIAPHRAGM, RUBBER	f	f
352	GROUP 119-CLAMPS AND CLIPS	f	f
353	GROUP 120-MISCELLANEOUS STOMA APPLIANCES	f	f
354	GROUP 122-ADHESIVE BARRIERS	f	f
355	GROUP 123-CLEANSERS AND SOLVENTS	f	f
356	GROUP 124-CREAMS AND OINTMENTS	f	f
357	GROUP 125-DEODORANTS	f	f
358	GROUP 126-PROTECTIVE FILMS	f	f
359	GROUP 127-PROTECTIVE PASTES	f	f
360	GROUP 128-PROTECTIVE POWDERS	f	f
361	HALOPERIDOL	f	f
363	HEPARIN CALCIUM	f	f
364	HEPARIN SODIUM	f	f
365	HEXAMINE HIPPURATE	f	f
366	HOMATROPINE HYDROBROMIDE	f	f
367	HUMAN CHORIONIC GONADOTROPHIN	f	f
369	HYDRALAZINE HYDROCHLORIDE	f	f
370	HYDROCHLOROTHIAZIDE	f	f
373	HYDROCORTISONE	f	f
374	HYDROCORTISONE ACETATE	f	f
375	HYDROCORTISONE SODIUM SUCCINATE	f	f
377	HYDROLYZED COLLAGEN PROTEINS	f	f
378	HYDROMORPHONE HYDROCHLORIDE	f	f
379	HYDROXOCOBALAMIN	f	f
380	HYDROXYCHLOROQUINE SULFATE	f	f
381	HYDROXYPROPYLCELLULOSE	f	f
382	HYDROXYUREA	f	f
383	HYOSCINE BUTYLBROMIDE	f	f
384	HYPROMELLOSE	f	f
386	IBUPROFEN	f	f
387	IDARUBICIN HYDROCHLORIDE	f	f
388	IFOSFAMIDE	f	f
389	IMIPRAMINE HYDROCHLORIDE	f	f
390	INDAPAMIDE HEMIHYDRATE	f	f
391	INDINAVIR SULFATE	f	f
392	INDOMETHACIN	f	f
393	INFLUENZA VACCINE	f	f
394	INSECT ALLERGEN EXTRACT-HONEY BEE VENOM	f	f
395	INSECT ALLERGEN EXTRACT-PAPER WASP VENOM	f	f
396	INSECT ALLERGEN EXTRACT-YELLOW JACKET VENOM	f	f
397	INSULIN ASPART	f	f
398	INSULIN ISOPHANE (N.P.H.)	f	f
399	INSULIN LISPRO	f	f
400	INSULIN LISPRO-INSULIN LISPRO PROTAMINE SUSPENSION	f	f
401	INSULIN NEUTRAL	f	f
402	INSULIN NEUTRAL-INSULIN ISOPHANE (N.P.H.), (MIXED) (Biphasic	f	f
403	INSULIN ZINC SUSPENSION (CRYSTALLINE) (Ultralente)	f	f
404	INSULIN ZINC SUSPENSION (Lente)	f	f
405	INTERFERON ALFA-2a	f	f
406	INTERFERON ALFA-2b	f	f
407	INTERFERON BETA-1a	f	f
408	INTERFERON BETA-1b	f	f
409	INTERFERON GAMMA-1b	f	f
410	IPRATROPIUM BROMIDE	f	f
412	IRBESARTAN	f	f
414	IRINOTECAN HYDROCHLORIDE TRIHYDRATE	f	f
415	IRON POLYMALTOSE COMPLEX	f	f
416	ISONIAZID	f	f
417	ISOSORBIDE DINITRATE	f	f
418	ISOSORBIDE MONONITRATE	f	f
419	ISOTRETINOIN	f	f
420	ISPAGHULA HUSK	f	f
421	ITRACONAZOLE	f	f
422	IVERMECTIN	f	f
423	KETOCONAZOLE	f	f
424	KETOPROFEN	f	f
425	LABETALOL HYDROCHLORIDE	f	f
426	LACTULOSE	f	f
427	LAMIVUDINE	f	f
429	LAMOTRIGINE	f	f
430	LANSOPRAZOLE	f	f
431	LATANOPROST	f	f
432	LEFLUNOMIDE	f	f
433	LENOGRASTIM	f	f
434	LETROZOLE	f	f
435	LEUPRORELIN ACETATE	f	f
436	LEVAMISOLE HYDROCHLORIDE	f	f
437	LEVOBUNOLOL HYDROCHLORIDE	f	f
438	LEVOCABASTINE HYDROCHLORIDE	f	f
441	LEVONORGESTREL	f	f
443	LIGNOCAINE HYDROCHLORIDE	f	f
445	LINCOMYCIN	f	f
446	LIOTHYRONINE SODIUM	f	f
447	LISINOPRIL	f	f
448	LITHIUM CARBONATE	f	f
449	LODOXAMIDE TROMETAMOL	f	f
450	LOPERAMIDE HYDROCHLORIDE	f	f
451	LORATADINE	f	f
452	LUBRICATING AGENT	f	f
453	MAGNESIUM ASPARTATE	f	f
454	MEBENDAZOLE	f	f
455	MEBEVERINE HYDROCHLORIDE	f	f
456	MEDROXYPROGESTERONE ACETATE	f	f
457	MEFENAMIC ACID	f	f
458	MEGESTROL ACETATE	f	f
459	MELPHALAN	f	f
460	MERCAPTOPURINE	f	f
461	MESALAZINE	f	f
462	MESNA	f	f
463	METFORMIN HYDROCHLORIDE	f	f
464	METHADONE HYDROCHLORIDE	f	f
465	METHENOLONE ACETATE	f	f
466	METHOTREXATE	f	f
467	METHYLDOPA	f	f
468	METHYLPHENOBARBITONE	f	f
469	METHYLPREDNISOLONE ACEPONATE	f	f
470	METHYLPREDNISOLONE ACETATE	f	f
471	METHYLPREDNISOLONE SODIUM SUCCINATE	f	f
472	METHYL SALICYLATE	f	f
473	METHYSERGIDE	f	f
474	METOCLOPRAMIDE HYDROCHLORIDE	f	f
475	METOPROLOL TARTRATE	f	f
476	METRONIDAZOLE	f	f
477	METRONIDAZOLE BENZOATE	f	f
478	MEXILETINE HYDROCHLORIDE	f	f
479	MIANSERIN HYDROCHLORIDE	f	f
480	MICONAZOLE	f	f
481	MICONAZOLE NITRATE	f	f
482	MILK POWDER-LACTOSE FREE FORMULA	f	f
483	MILK POWDER-LACTOSE MODIFIED	f	f
484	MILK POWDER-SYNTHETIC	f	f
485	MINERAL MIXTURE	f	f
486	MINOCYCLINE	f	f
487	MINOXIDIL	f	f
488	MISOPROSTOL	f	f
489	MITOZANTRONE HYDROCHLORIDE	f	f
490	MOCLOBEMIDE	f	f
491	MOMETASONE FUROATE	f	f
492	MORPHINE HYDROCHLORIDE	f	f
493	MORPHINE SULFATE	f	f
494	MORPHINE TARTRATE	f	f
495	MUPIROCIN	f	f
496	MYCOPHENOLATE MOFETIL	f	f
497	NADROPARIN CALCIUM	f	f
498	NAFARELIN ACETATE	f	f
499	NALOXONE HYDROCHLORIDE	f	f
500	NALTREXONE HYDROCHLORIDE	f	f
502	NAPHAZOLINE HYDROCHLORIDE	f	f
504	NAPROXEN	f	f
505	NAPROXEN SODIUM	f	f
506	NARATRIPTAN HYDROCHLORIDE	f	f
507	NEDOCROMIL SODIUM	f	f
508	NEFAZODONE HYDROCHLORIDE	f	f
509	NELFINAVIR MESYLATE	f	f
510	NEOMYCIN SULFATE	f	f
512	NEVIRAPINE	f	f
513	NICORANDIL	f	f
514	NICOTINE	f	f
515	NICOTINIC ACID	f	f
516	NIFEDIPINE	f	f
517	NILUTAMIDE	f	f
518	NITRAZEPAM	f	f
519	NITROFURANTOIN	f	f
520	NIZATIDINE	f	f
521	NORETHISTERONE	f	f
524	NORFLOXACIN	f	f
525	NORTRIPTYLINE HYDROCHLORIDE	f	f
526	NYSTATIN	f	f
527	OCTREOTIDE	f	f
528	OCTREOTIDE ACETATE	f	f
529	OESTRADIOL	f	f
533	OESTRADIOL VALERATE	f	f
537	OESTRIOL	f	f
538	OESTROGENS-CONJUGATED	f	f
542	OFLOXACIN	f	f
543	OLANZAPINE	f	f
544	OLSALAZINE SODIUM	f	f
545	OMEPRAZOLE	f	f
547	OMEPRAZOLE MAGNESIUM	f	f
550	ONDANSETRON	f	f
551	OXANDROLONE	f	f
552	OXAZEPAM	f	f
553	OXPRENOLOL HYDROCHLORIDE	f	f
554	OXYBUTYNIN HYDROCHLORIDE	f	f
555	OXYCODONE	f	f
556	OXYCODONE HYDROCHLORIDE	f	f
557	OXYMETAZOLINE HYDROCHLORIDE	f	f
558	PACLITAXEL	f	f
559	PANCREATIC EXTRACT	f	f
560	PANCREATIN ENZYME	f	f
561	PANCRELIPASE	f	f
562	PANTOPRAZOLE SODIUM SESQUIHYDRATE	f	f
563	PARACETAMOL	f	f
564	PARAFFIN	f	f
565	PAROXETINE HYDROCHLORIDE	f	f
566	PENICILLAMINE	f	f
567	PERGOLIDE MESYLATE	f	f
568	PERHEXILINE MALEATE	f	f
569	PERICYAZINE	f	f
570	PERINDOPRIL ERBUMINE	f	f
572	PERMETHRIN	f	f
573	PETHIDINE HYDROCHLORIDE	f	f
574	PHENELZINE SULFATE	f	f
575	PHENOBARBITONE	f	f
576	PHENOBARBITONE SODIUM	f	f
577	PHENOXYBENZAMINE HYDROCHLORIDE	f	f
578	PHENOXYMETHYLPENICILLIN	f	f
579	PHENYTOIN	f	f
580	PHENYTOIN SODIUM	f	f
581	PHOLCODINE	f	f
582	PILOCARPINE	f	f
583	PILOCARPINE HYDROCHLORIDE	f	f
584	PINDOLOL	f	f
587	PIPERAZINE OESTRONE SULFATE	f	f
588	PIROXICAM	f	f
589	PIZOTIFEN MALATE	f	f
590	PNEUMOCOCCAL VACCINE, POLYVALENT	f	f
591	PODOPHYLLOTOXIN	f	f
592	POLYGELINE	f	f
595	POLYVINYL ALCOHOL	f	f
597	POTASSIUM CHLORIDE	f	f
598	POVIDONE-IODINE	f	f
599	PRAVASTATIN SODIUM	f	f
600	PRAZOSIN HYDROCHLORIDE	f	f
601	PREDNISOLONE	f	f
603	PREDNISOLONE SODIUM PHOSPHATE	f	f
604	PREDNISONE	f	f
605	PRESSURE REDUCING PRODUCTS	f	f
606	PRIMIDONE	f	f
607	PROBENECID	f	f
608	PROBUCOL	f	f
609	PROCAINAMIDE HYDROCHLORIDE	f	f
610	PROCAINE PENICILLIN	f	f
611	PROCHLORPERAZINE	f	f
612	PROMETHAZINE HYDROCHLORIDE	f	f
613	PROPANTHELINE BROMIDE	f	f
614	PROPRANOLOL HYDROCHLORIDE	f	f
615	PROPYLTHIOURACIL	f	f
616	PROTEIN HYDROLYSATE FORMULA	f	f
617	PROTEIN HYDROLYSATE FORMULA LOW IN PHENYLALANINE	f	f
619	PSEUDOEPHEDRINE HYDROCHLORIDE	f	f
620	PSEUDOEPHEDRINE SULFATE	f	f
621	PSYLLIUM HYDROPHILIC MUCILLOID	f	f
623	PYRANTEL EMBONATE	f	f
624	PYRIDOSTIGMINE BROMIDE	f	f
625	PYRIDOXINE HYDROCHLORIDE	f	f
626	PYRIMETHAMINE	f	f
627	QUETIAPINE FUMARATE	f	f
628	QUINAPRIL HYDROCHLORIDE	f	f
629	QUINIDINE BISULFATE	f	f
630	QUININE BISULFATE	f	f
631	QUININE SULFATE	f	f
632	RALOXIFENE HYDROCHLORIDE	f	f
633	RALTITREXED	f	f
634	RAMIPRIL	f	f
636	RANITIDINE HYDROCHLORIDE	f	f
637	RED-BACK SPIDER ANTIVENOM	f	f
638	RETEPLASE (Recombinant plasminogen activator)	f	f
641	RIFABUTIN	f	f
642	RIFAMPICIN	f	f
643	RISEDRONATE SODIUM	f	f
644	RISPERIDONE	f	f
645	RITONAVIR	f	f
646	RITUXIMAB	f	f
647	RIVASTIGMINE HYDROGEN TARTRATE	f	f
648	ROFECOXIB	f	f
649	ROXITHROMYCIN	f	f
650	SALBUTAMOL SULFATE	f	f
655	SALIVA SUBSTITUTE	f	f
656	SALMETEROL XINAFOATE	f	f
658	SAQUINAVIR	f	f
659	SAQUINAVIR MESYLATE	f	f
660	SELEGILINE HYDROCHLORIDE	f	f
661	SELENIUM SULFIDE	f	f
663	SENNA STANDARDISED	f	f
664	SERTRALINE HYDROCHLORIDE	f	f
665	SILDENAFIL CITRATE	f	f
667	SIMVASTATIN	f	f
668	SKIN CLEANSER	f	f
669	SODIUM ACID PHOSPHATE	f	f
671	SODIUM AUROTHIOMALATE	f	f
672	SODIUM BICARBONATE	f	f
673	SODIUM CELLULOSE PHOSPHATE	f	f
674	SODIUM CHLORIDE	f	f
675	SODIUM CHLORIDE COMPOUND	f	f
677	SODIUM CITRO-TARTRATE	f	f
678	SODIUM CLODRONATE TETRAHYDRATE	f	f
679	SODIUM CROMOGLYCATE	f	f
680	SODIUM LACTATE COMPOUND	f	f
681	SODIUM NITROPRUSSIDE	f	f
682	SODIUM POLYSTYRENE SULFONATE	f	f
683	SODIUM VALPROATE	f	f
684	SOMATROPIN (Recombinant human growth hormone)	f	f
686	SOTALOL HYDROCHLORIDE	f	f
687	SPECTINOMYCIN	f	f
688	SPIRONOLACTONE	f	f
689	STAVUDINE	f	f
691	STREPTOKINASE	f	f
692	SUCRALFATE	f	f
693	SULFACETAMIDE SODIUM	f	f
694	SULFASALAZINE	f	f
695	SULFINPYRAZONE	f	f
696	SULINDAC	f	f
697	SULTHIAME	f	f
698	SUMATRIPTAN	f	f
699	SUMATRIPTAN SUCCINATE	f	f
700	SUNSCREENS	f	f
701	TACROLIMUS	f	f
702	TAMOXIFEN CITRATE	f	f
703	TAMSULOSIN HYDROCHLORIDE	f	f
704	TAPES-NON-WOVEN RETENTION (POLYACRYLATE)	f	f
705	TAPES-PLASTER ADHESIVE ELASTIC	f	f
662	SENEGA and AMMONIA	f	t
706	TAPES-PLASTER ADHESIVE HYPOALLERGENIC	f	f
707	TELMISARTAN	f	f
708	TEMAZEPAM	f	f
709	TEMOZOLOMIDE	f	f
710	TENOXICAM	f	f
711	TERAZOSIN HYDROCHLORIDE	f	f
712	TERBINAFINE	f	f
713	TERBINAFINE HYDROCHLORIDE	f	f
714	TERBUTALINE SULFATE	f	f
715	TESTOSTERONE	f	f
716	TESTOSTERONE ENANTHATE	f	f
717	TESTOSTERONE ESTERS	f	f
719	TETANUS VACCINE, ADSORBED	f	f
720	TETRABENAZINE	f	f
721	TETRACOSACTRIN	f	f
722	TETRACYCLINE HYDROCHLORIDE	f	f
723	TETRACYCLINE HYDROCHLORIDE (BUFFERED)	f	f
724	THEOPHYLLINE	f	f
725	THIABENDAZOLE	f	f
726	THIAMINE HYDROCHLORIDE	f	f
727	THIOGUANINE	f	f
728	THIORIDAZINE	f	f
729	THIORIDAZINE HYDROCHLORIDE	f	f
730	THIOTEPA	f	f
731	THYROXINE SODIUM	f	f
732	TIAGABINE HYDROCHLORIDE	f	f
733	TIAPROFENIC ACID	f	f
735	TICLOPIDINE HYDROCHLORIDE	f	f
736	TILUDRONATE DISODIUM	f	f
737	TIMOLOL MALEATE	f	f
739	TINIDAZOLE	f	f
740	TIROFIBAN HYDROCHLORIDE	f	f
741	TOBRAMYCIN	f	f
742	TOBRAMYCIN SULFATE	f	f
743	TOLBUTAMIDE	f	f
744	TOLNAFTATE	f	f
745	TOPIRAMATE	f	f
746	TOPOTECAN HYDROCHLORIDE	f	f
747	TOREMIFENE CITRATE	f	f
748	TRAMADOL HYDROCHLORIDE	f	f
749	TRANDOLAPRIL	f	f
750	TRANEXAMIC ACID	f	f
751	TRANYLCYPROMINE SULFATE	f	f
752	TRIAMCINOLONE ACETONIDE	f	f
754	TRIFLUOPERAZINE HYDROCHLORIDE	f	f
755	TRIGLYCERIDES, MEDIUM CHAIN	f	f
757	TRIGLYCERIDES-MEDIUM CHAIN, FORMULA	f	f
758	TRIMETHOPRIM	f	f
760	TROPISETRON HYDROCHLORIDE	f	f
761	UREA	f	f
762	UROFOLLITROPHIN (Highly purified)	f	f
763	URSODEOXYCHOLIC ACID	f	f
764	VALACICLOVIR HYDROCHLORIDE	f	f
765	VANCOMYCIN	f	f
766	VENLAFAXINE HYDROCHLORIDE	f	f
767	VERAPAMIL HYDROCHLORIDE	f	f
768	VIGABATRIN	f	f
769	VINBLASTINE SULFATE	f	f
770	VINCRISTINE SULFATE	f	f
771	VINORELBINE TARTRATE	f	f
772	VITAMIN B GROUP COMPLEX	f	f
773	WARFARIN SODIUM	f	f
774	WATER FOR INJECTIONS, STERILISED	f	f
775	WOOL ALCOHOLS	f	f
776	ZALCITABINE	f	f
777	ZIDOVUDINE	f	f
778	ZINC OXIDE	f	f
780	ZINC PYRITHIONE	f	f
782	ZOLMITRIPTAN	f	f
783	ZOPICLONE	f	f
92	BISMUTH SUBCITRATE and METRONIDAZOLE and TETRACYCLINE HYDROC	f	t
204	DIPHTHERIA and TETANUS VACCINE, ADSORBED	f	t
205	DIPHTHERIA and TETANUS VACCINE, ADSORBED, DILUTED FOR ADULT 	f	t
211	DISODIUM ETIDRONATE and CALCIUM CARBONATE	f	t
332	GLUCOSE and KETONE INDICATOR-URINE	f	t
530	OESTRADIOL and MEDROXYPROGESTERONE ACETATE	f	t
734	TICARCILLIN with CLAVULANIC ACID	f	t
539	OESTROGENS-CONJUGATED and MEDROXYPROGESTERONE ACETATE	f	t
546	OMEPRAZOLE and CLARITHROMYCIN and AMOXYCILLIN	f	t
548	OMEPRAZOLE MAGNESIUM and CLARITHROMYCIN and AMOXYCILLIN	f	t
549	OMEPRAZOLE MAGNESIUM and METRONIDAZOLE and AMOXYCILLIN	f	t
635	RANITIDINE BISMUTH CITRATE and CLARITHROMYCIN and AMOXYCILLI	f	t
639	RIBAVIRIN and INTERFERON ALFA-2b	f	t
25	AMINO ACID FORMULA without PHENYLALANINE	f	f
33	AMINO ACIDS-SYNTHETIC, FORMULA	f	f
24	AMINO ACID FORMULA without METHIONINE, THREONINE and VALINE 	f	f
26	AMINO ACID FORMULA without PHENYLALANINE, TYROSINE and METHI	f	f
27	AMINO ACID FORMULA with VITAMINS and MINERALS without METHIO	f	f
28	AMINO ACID FORMULA with VITAMINS and MINERALS without METHIO	f	f
29	AMINO ACID FORMULA with VITAMINS and MINERALS without PHENYL	f	f
30	AMINO ACID FORMULA with VITAMINS and MINERALS without PHENYL	f	f
31	AMINO ACID FORMULA with VITAMINS and MINERALS without VALINE	f	f
32	AMINO ACID FORMULA with VITAMINS, MINERALS and LONG CHAIN PO	f	f
118	CARBOHYDRATE, FAT, VITAMINS, MINERALS and TRACE ELEMENTS	f	f
19	ALUMINIUM HYDROXIDE with MAGNESIUM HYDROXIDE	f	t
41	AMOXYCILLIN with CLAVULANIC ACID	f	t
45	ANTAZOLINE with NAPHAZOLINE	f	t
82	BETAMETHASONE ACETATE with BETAMETHASONE SODIUM PHOSPHATE	f	t
109	CALCIUM CARBONATE with GLYCINE	f	t
125	CATIONIC CONDITIONER with PANTHENOL	f	t
162	CODEINE PHOSPHATE with ASPIRIN	f	t
163	CODEINE PHOSPHATE with PARACETAMOL	f	t
185	DEXTRAN 40 with GLUCOSE	f	t
186	DEXTRAN 40 with SODIUM CHLORIDE	f	t
187	DEXTRAN 70 with SODIUM CHLORIDE	f	t
193	DICLOFENAC SODIUM with MISOPROSTOL	f	t
201	DIMETHICONE with GLYCEROL	f	t
203	DIPHENOXYLATE HYDROCHLORIDE with ATROPINE SULFATE	f	t
209	DIPYRIDAMOLE with ASPIRIN	f	t
216	DOCUSATE SODIUM with BISACODYL	f	t
217	DOCUSATE SODIUM with SENNA	f	t
261	ENALAPRIL MALEATE with HYDROCHLOROTHIAZIDE	f	t
269	ERGOTAMINE TARTRATE with CAFFEINE	f	t
285	FERROUS SULFATE DRIED with FOLIC ACID	f	t
311	FOSINOPRIL SODIUM with HYDROCHLOROTHIAZIDE	f	t
371	HYDROCHLOROTHIAZIDE with AMILORIDE HYDROCHLORIDE	f	t
372	HYDROCHLOROTHIAZIDE with TRIAMTERENE	f	t
376	HYDROCORTISONE with CINCHOCAINE HYDROCHLORIDE	f	t
385	HYPROMELLOSE with DEXTRAN	f	t
411	IPRATROPIUM BROMIDE with SALBUTAMOL SULFATE	f	t
413	IRBESARTAN with HYDROCHLOROTHIAZIDE	f	t
428	LAMIVUDINE with ZIDOVUDINE	f	t
439	LEVODOPA with BENSERAZIDE	f	t
440	LEVODOPA with CARBIDOPA	f	t
442	LEVONORGESTREL with ETHINYLOESTRADIOL	f	t
444	LIGNOCAINE HYDROCHLORIDE with CARBOXYMETHYLCELLULOSE	f	t
503	NAPHAZOLINE HYDROCHLORIDE with PHENIRAMINE MALEATE	f	t
511	NEOMYCIN UNDECENOATE with BACITRACIN ZINC	f	t
522	NORETHISTERONE with ETHINYLOESTRADIOL	f	t
523	NORETHISTERONE with MESTRANOL	f	t
536	OESTRADIOL with NORETHISTERONE ACETATE	f	t
541	OESTROGENS-CONJUGATED with MEDROXYPROGESTERONE ACETATE	f	t
571	PERINDOPRIL ERBUMINE with INDAPAMIDE HEMIHYDRATE	f	t
585	PINE TAR with CADE OIL, COAL TAR SOLUTION, ARACHIS OIL EXTRA	f	t
586	PINE TAR with TRIETHANOLAMINE LAURYL SULFATE	f	t
596	POLYVINYL ALCOHOL with POVIDONE	f	t
602	PREDNISOLONE ACETATE with PHENYLEPHRINE HYDROCHLORIDE	f	t
618	PROTEIN HYDROLYSATE FORMULA with MEDIUM CHAIN TRIGLYCERIDES	f	t
622	PSYLLIUM HYDROPHILIC MUCILLOID with HIGH AMYLOSE MAIZE STARC	f	t
652	SALICYLIC ACID with BENZALKONIUM CHLORIDE, ALCOHOL, COAL TAR	f	t
654	SALICYLIC ACID with PODOPHYLLIN RESIN	f	t
657	SALMETEROL XINAFOATE with FLUTICASONE PROPIONATE	f	t
666	SILVER SULFADIAZINE with CHLORHEXIDINE GLUCONATE	f	t
676	SODIUM CHLORIDE with GLUCOSE	f	t
690	STERCULIA with FRANGULA BARK	f	t
738	TIMOLOL MALEATE with PILOCARPINE HYDROCHLORIDE	f	t
753	TRIAMCINOLONE ACETONIDE with NEOMYCIN SULFATE, GRAMICIDIN an	f	t
759	TRIMETHOPRIM with SULFAMETHOXAZOLE	f	t
781	ZINC SULFATE with PHENYLEPHRINE HYDROCHLORIDE	f	t
12	ALLANTOIN with GLYCEROL and ICHTHAMMOL	f	t
252	DRESSING with CADEXOMER IODINE	f	f
13	ALLANTOIN with SULFUR, PHENOL, COAL TAR SOLUTION and MENTHOL	f	t
20	ALUMINIUM HYDROXIDE with MAGNESIUM HYDROXIDE and SIMETHICONE	f	t
21	ALUMINIUM HYDROXIDE with MAGNESIUM TRISILICATE and MAGNESIUM	f	t
123	CARMELLOSE SODIUM with PECTIN and GELATIN	f	t
183	DEXAMETHASONE with FRAMYCETIN SULFATE and GRAMICIDIN	f	t
190	DICHLOROBENZENE with CHLORBUTOL and TURPENTINE OIL	f	t
274	ESSENTIAL AMINO ACIDS FORMULA with MINERALS and VITAMIN C	f	t
368	HUMAN MENOPAUSAL GONADOTROPHIN standardised with HUMAN CHORI	f	t
531	OESTRADIOL and OESTRADIOL with DYDROGESTERONE	f	t
532	OESTRADIOL and OESTRADIOL with NORETHISTERONE ACETATE	f	t
534	OESTRADIOL VALERATE and OESTRADIOL VALERATE with CYPROTERONE	f	t
535	OESTRADIOL VALERATE and OESTRADIOL VALERATE with MEDROXYPROG	f	t
540	OESTROGENS-CONJUGATED and OESTROGENS-CONJUGATED with MEDROXY	f	t
593	POLYMYXIN B SULFATE with BACITRACIN and NEOMYCIN SULFATE	f	t
594	POLYMYXIN B SULFATE with NEOMYCIN SULFATE and GRAMICIDIN	f	t
640	RICINOLEIC ACID with ACETIC ACID and HYDROXYQUINOLINE SULFAT	f	t
651	SALICYLIC ACID with BENZALKONIUM CHLORIDE, ALCOHOL and POLYO	f	t
653	SALICYLIC ACID with COAL TAR SOLUTION, PINE TAR and UNDECYLE	f	t
670	SODIUM ALGINATE with CALCIUM CARBONATE and SODIUM BICARBONAT	f	t
685	SORBITOL with SODIUM CITRATE and SODIUM LAURYL SULFOACETATE	f	t
756	TRIGLYCERIDES, MEDIUM CHAIN and LONG CHAIN with GLUCOSE POLY	f	t
779	ZINC OXIDE with STARCH and CHLORPHENESIN	f	t
318	GAUZE and COTTON TISSUE (COMBINE ROLL)	f	f
228	DRESSING-ACTIVATED CHARCOAL (MALODOROUS WOUND)	f	f
229	DRESSING-ALGINATE (CAVITY WOUND)	f	f
230	DRESSING-ALGINATE (SUPERFICIAL WOUND)	f	f
231	DRESSING-FILM	f	f
232	DRESSING-FILM ISLAND	f	f
233	DRESSING-FOAM-HEAVY EXUDATE	f	f
234	DRESSING-FOAM-LIGHT EXUDATE	f	f
235	DRESSING-FOAM-MODERATE EXUDATE	f	f
237	DRESSING-GAUZE (ABSORBENT PAD)	f	f
238	DRESSING-GAUZE-EYE PAD	f	f
239	DRESSING-GAUZE-PARAFFIN	f	f
241	DRESSING-GAUZE-POVIDONE-IODINE PAD	f	f
242	DRESSING-HYDROACTIVE (CAVITY WOUND)	f	f
243	DRESSING-HYDROACTIVE (SUPERFICIAL WOUND-HIGH EXUDATE)	f	f
244	DRESSING-HYDROACTIVE (SUPERFICIAL WOUND-LIGHT EXUDATE)	f	f
245	DRESSING-HYDROACTIVE (SUPERFICIAL WOUND-MODERATE EXUDATE)	f	f
246	DRESSING-HYDROCOLLOID (CAVITY WOUND)	f	f
247	DRESSING-HYDROCOLLOID (SUPERFICIAL WOUND-LIGHT EXUDATE)	f	f
248	DRESSING-HYDROCOLLOID (SUPERFICIAL WOUND-MODERATE EXUDATE)	f	f
249	DRESSING-HYDROGEL-AMORPHOUS	f	f
250	DRESSING-HYDROGEL-SHEET	f	f
251	DRESSING-NON-ADHERENT	f	f
236	DRESSING-FOAM with CHARCOAL (MALODOROUS WOUND)	f	f
240	DRESSING-GAUZE-PARAFFIN with CHLORHEXIDINE ACETATE	f	f
298	FLUPENTHIXOL DECANOATE	f	t
299	FLUPHENAZINE DECANOATE	f	t
362	HALOPERIDOL DECANOATE	f	t
501	NANDROLONE DECANOATE	f	t
718	TESTOSTERONE UNDECANOATE	f	t
784	ZUCLOPENTHIXOL DECANOATE	f	t
174	DALTEPARIN SODIUM	f	f
17	ALTEPLASE	f	f
18	ALTRETAMINE	f	f
\.
