// File: CosEventComm.idl
// This file contains an abbreviated set of definitions, only those
// which are required by DsObservationAccess. 
// Use this file only when the standard CosEvent module
// is not available nor desired for compilation and runtime.

#ifndef _COS_EVENT_COMM_IDL_
#define _COS_EVENT_COMM_IDL_

#pragma prefix "omg.org"

module CosEventComm {
	exception Disconnected{};

	interface PushConsumer {
		void push (in any data) raises(Disconnected);
		void disconnect_push_consumer(); 
	};

    interface PushSupplier {
		void disconnect_push_supplier();
	};
};
#endif /* ifndef _COS_EVENT_COMM_IDL_ */
