#pragma prefix "omg.org" 
module CosPropertyService
{
   // Data types

   /** A PropertyName is a string. */
   typedef string PropertyName;

   /** A Property is a two tuple of (property_name, property_value). */
   struct Property
   {
      PropertyName property_name;
      any property_value;
   };
 /** Properties is a sequence of Property's. */
   typedef sequence <Property> Properties;
};
