// File: NamingAuthority.idl
// This file contains an abbreviated set of definitions, only those
// which are required by DsObservationAccess. 
// Use this file only when the standard Person Identification Service (PIDS)
// is not available nor desired for compilation and runtime.


#ifndef _NAMING_AUTHORITY_IDL_
#define _NAMING_AUTHORITY_IDL_

#pragma prefix "omg.org"

module NamingAuthority
{
	enum RegistrationAuthority {
		OTHER,
		ISO,
		DNS,
		IDL,
		DCE };

	typedef string NamingEntity;

	struct AuthorityId {
		RegistrationAuthority   authority;
		NamingEntity            naming_entity;
	};
	typedef string AuthorityIdStr;

	typedef string LocalName;
	struct QualifiedName {
		AuthorityId authority_id;
		LocalName local_name;
	};
	typedef string QualifiedNameStr;

};

#endif // _NAMING_AUTHORITY_IDL_


