# -*- coding: UTF-8 -*-
#
# generated by wxGlade
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class wxg2ButtonQuestionDlg(wx.Dialog):
	def __init__(self, *args, **kwds):
		# begin wxGlade: wxg2ButtonQuestionDlg.__init__
		kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE | wx.MAXIMIZE_BOX | wx.MINIMIZE_BOX | wx.RESIZE_BORDER | wx.STAY_ON_TOP
		wx.Dialog.__init__(self, *args, **kwds)
		self.SetTitle(_("Put caption here."))

		__szr_main = wx.BoxSizer(wx.VERTICAL)

		self._LBL_question = wx.StaticText(self, wx.ID_ANY, _("Put question here."))
		__szr_main.Add(self._LBL_question, 1, wx.ALL | wx.EXPAND, 10)

		top_bottom_separator = wx.StaticLine(self, wx.ID_ANY)
		__szr_main.Add(top_bottom_separator, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 5)

		self._CHBOX_dont_ask_again = wx.CheckBox(self, wx.ID_ANY, _("Remember and don't ask again."))
		self._CHBOX_dont_ask_again.SetToolTip(_("Check this if you want GNUmed to remember your decision and not ask you again."))
		__szr_main.Add(self._CHBOX_dont_ask_again, 0, wx.LEFT | wx.RIGHT | wx.TOP, 10)

		__szr_buttons = wx.BoxSizer(wx.HORIZONTAL)
		__szr_main.Add(__szr_buttons, 0, wx.ALL | wx.EXPAND, 10)

		__szr_buttons.Add((20, 20), 1, wx.EXPAND, 0)

		self._BTN_1 = wx.Button(self, wx.ID_YES, _("Yes"))
		__szr_buttons.Add(self._BTN_1, 0, wx.EXPAND, 3)

		__szr_buttons.Add((20, 20), 1, wx.EXPAND, 0)

		self._BTN_2 = wx.Button(self, wx.ID_NO, _("No"))
		__szr_buttons.Add(self._BTN_2, 0, wx.EXPAND, 0)

		__szr_buttons.Add((20, 20), 1, wx.EXPAND, 0)

		self.SetSizer(__szr_main)
		__szr_main.Fit(self)

		self.Layout()
		self.Centre()

		self.Bind(wx.EVT_BUTTON, self._on_BTN_1_pressed, self._BTN_1)
		self.Bind(wx.EVT_BUTTON, self._on_BTN_2_pressed, self._BTN_2)
		# end wxGlade

	def _on_BTN_1_pressed(self, event):  # wxGlade: wxg2ButtonQuestionDlg.<event_handler>
		print("Event handler '_on_BTN_1_pressed' not implemented!")
		event.Skip()

	def _on_BTN_2_pressed(self, event):  # wxGlade: wxg2ButtonQuestionDlg.<event_handler>
		print("Event handler '_on_BTN_2_pressed' not implemented!")
		event.Skip()

# end of class wxg2ButtonQuestionDlg
