#!/usr/bin/env python
# -*- coding: ISO-8859-15 -*-
# generated by wxGlade 0.4.1 on Tue Apr 24 19:23:25 2007

import wx

class wxg3ButtonQuestionDlg(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: wxg3ButtonQuestionDlg.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.MAXIMIZE_BOX|wx.MINIMIZE_BOX|wx.THICK_FRAME|wx.STAY_ON_TOP
        wx.Dialog.__init__(self, *args, **kwds)
        self._LBL_question = wx.StaticText(self, -1, _("Put question here."))
        self._BTN_1 = wx.Button(self, wx.ID_YES, _("Yes"))
        self._BTN_2 = wx.Button(self, wx.ID_NO, _("No"))
        self._BTN_3 = wx.Button(self, wx.ID_CANCEL, _("Cancel"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self._on_BTN_1_pressed, id=wx.ID_YES)
        self.Bind(wx.EVT_BUTTON, self._on_BTN_2_pressed, id=wx.ID_NO)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxg3ButtonQuestionDlg.__set_properties
        self.SetTitle(_("Put caption here."))
        self._BTN_1.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxg3ButtonQuestionDlg.__do_layout
        __szr_main = wx.BoxSizer(wx.VERTICAL)
        __szr_buttons = wx.BoxSizer(wx.HORIZONTAL)
        __szr_main.Add(self._LBL_question, 1, wx.ALL|wx.EXPAND, 10)
        __szr_buttons.Add(self._BTN_1, 0, wx.RIGHT|wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 3)
        __szr_buttons.Add(self._BTN_2, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __szr_buttons.Add((20, 20), 1, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __szr_buttons.Add(self._BTN_3, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __szr_main.Add(__szr_buttons, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 5)
        self.SetAutoLayout(True)
        self.SetSizer(__szr_main)
        __szr_main.Fit(self)
        __szr_main.SetSizeHints(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def _on_BTN_1_pressed(self, event): # wxGlade: wxg3ButtonQuestionDlg.<event_handler>
        print "Event handler `_on_BTN_1_pressed' not implemented!"
        event.Skip()

    def _on_BTN_2_pressed(self, event): # wxGlade: wxg3ButtonQuestionDlg.<event_handler>
        print "Event handler `_on_BTN_2_pressed' not implemented!"
        event.Skip()

# end of class wxg3ButtonQuestionDlg


