#!/usr/bin/env python
# -*- coding: ISO-8859-15 -*-
# generated by wxGlade 0.4.1 on Sat Mar 10 13:28:37 2007

import wx

class wxgAllergyEditAreaPnl(wx.ScrolledWindow):
    def __init__(self, *args, **kwds):

        from Gnumed.wxpython import gmPhraseWheel, gmDateTimeInput

        # begin wxGlade: wxgAllergyEditAreaPnl.__init__
        kwds["style"] = wx.NO_BORDER|wx.TAB_TRAVERSAL
        wx.ScrolledWindow.__init__(self, *args, **kwds)
        self._DPRW_date_noted = gmDateTimeInput.cFuzzyTimestampInput(self, -1, "", style=wx.NO_BORDER)
        self._PRW_trigger = gmPhraseWheel.cPhraseWheel(self, -1, "", style=wx.NO_BORDER)
        self._TCTRL_brand_name = wx.TextCtrl(self, -1, "", style=wx.NO_BORDER)
        self._TCTRL_generic = wx.TextCtrl(self, -1, "", style=wx.NO_BORDER)
        self._ChBOX_generic_specific = wx.CheckBox(self, -1, _("&Tolerates others in class"))
        self._TCTRL_atc_classes = wx.TextCtrl(self, -1, "", style=wx.NO_BORDER)
        self._PRW_reaction = gmPhraseWheel.cPhraseWheel(self, -1, "", style=wx.NO_BORDER)
        self._RBTN_type_allergy = wx.RadioButton(self, -1, _("&Allergy"), style=wx.RB_GROUP)
        self._RBTN_type_sensitivity = wx.RadioButton(self, -1, _("&Sensitivity"))
        self._ChBOX_definite = wx.CheckBox(self, -1, _("&Definite"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxgAllergyEditAreaPnl.__set_properties
        self.SetScrollRate(10, 10)
        self._DPRW_date_noted.SetToolTipString(_("Since when do we know about this allergy. Mostly \"today\"."))
        self._PRW_trigger.SetToolTipString(_("What is reported to be the trigger for the reaction. Can be\n- a drug (brand name, generic, constrast media, ...)\n- a chemical (household, job related)\n- an animal (cat fur, lice, ...)\n- a metal (CrNi, ...)\n- a foodstuff (lactose, ...)\n- a type of pollen (birch, ...)\n- ..."))
        self._TCTRL_brand_name.SetToolTipString(_("Brand name if a drug is entered as the trigger."))
        self._TCTRL_brand_name.Enable(False)
        self._TCTRL_generic.SetToolTipString(_("Brand name if a drug is entered as the trigger."))
        self._TCTRL_generic.Enable(False)
        self._ChBOX_generic_specific.SetToolTipString(_("Check if this reaction applies to this drug/generic only, not the entire drug class."))
        self._TCTRL_atc_classes.SetToolTipString(_("Displays drug classe(s) along with their ATC code."))
        self._TCTRL_atc_classes.Enable(False)
        self._PRW_reaction.SetToolTipString(_("Document signs and symptoms. If reaction is to a drug also document time of onset after drug administration (<24h, 24-72h, >72h)."))
        self._RBTN_type_allergy.SetToolTipString(_("Select this if the reaction is an allergy."))
        self._RBTN_type_allergy.SetValue(1)
        self._RBTN_type_sensitivity.SetToolTipString(_("Select this if the reaction is a sensitivity."))
        self._ChBOX_definite.SetToolTipString(_("Check this if this allergy/intolerance is known to exist for sure as opposed to suspected."))
        self._ChBOX_definite.SetValue(1)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxgAllergyEditAreaPnl.__do_layout
        _gszr_main = wx.FlexGridSizer(7, 2, 1, 3)
        __szr_reaction_type = wx.BoxSizer(wx.HORIZONTAL)
        __szr_generic = wx.BoxSizer(wx.HORIZONTAL)
        __lbl_date_noted = wx.StaticText(self, -1, _("Date Noted"))
        _gszr_main.Add(__lbl_date_noted, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        _gszr_main.Add(self._DPRW_date_noted, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __lbl_trigger = wx.StaticText(self, -1, _("Trigger"))
        _gszr_main.Add(__lbl_trigger, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        _gszr_main.Add(self._PRW_trigger, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __lbl_brand_name = wx.StaticText(self, -1, _("Brand Name"))
        _gszr_main.Add(__lbl_brand_name, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        _gszr_main.Add(self._TCTRL_brand_name, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __lbl_generic = wx.StaticText(self, -1, _("Generics"))
        _gszr_main.Add(__lbl_generic, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        __szr_generic.Add(self._TCTRL_generic, 1, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __szr_generic.Add(self._ChBOX_generic_specific, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        _gszr_main.Add(__szr_generic, 1, wx.EXPAND, 0)
        __lbl_atc_classes = wx.StaticText(self, -1, _("Drug Classes"))
        _gszr_main.Add(__lbl_atc_classes, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        _gszr_main.Add(self._TCTRL_atc_classes, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __lbl_reaction = wx.StaticText(self, -1, _("Reaction"))
        __lbl_reaction.SetToolTipString(_("Document signs and symptoms. If reaction is to a drug also document time of onset after drug administration (<24h, 24-72h, >72h)."))
        _gszr_main.Add(__lbl_reaction, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        _gszr_main.Add(self._PRW_reaction, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __lbl_reaction_type = wx.StaticText(self, -1, _("Reaction Type"))
        _gszr_main.Add(__lbl_reaction_type, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        __szr_reaction_type.Add(self._RBTN_type_allergy, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        __szr_reaction_type.Add(self._RBTN_type_sensitivity, 0, wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 15)
        __szr_reaction_type.Add(self._ChBOX_definite, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        _gszr_main.Add(__szr_reaction_type, 1, wx.EXPAND, 0)
        self.SetSizer(_gszr_main)
        _gszr_main.Fit(self)
        _gszr_main.AddGrowableCol(1)
        # end wxGlade

# end of class wxgAllergyEditAreaPnl


