#!/usr/bin/env python
# -*- coding: utf8 -*-
# generated by wxGlade 0.6.3 from "/home/ncq/Projekte/gm-git/gnumed/gnumed/client/wxg/wxgConsumableSubstanceEAPnl.wxg"

import wx

# begin wxGlade: extracode
# end wxGlade



class wxgConsumableSubstanceEAPnl(wx.ScrolledWindow):
    def __init__(self, *args, **kwds):

        from Gnumed.wxpython import gmMedicationWidgets

        # begin wxGlade: wxgConsumableSubstanceEAPnl.__init__
        kwds["style"] = wx.NO_BORDER|wx.TAB_TRAVERSAL
        wx.ScrolledWindow.__init__(self, *args, **kwds)
        self._TCTRL_substance = wx.TextCtrl(self, -1, "", style=wx.NO_BORDER)
        self._PRW_atc = gmMedicationWidgets.cATCPhraseWheel(self, -1, "", style=wx.NO_BORDER)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxgConsumableSubstanceEAPnl.__set_properties
        self.SetScrollRate(10, 10)
        self._TCTRL_substance.SetToolTipString(_("Enter the name of the consumable substance.\n\nExamples:\n- metoprolol\n- tobacco\n- alcohol\n- marihuana\n- aloe vera\n- ibuprofen"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxgConsumableSubstanceEAPnl.__do_layout
        _gszr_main = wx.FlexGridSizer(2, 2, 1, 3)
        __lbl_substance = wx.StaticText(self, -1, _("Substance"))
        __lbl_substance.SetForegroundColour(wx.Colour(255, 0, 0))
        _gszr_main.Add(__lbl_substance, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        _gszr_main.Add(self._TCTRL_substance, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __lbl_atc = wx.StaticText(self, -1, _("ATC code"))
        _gszr_main.Add(__lbl_atc, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        _gszr_main.Add(self._PRW_atc, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        self.SetSizer(_gszr_main)
        _gszr_main.Fit(self)
        _gszr_main.AddGrowableCol(1)
        # end wxGlade

# end of class wxgConsumableSubstanceEAPnl


