#!/usr/bin/env python
# -*- coding: ISO-8859-15 -*-
# generated by wxGlade 0.4cvs on Sat Jun 10 00:58:17 2006

import wx

class wxgEditStaffListDlg(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: wxgEditStaffListDlg.__init__
        kwds["style"] = wx.CAPTION|wx.RESIZE_BORDER|wx.CLOSE_BOX|wx.MAXIMIZE_BOX|wx.MINIMIZE_BOX|wx.THICK_FRAME|wx.STAY_ON_TOP
        wx.Dialog.__init__(self, *args, **kwds)
        self._LCTRL_staff = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.LC_ALIGN_LEFT|wx.LC_SINGLE_SEL|wx.LC_SORT_ASCENDING|wx.SUNKEN_BORDER|wx.NO_BORDER)
        self._btn_activate = wx.Button(self, -1, _("Activate"))
        self._btn_deactivate = wx.Button(self, -1, _("Deactivate"))
        self._btn_delete = wx.Button(self, -1, _("Delete"))
        self._btn_close = wx.Button(self, wx.ID_CANCEL, _("Close"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LIST_ITEM_DESELECTED, self._on_listitem_deselected, self._LCTRL_staff)
        self.Bind(wx.EVT_LIST_ITEM_SELECTED, self._on_listitem_selected, self._LCTRL_staff)
        self.Bind(wx.EVT_BUTTON, self._on_activate_button_pressed, self._btn_activate)
        self.Bind(wx.EVT_BUTTON, self._on_deactivate_button_pressed, self._btn_deactivate)
        self.Bind(wx.EVT_BUTTON, self._on_delete_button_pressed, self._btn_delete)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxgEditStaffListDlg.__set_properties
        self.SetTitle(_("Edit staff list"))
        self.SetSize((700, 200))
        self._LCTRL_staff.SetToolTipString(_("The list of currently existing staff members."))
        self._LCTRL_staff.SetFocus()
        self._btn_activate.SetToolTipString(_("Activate selected employee."))
        self._btn_activate.Enable(False)
        self._btn_deactivate.SetToolTipString(_("Deactivate selected employee."))
        self._btn_deactivate.Enable(False)
        self._btn_delete.SetToolTipString(_("Entirely remove the staff entry (including the database account). This will only be possible if no patient data was aved under this account. If any data exists the entry will be deactivated only."))
        self._btn_delete.Enable(False)
        self._btn_close.SetToolTipString(_("Dismiss this dialog."))
        self._btn_close.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxgEditStaffListDlg.__do_layout
        __szr_main = wx.BoxSizer(wx.VERTICAL)
        __szr_buttons = wx.BoxSizer(wx.HORIZONTAL)
        __szr_main.Add(self._LCTRL_staff, 1, wx.EXPAND, 0)
        __szr_buttons.Add(self._btn_activate, 0, 0, 0)
        __szr_buttons.Add(self._btn_deactivate, 0, 0, 0)
        __szr_buttons.Add(self._btn_delete, 0, 0, 0)
        __szr_buttons.Add((20, 20), 1, wx.EXPAND, 0)
        __szr_buttons.Add(self._btn_close, 0, 0, 0)
        __szr_main.Add(__szr_buttons, 0, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(__szr_main)
        self.Layout()
        self.Centre()
        # end wxGlade

    def _on_listitem_deselected(self, event): # wxGlade: wxgEditStaffListDlg.<event_handler>
        print "Event handler `_on_listitem_deselected' not implemented!"
        event.Skip()

    def _on_listitem_selected(self, event): # wxGlade: wxgEditStaffListDlg.<event_handler>
        print "Event handler `_on_listitem_selected' not implemented!"
        event.Skip()

    def _on_activate_button_pressed(self, event): # wxGlade: wxgEditStaffListDlg.<event_handler>
        print "Event handler `_on_activate_button_pressed' not implemented!"
        event.Skip()

    def _on_deactivate_button_pressed(self, event): # wxGlade: wxgEditStaffListDlg.<event_handler>
        print "Event handler `_on_deactivate_button_pressed' not implemented!"
        event.Skip()

    def _on_delete_button_pressed(self, event): # wxGlade: wxgEditStaffListDlg.<event_handler>
        print "Event handler `_on_delete_button_pressed' not implemented!"
        event.Skip()

# end of class wxgEditStaffListDlg


