#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
from Gnumed.wxpython.gmEMRTimelineWidgets import cEMRTimelinePnl
# end wxGlade


class wxgEMRTimelinePluginPnl(wx.ScrolledWindow):
	def __init__(self, *args, **kwds):
		# begin wxGlade: wxgEMRTimelinePluginPnl.__init__
		kwds["style"] = wx.NO_BORDER | wx.TAB_TRAVERSAL
		wx.ScrolledWindow.__init__(self, *args, **kwds)
		self._PNL_timeline = cEMRTimelinePnl(self, wx.ID_ANY, style=wx.NO_BORDER | wx.TAB_TRAVERSAL)
		self._BTN_refresh = wx.Button(self, wx.ID_REFRESH, "")
		self._BTN_save = wx.Button(self, wx.ID_SAVEAS, "")
		self._BTN_export_area = wx.Button(self, wx.ID_ANY, _("E&xport area"))
		self._BTN_print = wx.Button(self, wx.ID_PRINT, "")

		self.__set_properties()
		self.__do_layout()

		self.Bind(wx.EVT_BUTTON, self._on_refresh_button_pressed, self._BTN_refresh)
		self.Bind(wx.EVT_BUTTON, self._on_save_button_pressed, self._BTN_save)
		self.Bind(wx.EVT_BUTTON, self._on_export_area_button_pressed, self._BTN_export_area)
		self.Bind(wx.EVT_BUTTON, self._on_print_button_pressed, self._BTN_print)
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: wxgEMRTimelinePluginPnl.__set_properties
		self.SetScrollRate(10, 10)
		self._BTN_refresh.SetToolTipString(_("Refresh the timeline display."))
		self._BTN_save.SetToolTipString(_("Save timeline as SVG image."))
		self._BTN_export_area.SetToolTipString(_("Put timeline into export area."))
		self._BTN_print.SetToolTipString(_("Print timeline."))
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: wxgEMRTimelinePluginPnl.__do_layout
		__szr_main = wx.BoxSizer(wx.VERTICAL)
		__szr_buttons = wx.BoxSizer(wx.HORIZONTAL)
		__szr_main.Add(self._PNL_timeline, 1, wx.BOTTOM | wx.EXPAND | wx.ALIGN_CENTER_VERTICAL, 3)
		__szr_buttons.Add((20, 20), 1, wx.EXPAND | wx.ALIGN_CENTER_VERTICAL, 0)
		__szr_buttons.Add(self._BTN_refresh, 0, wx.RIGHT | wx.ALIGN_CENTER_VERTICAL, 3)
		__szr_buttons.Add(self._BTN_save, 0, wx.RIGHT | wx.ALIGN_CENTER_VERTICAL, 3)
		__szr_buttons.Add(self._BTN_export_area, 0, wx.RIGHT | wx.ALIGN_CENTER_VERTICAL, 3)
		__szr_buttons.Add(self._BTN_print, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		__szr_buttons.Add((20, 20), 1, wx.EXPAND | wx.ALIGN_CENTER_VERTICAL, 0)
		__szr_main.Add(__szr_buttons, 0, wx.EXPAND, 0)
		self.SetSizer(__szr_main)
		__szr_main.Fit(self)
		# end wxGlade

	def _on_refresh_button_pressed(self, event):  # wxGlade: wxgEMRTimelinePluginPnl.<event_handler>
		print "Event handler '_on_refresh_button_pressed' not implemented!"
		event.Skip()

	def _on_save_button_pressed(self, event):  # wxGlade: wxgEMRTimelinePluginPnl.<event_handler>
		print "Event handler '_on_save_button_pressed' not implemented!"
		event.Skip()

	def _on_export_area_button_pressed(self, event):  # wxGlade: wxgEMRTimelinePluginPnl.<event_handler>
		print "Event handler '_on_export_area_button_pressed' not implemented!"
		event.Skip()

	def _on_print_button_pressed(self, event):  # wxGlade: wxgEMRTimelinePluginPnl.<event_handler>
		print "Event handler '_on_print_button_pressed' not implemented!"
		event.Skip()

# end of class wxgEMRTimelinePluginPnl
