#!/usr/bin/env python
# -*- coding: ISO-8859-15 -*-
# generated by wxGlade 0.4cvs on Thu Jul  6 14:13:37 2006

import wx

class wxgEditDocumentTypesDlg(wx.Dialog):
    def __init__(self, *args, **kwds):

        from Gnumed.wxpython import gmMedDocWidgets

        # begin wxGlade: wxgEditDocumentTypesDlg.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.MAXIMIZE_BOX|wx.MINIMIZE_BOX|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self._PNL_edit_document_types = gmMedDocWidgets.cEditDocumentTypesPnl(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxgEditDocumentTypesDlg.__set_properties
        self.SetTitle(_("Edit Document Types"))
        self.SetSize((400, 400))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxgEditDocumentTypesDlg.__do_layout
        _szr_main = wx.BoxSizer(wx.VERTICAL)
        _szr_main.Add(self._PNL_edit_document_types, 1, wx.ALL|wx.EXPAND, 3)
        self.SetAutoLayout(True)
        self.SetSizer(_szr_main)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class wxgEditDocumentTypesDlg


