#!/usr/bin/env python
# -*- coding: utf8 -*-
# generated by wxGlade 0.6.3 from "/home/ncq/Projekte/gm-cvs/branches/HEAD/gnumed/gnumed/client/wxg/wxgEncounterTypeEditAreaPnl.wxg"

import wx

# begin wxGlade: extracode
# end wxGlade



class wxgEncounterTypeEditAreaPnl(wx.ScrolledWindow):
    def __init__(self, *args, **kwds):
        # begin wxGlade: wxgEncounterTypeEditAreaPnl.__init__
        kwds["style"] = wx.NO_BORDER|wx.TAB_TRAVERSAL
        wx.ScrolledWindow.__init__(self, *args, **kwds)
        self._TCTRL_l10n_name = wx.TextCtrl(self, -1, "", style=wx.NO_BORDER)
        self._TCTRL_name = wx.TextCtrl(self, -1, "", style=wx.NO_BORDER)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxgEncounterTypeEditAreaPnl.__set_properties
        self.SetScrollRate(10, 10)
        self._TCTRL_l10n_name.SetToolTipString(_("Required: The name for this encounter type in your local language."))
        self._TCTRL_name.SetToolTipString(_("Optional: The system-wide name for this encounter type. If you leave this empty the local name will be used.\n\nIt is useful to choose an English term but that is not mandatory. One advantage to using a system name is that different people can have the system name translated to their language and still use the same encounter type."))
        self._TCTRL_name.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxgEncounterTypeEditAreaPnl.__do_layout
        _gszr_main = wx.FlexGridSizer(3, 2, 1, 3)
        __lbl_l10n_name = wx.StaticText(self, -1, _("Local name"))
        __lbl_l10n_name.SetForegroundColour(wx.Colour(255, 0, 0))
        _gszr_main.Add(__lbl_l10n_name, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        _gszr_main.Add(self._TCTRL_l10n_name, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __lbl_name = wx.StaticText(self, -1, _("Name"))
        _gszr_main.Add(__lbl_name, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        _gszr_main.Add(self._TCTRL_name, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        self.SetSizer(_gszr_main)
        _gszr_main.Fit(self)
        _gszr_main.AddGrowableCol(1)
        # end wxGlade

# end of class wxgEncounterTypeEditAreaPnl


