#!/usr/bin/env python
# -*- coding: utf8 -*-
# generated by wxGlade 0.6.3 from "/home/ncq/Projekte/gm-cvs/branches/HEAD/gnumed/gnumed/client/wxg/wxgHospitalStayEditAreaPnl.wxg"

import wx

# begin wxGlade: extracode
# end wxGlade



class wxgHospitalStayEditAreaPnl(wx.Panel):
    def __init__(self, *args, **kwds):

        from Gnumed.wxpython.gmEMRStructWidgets import cEpisodeSelectionPhraseWheel
        from Gnumed.wxpython.gmPhraseWheel import cPhraseWheel

        # begin wxGlade: wxgHospitalStayEditAreaPnl.__init__
        kwds["style"] = wx.NO_BORDER|wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self._PRW_hospital = cPhraseWheel(self, -1, "", style=wx.NO_BORDER)
        self._DP_admission = wx.DatePickerCtrl(self, -1, style=wx.DP_DROPDOWN|wx.DP_SHOWCENTURY)
        self._DP_discharge = wx.DatePickerCtrl(self, -1, style=wx.DP_DROPDOWN|wx.DP_ALLOWNONE|wx.DP_SHOWCENTURY)
        self._PRW_episode = cEpisodeSelectionPhraseWheel(self, -1, "", style=wx.NO_BORDER)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxgHospitalStayEditAreaPnl.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxgHospitalStayEditAreaPnl.__do_layout
        _gszr_main = wx.FlexGridSizer(5, 2, 3, 5)
        __lbl_hospital = wx.StaticText(self, -1, _("Hospital"))
        _gszr_main.Add(__lbl_hospital, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        _gszr_main.Add(self._PRW_hospital, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __lbl_admission = wx.StaticText(self, -1, _("Admitted"))
        _gszr_main.Add(__lbl_admission, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        _gszr_main.Add(self._DP_admission, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        __lbl_discharge = wx.StaticText(self, -1, _("Discharged"))
        _gszr_main.Add(__lbl_discharge, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        _gszr_main.Add(self._DP_discharge, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        __lbl_episode = wx.StaticText(self, -1, _("Episode"))
        _gszr_main.Add(__lbl_episode, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        _gszr_main.Add(self._PRW_episode, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        self.SetSizer(_gszr_main)
        _gszr_main.Fit(self)
        _gszr_main.AddGrowableCol(1)
        # end wxGlade

# end of class wxgHospitalStayEditAreaPnl


