#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.1 from "/home/ncq/Projekte/gm-cvs/branches/HEAD/gnumed/gnumed/client/wxg/wxgMeasurementsReviewDlg.wxg"

import wx

# begin wxGlade: extracode
# end wxGlade



class wxgMeasurementsReviewDlg(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: wxgMeasurementsReviewDlg.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.MAXIMIZE_BOX|wx.MINIMIZE_BOX|wx.THICK_FRAME|wx.STAY_ON_TOP
        wx.Dialog.__init__(self, *args, **kwds)
        self._LBL_tests = wx.StaticText(self, -1, _("... test listing goes here ..."))
        self._CHBOX_abnormal = wx.CheckBox(self, -1, _("Technically &abnormal"))
        self._CHBOX_significant = wx.CheckBox(self, -1, _("Clinically &significant"))
        self._CHBOX_responsible = wx.CheckBox(self, -1, _("Take &responsibility"))
        self._BTN_sign_off = wx.Button(self, wx.ID_APPLY, "")
        self._BTN_cancel = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self._on_signoff_button_pressed, self._BTN_sign_off)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxgMeasurementsReviewDlg.__set_properties
        self.SetTitle(_("Reviewing test results"))
        self._CHBOX_abnormal.SetToolTipString(_("Check this if you consider the test result(s) to be technically abnormal."))
        self._CHBOX_abnormal.SetFocus()
        self._CHBOX_significant.SetToolTipString(_("Check this if you consider the test result(s) to be clinically significant."))
        self._CHBOX_responsible.SetToolTipString(_("Check this to take over responsibility for initiating action on these results."))
        self._BTN_sign_off.SetToolTipString(_("Sign-off test results and save review for all listed results."))
        self._BTN_cancel.SetToolTipString(_("Cancel and discard review, that is, do NOT sign off results."))
        self._BTN_cancel.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxgMeasurementsReviewDlg.__do_layout
        __szr_main = wx.BoxSizer(wx.VERTICAL)
        __szr_buttons = wx.BoxSizer(wx.HORIZONTAL)
        __szr_review = wx.BoxSizer(wx.HORIZONTAL)
        __msg_top = wx.StaticText(self, -1, _("This review applies to ALL test results listed  below!\n\nIf you want to change the scope of the review\nyou need to narrow or widen the selection of tests."), style=wx.ALIGN_CENTRE)
        __szr_main.Add(__msg_top, 0, wx.LEFT|wx.RIGHT|wx.TOP|wx.EXPAND, 5)
        __hline_atop_tests = wx.StaticLine(self, -1)
        __szr_main.Add(__hline_atop_tests, 0, wx.ALL|wx.EXPAND, 5)
        __szr_main.Add(self._LBL_tests, 1, wx.LEFT|wx.RIGHT|wx.EXPAND, 5)
        __hline_below_tests = wx.StaticLine(self, -1)
        __szr_main.Add(__hline_below_tests, 0, wx.ALL|wx.EXPAND, 5)
        __szr_review.Add(self._CHBOX_abnormal, 1, wx.RIGHT|wx.EXPAND, 3)
        __szr_review.Add(self._CHBOX_significant, 1, wx.LEFT|wx.RIGHT|wx.EXPAND, 3)
        __szr_review.Add(self._CHBOX_responsible, 1, wx.LEFT|wx.EXPAND, 3)
        __szr_main.Add(__szr_review, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 5)
        __szr_buttons.Add((20, 20), 2, wx.EXPAND, 5)
        __szr_buttons.Add(self._BTN_sign_off, 0, wx.EXPAND, 0)
        __szr_buttons.Add((20, 20), 1, wx.EXPAND, 5)
        __szr_buttons.Add(self._BTN_cancel, 0, wx.EXPAND, 0)
        __szr_buttons.Add((20, 20), 2, wx.EXPAND, 5)
        __szr_main.Add(__szr_buttons, 0, wx.ALL|wx.EXPAND, 5)
        self.SetSizer(__szr_main)
        __szr_main.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def _on_signoff_button_pressed(self, event): # wxGlade: wxgMeasurementsReviewDlg.<event_handler>
        print "Event handler `_on_signoff_button_pressed' not implemented!"
        event.Skip()

# end of class wxgMeasurementsReviewDlg


if __name__ == "__main__":
    import gettext
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    wxPanel = wxgMeasurementsReviewDlg(None, -1, "")
    app.SetTopWindow(wxPanel)
    wxPanel.Show()
    app.MainLoop()
