#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.1 from "/home/ncq/Projekte/gm-cvs/branches/HEAD/gnumed/gnumed/client/wxg/wxgMeasurementsPnl.wxg"

import wx
import wx.grid

# begin wxGlade: extracode
# end wxGlade



class wxgMeasurementsPnl(wx.ScrolledWindow):
    def __init__(self, *args, **kwds):

        from Gnumed.wxpython import gmMeasurementWidgets

        # begin wxGlade: wxgMeasurementsPnl.__init__
        kwds["style"] = wx.NO_BORDER|wx.TAB_TRAVERSAL
        wx.ScrolledWindow.__init__(self, *args, **kwds)
        self.data_grid = gmMeasurementWidgets.cMeasurementsGrid(self, -1, size=(1, 1))
        self._BTN_select_your_unsigned = wx.Button(self, -1, _("&My unsigned"))
        self._BTN_select_unsigned = wx.Button(self, -1, _("&All unsigned"))
        self._BTN_review = wx.Button(self, -1, _("&Sign selected  ... "))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self._on_select_my_unsigned_results_button_pressed, self._BTN_select_your_unsigned)
        self.Bind(wx.EVT_BUTTON, self._on_select_all_unsigned_results_button_pressed, self._BTN_select_unsigned)
        self.Bind(wx.EVT_BUTTON, self._on_review_button_pressed, self._BTN_review)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxgMeasurementsPnl.__set_properties
        self.SetScrollRate(10, 10)
        self._BTN_select_your_unsigned.SetToolTipString(_("Select those unsigned results for which you are responsible."))
        self._BTN_select_unsigned.SetToolTipString(_("Select all unsigned results, regardless of who is responsible for them."))
        self._BTN_review.SetToolTipString(_("Press this to batch-sign the selected measurements."))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxgMeasurementsPnl.__do_layout
        __szr_main = wx.BoxSizer(wx.VERTICAL)
        __szr_buttons = wx.BoxSizer(wx.HORIZONTAL)
        __szr_main.Add(self.data_grid, 1, wx.LEFT|wx.RIGHT|wx.TOP|wx.EXPAND, 5)
        __hline_buttons = wx.StaticLine(self, -1)
        __szr_main.Add(__hline_buttons, 0, wx.ALL|wx.EXPAND, 5)
        __lbl_select = wx.StaticText(self, -1, _("Select:"))
        __szr_buttons.Add(__lbl_select, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        __szr_buttons.Add(self._BTN_select_your_unsigned, 0, wx.LEFT|wx.EXPAND, 5)
        __szr_buttons.Add(self._BTN_select_unsigned, 0, wx.LEFT|wx.EXPAND, 5)
        __szr_buttons.Add((20, 20), 1, wx.EXPAND, 0)
        __szr_buttons.Add(self._BTN_review, 0, wx.EXPAND, 0)
        __szr_buttons.Add((20, 20), 1, wx.EXPAND, 0)
        __szr_main.Add(__szr_buttons, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 5)
        self.SetSizer(__szr_main)
        __szr_main.Fit(self)
        # end wxGlade

    def _on_select_unsigned_button_pressed(self, event): # wxGlade: wxgMeasurementsPnl.<event_handler>
        print "Event handler `_on_select_unsigned_button_pressed' not implemented!"
        event.Skip()

    def _on_select_your_unsigned_results_button_pressed(self, event): # wxGlade: wxgMeasurementsPnl.<event_handler>
        print "Event handler `_on_select_your_unsigned_results_button_pressed' not implemented!"
        event.Skip()

    def _on_review_button_pressed(self, event): # wxGlade: wxgMeasurementsPnl.<event_handler>
        print "Event handler `_on_review_button_pressed' not implemented!"
        event.Skip()

    def _on_select_my_unsigned_results_button_pressed(self, event): # wxGlade: wxgMeasurementsPnl.<event_handler>
        print "Event handler `_on_select_my_unsigned_results_button_pressed' not implemented"
        event.Skip()

    def _on_select_all_unsigned_results_button_pressed(self, event): # wxGlade: wxgMeasurementsPnl.<event_handler>
        print "Event handler `_on_select_all_unsigned_results_button_pressed' not implemented"
        event.Skip()

# end of class wxgMeasurementsPnl


