#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4.1 on Fri May 18 13:30:13 2007

import wx

class wxgMoveNarrativeDlg(wx.Dialog):
    def __init__(self, *args, **kwds):

        from Gnumed.wxpython import gmEMRStructWidgets

        # begin wxGlade: wxgMoveNarrativeDlg.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.MAXIMIZE_BOX|wx.MINIMIZE_BOX|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.LBL_source_episode = wx.StaticText(self, -1, "")
        self.LBL_encounter = wx.StaticText(self, -1, "")
        self.LBL_narrative = wx.StaticText(self, -1, "")
        self._PRW_episode_selector = gmEMRStructWidgets.cEpisodeSelectionPhraseWheel(self, -1, "", style=wx.NO_BORDER)
        self.__BTN_move = wx.Button(self, wx.ID_YES, "Move")
        self.__BTN_cancel = wx.Button(self, wx.ID_CANCEL, "Cancel")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self._on_move_button_pressed, id=wx.ID_YES)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxgMoveNarrativeDlg.__set_properties
        self.SetTitle("Moving narrative to another episode")
        self.SetSize((400, 400))
        self._PRW_episode_selector.SetToolTipString("Select the episode you want to move the narrative to.")
        self._PRW_episode_selector.SetFocus()
        self.__BTN_move.SetToolTipString("Move the narrative from the source to the target episode.")
        self.__BTN_cancel.SetToolTipString("Cancel moving the narrative entries and leave them where they are.")
        self.__BTN_cancel.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxgMoveNarrativeDlg.__do_layout
        __szr_main = wx.BoxSizer(wx.VERTICAL)
        __szr_buttons = wx.BoxSizer(wx.HORIZONTAL)
        __gszr_details = wx.FlexGridSizer(4, 2, 2, 5)
        __lbl_source_episode = wx.StaticText(self, -1, "Source episode")
        __lbl_source_episode.SetToolTipString("The episode the displayed narrative currently belongs to.")
        __gszr_details.Add(__lbl_source_episode, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __gszr_details.Add(self.LBL_source_episode, 1, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __lbl_encounter = wx.StaticText(self, -1, "Encounter")
        __gszr_details.Add(__lbl_encounter, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __gszr_details.Add(self.LBL_encounter, 1, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __lbl_narrative = wx.StaticText(self, -1, "Narrative")
        __gszr_details.Add(__lbl_narrative, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __gszr_details.Add(self.LBL_narrative, 1, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __lbl_target_episode = wx.StaticText(self, -1, "Target episode")
        __lbl_target_episode.SetToolTipString("The episode you want to move the displayed narrative to.")
        __gszr_details.Add(__lbl_target_episode, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __gszr_details.Add(self._PRW_episode_selector, 1, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __gszr_details.AddGrowableRow(2)
        __gszr_details.AddGrowableCol(1)
        __szr_main.Add(__gszr_details, 1, wx.ALL|wx.EXPAND, 5)
        __szr_buttons.Add((20, 20), 1, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        __szr_buttons.Add(self.__BTN_move, 0, wx.RIGHT|wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 5)
        __szr_buttons.Add(self.__BTN_cancel, 0, wx.LEFT|wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 5)
        __szr_buttons.Add((20, 20), 1, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        __szr_main.Add(__szr_buttons, 0, wx.ALL|wx.EXPAND, 5)
        self.SetAutoLayout(True)
        self.SetSizer(__szr_main)
        self.Layout()
        self.Centre()
        # end wxGlade

    def _on_move_button_pressed(self, event): # wxGlade: wxgMoveNarrativeDlg.<event_handler>
        print "Event handler `_on_move_button_pressed' not implemented"
        event.Skip()

# end of class wxgMoveNarrativeDlg


