#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.0
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
from Gnumed.wxpython.gmListWidgets import cReportListCtrl
# end wxGlade


class wxgMeasurementsByDayPnl(wx.Panel):
	def __init__(self, *args, **kwds):
		# begin wxGlade: wxgMeasurementsByDayPnl.__init__
		kwds["style"] = wx.TAB_TRAVERSAL
		wx.Panel.__init__(self, *args, **kwds)
		self._LCTRL_days = cReportListCtrl(self, wx.ID_ANY, style=wx.BORDER_NONE | wx.LC_REPORT)
		self._LCTRL_results = cReportListCtrl(self, wx.ID_ANY, style=wx.BORDER_NONE | wx.LC_REPORT)
		self._TCTRL_measurements = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.BORDER_NONE | wx.TE_AUTO_URL | wx.TE_MULTILINE | wx.TE_READONLY)

		self.__set_properties()
		self.__do_layout()

		self.Bind(wx.EVT_LIST_ITEM_SELECTED, self._on_day_selected, self._LCTRL_days)
		self.Bind(wx.EVT_LIST_ITEM_SELECTED, self._on_result_selected, self._LCTRL_results)
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: wxgMeasurementsByDayPnl.__set_properties
		self._TCTRL_measurements.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_BACKGROUND))
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: wxgMeasurementsByDayPnl.__do_layout
		__szr_main = wx.BoxSizer(wx.HORIZONTAL)
		__szr_main.Add(self._LCTRL_days, 2, wx.EXPAND | wx.RIGHT, 5)
		__szr_main.Add(self._LCTRL_results, 8, wx.EXPAND | wx.RIGHT, 5)
		__szr_main.Add(self._TCTRL_measurements, 10, wx.EXPAND, 0)
		self.SetSizer(__szr_main)
		__szr_main.Fit(self)
		self.Layout()
		# end wxGlade

	def _on_day_selected(self, event):  # wxGlade: wxgMeasurementsByDayPnl.<event_handler>
		print "Event handler '_on_day_selected' not implemented!"
		event.Skip()

	def _on_result_selected(self, event):  # wxGlade: wxgMeasurementsByDayPnl.<event_handler>
		print "Event handler '_on_result_selected' not implemented!"
		event.Skip()

# end of class wxgMeasurementsByDayPnl
