# -*- coding: UTF-8 -*-
#
# generated by wxGlade
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class wxgOrgUnitEAPnl(wx.ScrolledWindow):
	def __init__(self, *args, **kwds):
		# begin wxGlade: wxgOrgUnitEAPnl.__init__
		kwds["style"] = kwds.get("style", 0) | wx.BORDER_NONE | wx.TAB_TRAVERSAL
		wx.ScrolledWindow.__init__(self, *args, **kwds)
		from Gnumed.wxpython.gmOrganizationWidgets import cOrganizationPhraseWheel
		self._PRW_org = cOrganizationPhraseWheel(self, wx.ID_ANY, "")
		from Gnumed.wxpython.gmOrganizationWidgets import cOrgUnitPhraseWheel
		self._PRW_unit = cOrgUnitPhraseWheel(self, wx.ID_ANY, "")
		from Gnumed.wxpython.gmOrganizationWidgets import cOrgCategoryPhraseWheel
		self._PRW_category = cOrgCategoryPhraseWheel(self, wx.ID_ANY, "")

		self.__set_properties()
		self.__do_layout()
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: wxgOrgUnitEAPnl.__set_properties
		self.SetScrollRate(10, 10)
		self._PRW_org.SetToolTip(_("The organization this unit belongs to."))
		self._PRW_unit.SetToolTip(_("The name of the organizational unit."))
		self._PRW_category.SetToolTip(_("The category of the organizational unit."))
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: wxgOrgUnitEAPnl.__do_layout
		_gszr_main = wx.FlexGridSizer(3, 2, 1, 3)
		__lbl_org = wx.StaticText(self, wx.ID_ANY, _("Organization"))
		__lbl_org.SetForegroundColour(wx.Colour(255, 0, 0))
		_gszr_main.Add(__lbl_org, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		_gszr_main.Add(self._PRW_org, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)
		__lbl_unit = wx.StaticText(self, wx.ID_ANY, _("Unit"))
		__lbl_unit.SetForegroundColour(wx.Colour(255, 0, 0))
		_gszr_main.Add(__lbl_unit, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		_gszr_main.Add(self._PRW_unit, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)
		__lbl_category = wx.StaticText(self, wx.ID_ANY, _("Category"))
		_gszr_main.Add(__lbl_category, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		_gszr_main.Add(self._PRW_category, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)
		self.SetSizer(_gszr_main)
		_gszr_main.Fit(self)
		_gszr_main.AddGrowableCol(1)
		self.Layout()
		# end wxGlade

# end of class wxgOrgUnitEAPnl
