#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 from "/home/ncq/Projekte/gm-cvs/branches/HEAD/gnumed/gnumed/client/wxg/wxgProvinceEAPnl.wxg"

import wx

# begin wxGlade: extracode
# end wxGlade



class wxgProvinceEAPnl(wx.ScrolledWindow):
    def __init__(self, *args, **kwds):

        from Gnumed.wxpython import gmAddressWidgets

        # begin wxGlade: wxgProvinceEAPnl.__init__
        kwds["style"] = wx.NO_BORDER|wx.TAB_TRAVERSAL
        wx.ScrolledWindow.__init__(self, *args, **kwds)
        self._PRW_region = gmAddressWidgets.cStateSelectionPhraseWheel(self, -1, "", style=wx.NO_BORDER)
        self._TCTRL_code = wx.TextCtrl(self, -1, "", style=wx.NO_BORDER)
        self._PRW_country = gmAddressWidgets.cCountryPhraseWheel(self, -1, "", style=wx.NO_BORDER)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxgProvinceEAPnl.__set_properties
        self.SetScrollRate(10, 10)
        self._TCTRL_code.SetToolTipString(_("A code for this region."))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxgProvinceEAPnl.__do_layout
        _gszr_main = wx.FlexGridSizer(3, 2, 1, 3)
        __szr_code = wx.BoxSizer(wx.HORIZONTAL)
        __lbl_region = wx.StaticText(self, -1, _("Region"))
        _gszr_main.Add(__lbl_region, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        _gszr_main.Add(self._PRW_region, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __lbl_code = wx.StaticText(self, -1, _("Code"))
        _gszr_main.Add(__lbl_code, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        __szr_code.Add(self._TCTRL_code, 1, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        __szr_code.Add((20, 20), 1, wx.ALIGN_CENTER_VERTICAL, 0)
        _gszr_main.Add(__szr_code, 1, wx.EXPAND, 0)
        __lbl_country = wx.StaticText(self, -1, _("Country"))
        _gszr_main.Add(__lbl_country, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        _gszr_main.Add(self._PRW_country, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        self.SetSizer(_gszr_main)
        _gszr_main.Fit(self)
        _gszr_main.AddGrowableCol(1)
        # end wxGlade

# end of class wxgProvinceEAPnl


