#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.5 on Mon Nov 12 19:40:38 2007 from /home/ncq/Projekte/gm-cvs/branches/HEAD/gnumed/gnumed/client/wxg/wxgPersonContactsManagerPnl.wxg

import wx

class wxgPersonContactsManagerPnl(wx.ScrolledWindow):
    def __init__(self, *args, **kwds):

        from Gnumed.wxpython import gmDemographicsWidgets

        # begin wxGlade: wxgPersonContactsManagerPnl.__init__
        kwds["style"] = wx.NO_BORDER|wx.TAB_TRAVERSAL
        wx.ScrolledWindow.__init__(self, *args, **kwds)
        self._PNL_addresses = gmDemographicsWidgets.cPersonAddressesManagerPnl(self, -1, style=wx.NO_BORDER|wx.TAB_TRAVERSAL)
        self._PNL_comms = gmDemographicsWidgets.cPersonCommsManagerPnl(self, -1, style=wx.NO_BORDER|wx.TAB_TRAVERSAL)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxgPersonContactsManagerPnl.__set_properties
        self.SetFocus()
        self.SetScrollRate(10, 10)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxgPersonContactsManagerPnl.__do_layout
        __szr_main = wx.BoxSizer(wx.VERTICAL)
        __szr_main.Add(self._PNL_addresses, 1, wx.ALL|wx.EXPAND, 5)
        __szr_main.Add(self._PNL_comms, 1, wx.ALL|wx.EXPAND, 5)
        self.SetSizer(__szr_main)
        __szr_main.Fit(self)
        # end wxGlade

# end of class wxgPersonContactsManagerPnl


