#!/usr/bin/env python
# -*- coding: ISO-8859-15 -*-
# generated by wxGlade 0.4cvs on Sun May 28 10:51:48 2006

import wx

class wxgScrolledEMRTreePnl(wx.ScrolledWindow):
    def __init__(self, *args, **kwds):

        from Gnumed.wxpython import gmEMRBrowser

        # begin wxGlade: wxgScrolledEMRTreePnl.__init__
        kwds["style"] = wx.NO_BORDER|wx.TAB_TRAVERSAL
        wx.ScrolledWindow.__init__(self, *args, **kwds)
        self._emr_tree = gmEMRBrowser.cEMRTree(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxgScrolledEMRTreePnl.__set_properties
        self.SetScrollRate(10, 10)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxgScrolledEMRTreePnl.__do_layout
        __szr_main = wx.BoxSizer(wx.VERTICAL)
        __szr_main.Add(self._emr_tree, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(__szr_main)
        __szr_main.Fit(self)
        __szr_main.SetSizeHints(self)
        # end wxGlade

# end of class wxgScrolledEMRTreePnl


