#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 from "/home/ncq/Projekte/gm-cvs/branches/HEAD/gnumed/gnumed/client/wxg/wxgSoapNoteExpandoEditAreaPnl.wxg"

import wx

# begin wxGlade: extracode
# end wxGlade



class wxgSoapNoteExpandoEditAreaPnl(wx.ScrolledWindow):
    def __init__(self, *args, **kwds):

        from Gnumed.wxpython.gmNarrativeWidgets import cSoapLineTextCtrl
        from Gnumed.wxpython.gmNarrativeWidgets import cVisualSoapPresenterPnl

        # begin wxGlade: wxgSoapNoteExpandoEditAreaPnl.__init__
        kwds["style"] = wx.NO_BORDER|wx.TAB_TRAVERSAL
        wx.ScrolledWindow.__init__(self, *args, **kwds)
        self._TCTRL_Soap = cSoapLineTextCtrl(self, -1, "", style=wx.TE_WORDWRAP|wx.NO_BORDER)
        self._TCTRL_sOap = cSoapLineTextCtrl(self, -1, "", style=wx.TE_WORDWRAP|wx.NO_BORDER)
        self._TCTRL_soAp = cSoapLineTextCtrl(self, -1, "", style=wx.TE_WORDWRAP|wx.NO_BORDER)
        self._TCTRL_soaP = cSoapLineTextCtrl(self, -1, "", style=wx.TE_WORDWRAP|wx.NO_BORDER)
        self._PNL_visual_soap = cVisualSoapPresenterPnl(self, -1)
        self._TCTRL_summary = cSoapLineTextCtrl(self, -1, "", style=wx.TE_WORDWRAP|wx.NO_BORDER)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: wxgSoapNoteExpandoEditAreaPnl.__set_properties
        self.SetScrollRate(10, 10)
        self._TCTRL_summary.SetToolTipString(_("Here you can modify the cumulative summary of the problem (regardless of whether that is a new one, a health issue, or an episode)."))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: wxgSoapNoteExpandoEditAreaPnl.__do_layout
        __szr_main = wx.BoxSizer(wx.VERTICAL)
        __lbl_Soap = wx.StaticText(self, -1, _("Subjective"))
        __szr_main.Add(__lbl_Soap, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 5)
        __szr_main.Add(self._TCTRL_Soap, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 3)
        __lbl_sOap = wx.StaticText(self, -1, _("Objective"))
        __szr_main.Add(__lbl_sOap, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 5)
        __szr_main.Add(self._TCTRL_sOap, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 3)
        __lbl_soAp = wx.StaticText(self, -1, _("Assessment"))
        __szr_main.Add(__lbl_soAp, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 5)
        __szr_main.Add(self._TCTRL_soAp, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 3)
        __lbl_soaP = wx.StaticText(self, -1, _("Plan"))
        __szr_main.Add(__lbl_soaP, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 5)
        __szr_main.Add(self._TCTRL_soaP, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 3)
        __szr_main.Add(self._PNL_visual_soap, 0, wx.EXPAND, 0)
        _hline_above_summary = wx.StaticLine(self, -1)
        __szr_main.Add(_hline_above_summary, 0, wx.LEFT|wx.RIGHT|wx.TOP|wx.EXPAND, 5)
        __lbl_summary = wx.StaticText(self, -1, _("Problem summary"))
        __szr_main.Add(__lbl_summary, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 5)
        __szr_main.Add(self._TCTRL_summary, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 3)
        self.SetSizer(__szr_main)
        __szr_main.Fit(self)
        # end wxGlade

# end of class wxgSoapNoteExpandoEditAreaPnl


