# -*- coding: UTF-8 -*-
#
# generated by wxGlade
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
from Gnumed.wxpython.gmListWidgets import cReportListCtrl
# end wxGlade


class wxgXdtListPnl(wx.ScrolledWindow):
	def __init__(self, *args, **kwds):
		# begin wxGlade: wxgXdtListPnl.__init__
		kwds["style"] = kwds.get("style", 0) | wx.BORDER_NONE | wx.TAB_TRAVERSAL
		wx.ScrolledWindow.__init__(self, *args, **kwds)
		self._LCTRL_xdt = cReportListCtrl(self, wx.ID_ANY, style=wx.BORDER_NONE | wx.LC_REPORT)
		self._BTN_load = wx.Button(self, wx.ID_ANY, _("load file"))

		self.__set_properties()
		self.__do_layout()

		self.Bind(wx.EVT_BUTTON, self._on_load_button_pressed, self._BTN_load)
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: wxgXdtListPnl.__set_properties
		self.SetScrollRate(10, 10)
		self._LCTRL_xdt.SetFocus()
		self._BTN_load.SetToolTip(_("Load an xDT file."))
		self._BTN_load.SetDefault()
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: wxgXdtListPnl.__do_layout
		_szr_main = wx.BoxSizer(wx.VERTICAL)
		_szr_main.Add(self._LCTRL_xdt, 1, wx.EXPAND, 0)
		_szr_main.Add(self._BTN_load, 0, 0, 0)
		self.SetSizer(_szr_main)
		_szr_main.Fit(self)
		self.Layout()
		# end wxGlade

	def _on_load_button_pressed(self, event):  # wxGlade: wxgXdtListPnl.<event_handler>
		print("Event handler '_on_load_button_pressed' not implemented!")
		event.Skip()

# end of class wxgXdtListPnl
